/* Syntari agent and workflow patterns. All demonstrations run locally. */
(() => {
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const b=(label,action,cls='small',extra='')=>`<button type="button" class="button ${cls}" data-agent-action="${action}" ${extra}>${label}</button>`;
 const surface=(kind,html)=>`<div class="agent-surface" data-agent-kind="${kind}">${html}</div>`;
 const header=(ic,title,meta='')=>`<div class="agent-heading">${icon(ic)}<strong>${title}</strong><span class="hint">${meta}</span></div>`;
 const jobs=new WeakMap();
 const conversations=new WeakMap();
 const tasks=['Review the workspace','Prepare the changes','Check the details','Finish the handoff'];
 const taskRows=(step=0)=>tasks.map((t,i)=>`<li class="${i<step?'is-complete':i===step?'is-current':''}"><span class="task-mark">${icon(i<step?'circlecheck':i===step?'clock':'circle')}</span><span>${t}<small>${i<step?'Completed':i===step?'Ready to run':'Pending'}</small></span><span class="task-percent">${i<step?'100%':''}</span></li>`).join('');
 const todo=()=>surface('todo',`<details class="agent-disclosure" open><summary>${icon('list-todo')}<span>Workspace plan<small data-todo-count>0 of 4 completed</small></span>${icon('down')}</summary><ol class="agent-tasks">${taskRows()}</ol></details><div class="agent-footer"><span class="hint" data-run-status role="status">Ready when you are</span>${b('Run plan','todo-run')}${b(icon('square'),'todo-stop','small ghost','aria-label="Stop plan" disabled')}</div>`);
 const approval=(tool=false)=>surface('approval',`${header(tool?'terminal':'circlecheck',tool?'Allow this tool?':'Review the changes','Your decision')}<p>${tool?'Read the files in your workspace to prepare a summary.':'Three updated pages are ready for your review.'}</p><div class="agent-inset">${icon(tool?'folder':'file')} ${tool?'Workspace files · read only':'Homepage, About, and Contact'}</div><p class="hint">Local demonstration. No external action is performed.</p><div class="agent-decision" role="status"></div><div class="agent-footer">${b('Decline','reject','small ghost')}${b('Approve','approve','small primary')}</div>`);
 const code=()=>surface('code',`${header('code','theme.css','CSS') }<pre><code>:root {
  --surface: #ffffff;
  --accent: #918df6;
  --radius-card: 18px;
}</code></pre><div class="agent-footer"><span class="hint">Syntari foundations</span>${b(icon('copy')+' Copy','copy-code')}</div>`);
 const diff=()=>surface('diff',`<details class="agent-disclosure" open><summary>${icon('file')}<span>layout.css<small>2 additions · 2 deletions</small></span>${icon('down')}</summary><pre class="diff-lines"><code><span class="diff-neutral">  .card {</span><span class="diff-remove">−   border-radius: 8px;</span><span class="diff-add">+   border-radius: var(--radius-card);</span><span class="diff-remove">−   background: white;</span><span class="diff-add">+   background: var(--surface);</span><span class="diff-neutral">  }</span></code></pre></details><div class="agent-decision" role="status"></div><div class="agent-footer">${b('Keep changes','approve','small primary')}${b('Discard','reject','small ghost')}</div>`);
 const result=()=>surface('result',`<details class="agent-disclosure"><summary>${icon('terminal')}<span>Workspace check<small>3 files checked · all passed</small></span>${badge('Complete','green')}${icon('down')}</summary><dl class="metadata-list"><div><dt>Files</dt><dd>3</dd></div><div><dt>Warnings</dt><dd>0</dd></div><div><dt>Duration</dt><dd>240 ms</dd></div></dl><p class="hint">Local sample output</p></details>${b('Run again','tool-run','small ghost')}`);
 const streamText='Your workspace is ready. The new components share Syntari’s colors, spacing, and quiet motion. You can review the changes, adjust a detail, or start something new.';
 const stream=()=>surface('stream',`${header('bot','Syntari assistant','Local preview')}<div class="stream-content" aria-live="off">A little help, when you need it.</div><span class="sr-only" data-stream-status role="status"></span><div class="agent-footer">${b('Generate response','stream-start','small primary')}${b(icon('square')+' Stop','stream-stop','small ghost','disabled')}</div>`);
 const citations=()=>surface('citations',`${header('link','Sources','2 references')}<p>Built around shared tokens and explicit interaction states.</p><details class="citation"><summary><span class="citation-number">1</span> Syntari foundations ${icon('down')}</summary><p>Semantic colors, spacing, typography, and motion are shared across every component.</p>${b('View foundations','foundations','small ghost')}</details><details class="citation"><summary><span class="citation-number">2</span> Component behavior ${icon('down')}</summary><p>Examples respond to keyboard and pointer input, with reduced-motion support.</p>${b('View component guidance','foundations','small ghost')}</details>`);
 const activity=()=>surface('activity',`${header('list','Recent activity','This run')}<ol class="agent-timeline"><li>${icon('circlecheck')}<span>Workspace opened<small>Ready for the next step</small></span><time>now</time></li></ol><div class="agent-footer">${b('Add event','activity-add')}${b('Clear','activity-clear','small ghost')}</div>`);
 const loading=()=>surface('loading',`${header('bot','Working on it','Preview')}<div class="agent-loading" role="status"><span class="spinner"></span> Looking through your workspace</div><div class="agent-loading-lines" aria-hidden="true"><span></span><span></span><span></span></div><div class="agent-footer">${b('Next state','loading-next','small ghost')}</div>`);
 const message=()=>surface('message',`${header('bot','Syntari assistant','just now')}<p>A good starting point: one shared set of components, with room to make it yours.</p><div class="agent-footer">${b(icon('copy'),'copy-message','small ghost','aria-label="Copy message"')}${b(icon('thumbs-up'),'like','small ghost','aria-label="Helpful response" aria-pressed="false"')}${b(icon('rotate-ccw'),'regenerate','small ghost','aria-label="Regenerate message"')}</div>`);
 const composer=()=>`<form class="agent-composer" data-agent-prompt><label class="sr-only">Message to Syntari<textarea name="prompt" rows="2" placeholder="What would you like to make?" required maxlength="1000"></textarea></label><div class="composer-actions"><label class="attachment-button" title="Attach file">${icon('paperclip')}<input type="file" aria-label="Attach a file" data-agent-attachment></label><span class="hint" data-attachment-name>Ask Syntari</span><button type="submit" class="icon-button primary" aria-label="Send message">${icon('arrow-up')}</button></div></form>`;
 const chat=()=>surface('chat',`<div class="agent-chat-layout"><aside class="agent-chat-sidebar"><strong>Conversations</strong>${b(icon('plus')+' New chat','new-chat','small ghost')}<button class="conversation active" data-agent-action="conversation">Workspace ideas</button><button class="conversation" data-agent-action="conversation">Release checklist</button></aside><div class="agent-chat-main">${header('bot','Syntari','Local demo')}<div class="agent-messages" role="log" aria-label="Conversation"><div class="assistant-message">What are you working on?</div></div>${composer()}</div></div>`);
 const imagePreview=()=>surface('image',`${header('image','Image preview','Sample artwork')}<div class="agent-image-placeholder">${icon('image')}<span>Your next visual, right here.</span></div><p class="hint">Demonstrates loading and preview states with local artwork.</p><div class="agent-footer">${b('Generate preview','image-generate','small primary')}</div>`);
 const tree=()=>surface('tree',`<div class="file-tree"><details open><summary>${icon('chevron')}${icon('folder')} Workspace</summary><details open><summary>${icon('chevron')}${icon('folder')} Components</summary>${['Button','Card','Dialog'].map(t=>b(icon('file')+t+'.html','tree-file','ghost small',`data-file="${t}"`)).join('')}</details><details><summary>${icon('chevron')}${icon('folder')} Foundations</summary>${b(icon('file')+'tokens.css','tree-file','ghost small','data-file="Tokens"')}</details></details><p class="hint" data-tree-status role="status">Choose a file to preview its purpose.</p></div>`);
 const rail=()=>surface('rail',`<div class="preview-stage"><span class="preview-orb"></span><span data-rail-title>Brand exploration</span></div><div class="preview-rail" role="group" aria-label="Choose artwork">${['Brand exploration','Color study','Spatial rhythm'].map((t,i)=>`<button data-agent-action="rail-select" data-rail="${i}" aria-label="${t}" aria-pressed="${!i}"><span class="rail-orb orb-${i}"></span></button>`).join('')}</div>`);
 const otp=()=>surface('otp',`${header('lock','Check your inbox')}<p>Enter the six-digit code. Use 123456 in this demo.</p><form data-otp-form><label class="field">Verification code<input name="code" class="otp-input" inputmode="numeric" autocomplete="one-time-code" pattern="[0-9]{6}" maxlength="6" placeholder="· · · · · ·" required></label><p role="status" class="hint" data-otp-status></p><button class="button primary small" type="submit">Verify code</button></form>`);
 const feedback=()=>surface('feedback',`${header('chat','How did this feel?')}<form data-feedback-form><fieldset><legend class="sr-only">Rating</legend>${['Could be better','Good','Great'].map((t,i)=>`<label class="choice"><input type="radio" name="rating" value="${t}" ${i===1?'checked':''}>${t}</label>`).join('')}</fieldset><label class="field">Anything to add?<textarea name="note" rows="2" placeholder="What worked well, or what could improve?" maxlength="300"></textarea></label><button class="button small primary" type="submit">Send feedback</button><p class="hint" role="status">Saved in this preview only.</p></form>`);
 const notifications=()=>surface('notifications',`${header('bell','Inbox','2 unread')}<div class="notification-items">${['Jamie shared a project','Your export is ready'].map(t=>`<div class="notification-item"><span class="status-dot"></span><span>${t}<small>Just now</small></span>${b(icon('x'),'dismiss-notification','small ghost',`aria-label="Dismiss ${t}"`)}</div>`).join('')}</div><div class="agent-footer">${b('Add notification','add-notification','small secondary')}</div>`);
 const context=()=>surface('context',`<div class="context-target" tabindex="0" aria-label="Project actions. Press Shift F10 or use the actions button.">${icon('folder')}<h3>Brand assets</h3><p>Right-click or open the actions.</p>${b('Actions '+icon('more'),'context-open')}<div class="agent-context-menu" role="menu" hidden>${['Duplicate','Rename','Archive'].map(t=>b(icon(t==='Duplicate'?'copy':t==='Rename'?'edit':'folder')+t,'context-choice','ghost small',`role="menuitem" data-choice="${t}"`)).join('')}</div><span data-context-status role="status" class="hint"></span></div>`);
 const scheduler=()=>surface('scheduler',`${header('calendar','Choose a meeting time','30 minutes')}<div class="schedule-days" role="group" aria-label="Day">${['Monday','Tuesday','Wednesday'].map((d,i)=>b(d.slice(0,3),'schedule-day','small',`data-day="${d}" aria-pressed="${!i}"`)).join('')}</div><div class="schedule-times" role="group" aria-label="Time">${['09:00','10:30','14:00','15:30'].map(t=>b(t,'schedule-time','small',`data-time="${t}" aria-pressed="false"`)).join('')}</div><p class="hint" role="status" data-schedule-status>Choose a time on Monday.</p>${b('Confirm time','schedule-confirm','small primary is-hidden','disabled')}`);
 const wheel=()=>surface('wheel',`${header('clock','Pick a duration')}<div class="duration-wheel" role="listbox" aria-label="Duration">${[15,30,45,60,90].map(n=>`<button type="button" role="option" aria-selected="${n===30}" tabindex="${n===30?0:-1}" data-agent-action="wheel-select">${n} minutes</button>`).join('')}</div><p class="hint">Scroll, click, or use the arrow keys.</p>`);
 const swipe=()=>surface('swipe',`${header('list','Reading list')}<div class="swipe-items">${['Design notes','Project brief','Release checklist'].map(t=>`<div class="swipe-item"><span>${icon('file')}${t}</span>${b('Archive','swipe-archive','small ghost')}</div>`).join('')}</div><p class="hint" role="status">Swipe left or choose Archive.</p>${b('Undo','swipe-undo','small ghost','disabled')}`);
 const notfound=()=>surface('notfound',`<div class="empty-icon">${icon('search')}</div><h3>Nothing at this address.</h3><p>Let’s get you back to familiar ground.</p>${b('Back to components','gallery','small')}`);
 function register(){categoryIcons.Agents='bot';
 const rows=[
 ['Agent todo list','Agents','Run / stop / replay',todo,'A collapsible task plan with explicit task states and bounded progress.'],
 ['Agent message','Agents','Copy / feedback / regenerate',message,'A response with source identity and contextual actions.'],
 ['Message bubbles','Agents','User / assistant',()=>surface('bubbles','<div class="user-message">A calmer space for the team.</div><div class="assistant-message">Let’s start with the things you use every day.</div>'),'Role-specific message surfaces.'],
 ['Message scroller','Agents','Scroll / jump to latest',()=>surface('scroller',`<div class="agent-messages scroll-demo" role="log" aria-label="Message history">${Array.from({length:8},(_,i)=>`<div class="${i%2?'user':'assistant'}-message">${['Where should we begin?','With the workspace.','The basics are ready.','Let’s add the details.'][i%4]}</div>`).join('')}</div>${b('Jump to latest '+icon('down'),'jump-latest','small')}`),'A bounded message history with an explicit jump action.'],
 ['Prompt input','Agents','Compose / attachments',()=>surface('prompt',`${composer()}<p class="hint" data-prompt-status role="status">Local preview · nothing is sent</p>`),'A growing prompt field with a local attachment picker and submit feedback.'],
 ['Code block','Agents','Copy',code,'Code is preserved as text, with a copy action.'],
 ['Approval card','Agents','Approve / decline / reset',()=>approval(false),'A decision card that records an explicit choice.'],
 ['File diff','Agents','Expand / keep / discard',diff,'Readable additions and deletions with a review outcome.'],
 ['Tool result','Agents','Expand / rerun',result,'Inspect structured output and run a bounded local simulation.'],
 ['Streaming response','Agents','Start / stop / regenerate',stream,'A cancellable response preview. Completion is announced without reading every character.'],
 ['Image generation','Agents','Loading / preview',imagePreview,'Local artwork illustrates generation states; no model service is called.'],
 ['Tool approval','Agents','Permission / outcome',()=>approval(true),'Show the requested scope before the user decides.'],
 ['Citations','Agents','Expand / source links',citations,'Numbered references disclose context next to a response.'],
 ['Agent activity','Agents','Append / clear',activity,'A chronological record separate from the task plan.'],
 ['Agent loading states','Agents','Searching / preparing / ready',loading,'Feedback before a durable task plan is available.'],
 ['AI sidebar','Agents','Conversations / new chat',chat,'Conversation navigation next to a working composer.'],
 ['Chat workspace','Agents','Compose / history / new chat',chat,'A composed local conversation with retained messages between previews.'],
 ['File tree','Navigation','Nested folders / selection',tree,'Explore nested files with disclosures and preview feedback.'],
 ['Preview rail','Content','Select / transition',rail,'A compact artwork selector updates a shared preview.'],
 ['OTP input','Form controls','Paste / verify / error',otp,'One accessible code field supports paste, autofill, and validation.'],
 ['Feedback widget','Feedback & status','Rate / submit',feedback,'Collect a rating and optional note within the local preview.'],
 ['Notification stack','Feedback & status','Add / dismiss',notifications,'A compact inbox with per-notification dismissal.'],
 ['Context menu','Overlay','Pointer / keyboard',context,'Secondary actions open with right-click, Shift F10, or an explicit button.'],
 ['Availability scheduler','Form controls','Day / time / confirm',scheduler,'Choose a day and available time with explicit confirmation.'],
 ['Wheel picker','Form controls','Scroll / keyboard',wheel,'A bounded duration list with scroll snapping and keyboard selection.'],
 ['Swipeable list','Table & list','Archive / undo',swipe,'Pointer swipes and visible actions lead to the same reversible outcome.'],
 ['Not found','Content','Recovery',notfound,'An actionable empty route state.']
 ];rows.forEach(([name,cat,variants,render,description])=>add(name,cat,variants,description,render()));}
 function saveConversation(root){let data=conversations.get(root);if(!data){data={current:'Workspace ideas',items:new Map()};conversations.set(root,data)}data.items.set(data.current,root.querySelector('.agent-messages').innerHTML);return data}
 function announce(root,text){let status=root.querySelector('[data-run-status]');if(status)status.textContent=text;}
 function cancel(root){const job=jobs.get(root);if(job){clearInterval(job);clearTimeout(job);jobs.delete(root)}}
 function motion(el){if(!matchMedia('(prefers-reduced-motion: reduce)').matches)SyntariMotion.panel(el)}
 function finishTodo(root){cancel(root);root.querySelector('[data-agent-action="todo-run"]').disabled=false;root.querySelector('[data-agent-action="todo-run"]').textContent='Replay';root.querySelector('[data-agent-action="todo-stop"]').disabled=true;announce(root,'All tasks completed');}
 function runTodo(root){cancel(root);let tick=0;const run=root.querySelector('[data-agent-action="todo-run"]'),stop=root.querySelector('[data-agent-action="todo-stop"]');run.disabled=true;stop.disabled=false;root.querySelector('details').open=true;root.querySelector('ol').innerHTML=taskRows(0);root.querySelector('[data-todo-count]').textContent='0 of 4 completed';announce(root,'Plan running');const job=setInterval(()=>{if(!root.isConnected){cancel(root);return}tick++;const step=Math.floor(tick/4);root.querySelectorAll('li').forEach((li,i)=>{li.classList.toggle('is-complete',i<step);li.classList.toggle('is-current',i===step);li.querySelector('small').textContent=i<step?'Completed':i===step?'In progress':'Pending';li.querySelector('.task-percent').textContent=i<step?'100%':i===step?`${tick%4*25}%`:'';const mark=li.querySelector('.task-mark'),phase=i<step?'complete':i===step?'current':'pending';if(mark.dataset.phase!==phase){mark.dataset.phase=phase;mark.innerHTML=icon(i<step?'circlecheck':i===step?'clock':'circle');motion(mark)}});root.querySelector('[data-todo-count]').textContent=`${step} of 4 completed`;if(tick%4===0)announce(root,`${step} tasks completed`);if(step===4)finishTodo(root)},240);jobs.set(root,job)}
 function runStream(root){cancel(root);const output=root.querySelector('.stream-content');output.textContent='';root.querySelector('[data-agent-action="stream-start"]').disabled=true;root.querySelector('[data-agent-action="stream-stop"]').disabled=false;let n=0;const complete=()=>{cancel(root);root.querySelector('[data-agent-action="stream-start"]').disabled=false;root.querySelector('[data-agent-action="stream-start"]').textContent='Regenerate';root.querySelector('[data-agent-action="stream-stop"]').disabled=true;root.querySelector('[data-stream-status]').textContent='Response complete.'};if(matchMedia('(prefers-reduced-motion: reduce)').matches){output.textContent=streamText;complete();return}jobs.set(root,setInterval(()=>{if(!root.isConnected){cancel(root);return}n+=4;output.textContent=streamText.slice(0,n);if(n>=streamText.length)complete()},28));}
 function decide(root,approved){const result=root.querySelector('.agent-decision');result.textContent=approved?'Approved · ready for the next step':'Declined · no changes applied';result.className='agent-decision '+(approved?'accepted':'declined');root.querySelector('.agent-footer').innerHTML=b('Reset preview','decision-reset','small ghost');motion(result);result.setAttribute('tabindex','-1');result.focus()}
 function openContext(root){const menu=root.querySelector('.agent-context-menu');menu.hidden=false;menu.querySelector('button').focus();motion(menu)}
 document.addEventListener('click',async e=>{
 const el=e.target.closest('[data-agent-action]');if(!el){document.querySelectorAll('.agent-context-menu').forEach(x=>x.hidden=true);return}const action=el.dataset.agentAction,root=el.closest('[data-agent-kind]');if(!root)return;
 if(action==='todo-run')runTodo(root);
 if(action==='todo-stop'){cancel(root);root.querySelector('[data-agent-action="todo-run"]').disabled=false;el.disabled=true;root.querySelector('[data-agent-action="todo-run"]').textContent='Restart';const current=root.querySelector('.is-current small');if(current)current.textContent='Stopped';announce(root,'Plan stopped. Restart when ready.')}
 if(action==='stream-start')runStream(root);
 if(action==='stream-stop'){cancel(root);el.disabled=true;root.querySelector('[data-agent-action="stream-start"]').disabled=false;root.querySelector('[data-stream-status]').textContent='Response stopped.'}
 if(action==='approve'||action==='reject')decide(root,action==='approve');
 if(action==='decision-reset'){const wrap=document.createElement('div');wrap.innerHTML=root.dataset.agentKind==='diff'?diff():approval(root.textContent.includes('Allow this tool'));root.innerHTML=wrap.firstElementChild.innerHTML}
 if(action==='copy-code'||action==='copy-message'){try{await navigator.clipboard.writeText(root.querySelector(action==='copy-code'?'code':'p').textContent);showToast('Copied to clipboard.')}catch{showToast('Copy unavailable. Select the text to copy.')}}
 if(action==='like'){const liked=el.getAttribute('aria-pressed')!=='true';el.setAttribute('aria-pressed',liked);showToast(liked?'Thanks for the feedback.':'Feedback removed.')}
 if(action==='regenerate'){root.querySelector('p').textContent=root.dataset.version?'A good starting point: one shared set of components, with room to make it yours.':'Start with the essentials. Add complexity when your product needs it.';root.dataset.version=root.dataset.version?'':'1';motion(root.querySelector('p'))}
 if(action==='tool-run'){el.disabled=true;el.textContent='Checking…';jobs.set(root,setTimeout(()=>{if(!root.isConnected)return;el.disabled=false;el.textContent='Run again';root.querySelector('details').open=true;motion(root.querySelector('dl'));showToast('Workspace check complete.')},650))}
 if(action==='activity-add'){const li=document.createElement('li');li.innerHTML=icon('circlecheck')+'<span>Component reviewed<small>Ready for the next step</small></span><time>now</time>';root.querySelector('ol').append(li);if(root.querySelectorAll('li').length>5)root.querySelector('li').remove();motion(li)}
 if(action==='activity-clear')root.querySelector('ol').replaceChildren();
 if(action==='loading-next'){const states=['Preparing a response','Ready for your review','Looking through your workspace'];const n=Number(root.dataset.stage||0);root.querySelector('.agent-loading').innerHTML=icon(n===1?'circlecheck':'clock')+states[n%3];root.dataset.stage=n+1;root.querySelector('.agent-loading-lines').hidden=n%3===1}
 if(action==='image-generate'){el.disabled=true;el.textContent='Preparing…';const frame=root.querySelector('.agent-image-placeholder');frame.innerHTML='<span class="spinner"></span><span>Preparing preview</span>';jobs.set(root,setTimeout(()=>{if(!root.isConnected)return;frame.innerHTML='<span class="generated-syntari" aria-label="Abstract lavender rings"></span>';el.textContent='Generate again';el.disabled=false;motion(frame)},850))}
 if(action==='jump-latest'){const scroll=root.querySelector('.agent-messages');scroll.scrollTo({top:scroll.scrollHeight,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'})}
 if(action==='new-chat'){const state=saveConversation(root);state.current='New conversation '+(state.items.size+1);root.querySelectorAll('.conversation').forEach(x=>x.classList.remove('active'));const tab=document.createElement('button');tab.className='conversation active';tab.dataset.agentAction='conversation';tab.textContent=state.current;root.querySelector('.agent-chat-sidebar').append(tab);root.querySelector('.agent-messages').innerHTML='<div class="assistant-message">What would you like to explore?</div>';root.querySelector('textarea').focus()}
 if(action==='conversation'){const state=saveConversation(root);state.current=el.textContent;root.querySelectorAll('.conversation').forEach(x=>x.classList.toggle('active',x===el));root.querySelector('.agent-messages').innerHTML=state.items.get(state.current)||`<div class="assistant-message">${esc(el.textContent)} — ready to pick up where you left off.</div>`;motion(root.querySelector('.agent-messages'))}
 if(action==='tree-file'){root.querySelectorAll('[data-file]').forEach(x=>x.classList.toggle('active',x===el));root.querySelector('[data-tree-status]').textContent=`${el.dataset.file}: ${ {Button:'Shared actions with focus and pressed states.',Card:'A surface for related content.',Dialog:'Focused tasks with keyboard dismissal.',Tokens:'Shared colors, spacing, and motion.'}[el.dataset.file]}`;}
 if(action==='rail-select'){root.querySelectorAll('[data-rail]').forEach(x=>x.setAttribute('aria-pressed',x===el));root.querySelector('.preview-stage').dataset.color=el.dataset.rail;root.querySelector('[data-rail-title]').textContent=el.getAttribute('aria-label');motion(root.querySelector('.preview-stage'))}
 if(action==='dismiss-notification'){const item=el.closest('.notification-item');await SyntariMotion.remove(item);root.querySelector('.agent-heading .hint').textContent=root.querySelectorAll('.notification-item').length+' unread';root.querySelector('[data-agent-action="add-notification"]').focus()}
 if(action==='add-notification'){const item=document.createElement('div');item.className='notification-item';item.innerHTML='<span class="status-dot"></span><span>New workspace update<small>Just now</small></span>'+b(icon('x'),'dismiss-notification','small ghost','aria-label="Dismiss workspace update"');SyntariMotion.rearrange(root.querySelector('.notification-items'),()=>root.querySelector('.notification-items').prepend(item));root.querySelector('.agent-heading .hint').textContent=root.querySelectorAll('.notification-item').length+' unread';motion(item)}
 if(action==='context-open')openContext(root);
 if(action==='context-choice'){root.querySelector('.agent-context-menu').hidden=true;root.querySelector('[data-context-status]').textContent=el.dataset.choice+' selected in preview.';root.querySelector('[data-agent-action="context-open"]').focus()}
 if(action==='schedule-day'){const confirm=root.querySelector('[data-agent-action="schedule-confirm"]');root.classList.remove('is-confirmed');confirm.textContent='Confirm time';confirm.classList.add('is-hidden');motion(root.querySelector('.schedule-times'));root.querySelectorAll('[data-day]').forEach(x=>x.setAttribute('aria-pressed',x===el));root.dataset.day=el.dataset.day;root.querySelector('[data-schedule-status]').textContent=`Choose a time on ${el.dataset.day}.`;root.querySelectorAll('[data-time]').forEach(x=>x.setAttribute('aria-pressed',false));confirm.disabled=true}
 if(action==='schedule-time'){const confirm=root.querySelector('[data-agent-action="schedule-confirm"]');root.classList.remove('is-confirmed');confirm.textContent='Confirm time';confirm.classList.remove('is-hidden');motion(root.querySelector('[data-schedule-status]'));root.querySelectorAll('[data-time]').forEach(x=>x.setAttribute('aria-pressed',x===el));root.dataset.time=el.dataset.time;root.querySelector('[data-schedule-status]').textContent=`${root.dataset.day||'Monday'} at ${el.dataset.time}`;confirm.disabled=false}
 if(action==='schedule-confirm'){root.classList.add('is-confirmed');el.innerHTML=icon('check')+' Confirmed';el.disabled=true;motion(root.querySelector('[data-schedule-status]'));root.querySelector('[data-schedule-status]').textContent=`Selected: ${root.dataset.day||'Monday'} at ${root.dataset.time}. Local preview only.`}
 if(action==='wheel-select'){root.querySelectorAll('[role=option]').forEach(x=>{x.setAttribute('aria-selected',x===el);x.tabIndex=x===el?0:-1});el.scrollIntoView({block:'nearest',behavior:'smooth'})}
 if(action==='swipe-archive'){const item=el.closest('.swipe-item');await SyntariMotion.remove(item);delete item.dataset.removing;item.inert=false;root._archived=item;root.querySelector('[data-agent-action="swipe-undo"]').disabled=false;root.querySelector('p').textContent='Item archived. Undo to restore it.';root.querySelector('[data-agent-action="swipe-undo"]').focus()}
 if(action==='swipe-undo'&&root._archived){SyntariMotion.rearrange(root.querySelector('.swipe-items'),()=>root.querySelector('.swipe-items').append(root._archived));root._archived=null;el.disabled=true;root.querySelector('p').textContent='Item restored.'}
 if(action==='foundations'||action==='gallery'){setView(action);document.querySelector('#main')?.scrollIntoView({block:'start'})}
 });
 document.addEventListener('submit',e=>{const form=e.target,root=form.closest('[data-agent-kind]');if(!root)return;
 if(form.matches('[data-agent-prompt]')){e.preventDefault();const text=form.elements.prompt.value.trim();if(!text)return;const log=root.querySelector('.agent-messages');if(log){const user=document.createElement('div');user.className='user-message';user.textContent=text;log.append(user);const reply=document.createElement('div');reply.className='assistant-message';reply.textContent='Saved to this local conversation. Connect your own assistant to respond to messages.';log.append(reply);log.scrollTop=log.scrollHeight;motion(reply)}else root.querySelector('[data-prompt-status]').textContent='Prompt captured in preview: '+text;form.elements.prompt.value='';form.elements.prompt.focus()}
 if(form.matches('[data-otp-form]')){e.preventDefault();const valid=form.elements.code.value==='123456';form.classList.toggle('is-verified',valid);const submit=form.querySelector('[type=submit]');submit.innerHTML=valid?icon('check')+' Verified':'Verify code';submit.disabled=valid;motion(form.querySelector('[data-otp-status]'));form.querySelector('[data-otp-status]').textContent=valid?'Code verified. You’re ready to continue.':'That code did not match. Try 123456.';form.elements.code.setAttribute('aria-invalid',!valid);if(!valid)form.elements.code.focus()}
 if(form.matches('[data-feedback-form]')){e.preventDefault();form.querySelector('[role=status]').textContent='Thanks — your feedback was captured in this preview.';form.querySelector('button').innerHTML=icon('check')+' Update feedback';motion(form.querySelector('[role=status]'))}
 });
 document.addEventListener('input',e=>{const form=e.target.closest('[data-otp-form]');if(form){e.target.value=e.target.value.replace(/[^0-9]/g,'').slice(0,6);form.classList.remove('is-verified');e.target.removeAttribute('aria-invalid');const submit=form.querySelector('[type=submit]');submit.disabled=false;submit.textContent='Verify code';form.querySelector('[data-otp-status]').textContent='';}});
 document.addEventListener('change',e=>{if(e.target.matches('[data-agent-attachment]'))e.target.closest('form').querySelector('[data-attachment-name]').textContent=e.target.files[0]?.name||'Ask Syntari'});
 document.addEventListener('contextmenu',e=>{const root=e.target.closest('[data-agent-kind="context"]');if(root){e.preventDefault();openContext(root)}});
 document.addEventListener('keydown',e=>{const root=e.target.closest('[data-agent-kind]');if(!root)return;if(root.dataset.agentKind==='context'){const menu=root.querySelector('.agent-context-menu');if(e.key==='F10'&&e.shiftKey){e.preventDefault();openContext(root)}if(e.key==='Escape'&&!menu.hidden){e.preventDefault();menu.hidden=true;root.querySelector('[data-agent-action="context-open"]').focus()}if(!menu.hidden&&['ArrowDown','ArrowUp'].includes(e.key)){e.preventDefault();const items=[...menu.querySelectorAll('button')];items[(items.indexOf(e.target)+(e.key==='ArrowDown'?1:items.length-1))%items.length].focus()}}
 if(root.dataset.agentKind==='wheel'&&['ArrowDown','ArrowUp','Home','End'].includes(e.key)){e.preventDefault();const items=[...root.querySelectorAll('[role=option]')],i=items.indexOf(e.target),next=e.key==='Home'?0:e.key==='End'?items.length-1:Math.max(0,Math.min(items.length-1,i+(e.key==='ArrowDown'?1:-1)));items[next].click();items[next].focus()}});
 let drag=null;document.addEventListener('pointerdown',e=>{const item=e.target.closest('.swipe-item');if(item&&!e.target.closest('button')){drag={item,x:e.clientX,y:e.clientY,pointerId:e.pointerId};item.setPointerCapture?.(e.pointerId);item.classList.add('is-dragging')}});document.addEventListener('pointermove',e=>{if(!drag||e.pointerId!==drag.pointerId)return;const dx=Math.min(0,Math.max(-110,e.clientX-drag.x));if(Math.abs(e.clientY-drag.y)>45)return;drag.item.style.setProperty('--swipe-offset',`${dx}px`)});document.addEventListener('pointerup',e=>{if(!drag||e.pointerId!==drag.pointerId)return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y;const item=drag.item;item.classList.remove('is-dragging');item.style.removeProperty('--swipe-offset');if(dx<-56&&Math.abs(dy)<45)item.querySelector('button').click();drag=null});document.addEventListener('pointercancel',()=>{if(drag){drag.item.classList.remove('is-dragging');drag.item.style.removeProperty('--swipe-offset')}drag=null});
 window.SyntariAgents={todo,approval,code,diff,result,stream,citations,activity,loading,message,composer,chat};register();renderGallery();hydrate();
})();
