export function guideContent(id,{code,command,apiTable,commonAPI}) {
 const section=(name,body)=>`<section class="docs-section"><h2>${name}</h2>${body}</section>`;
 const p=text=>`<p class="docs-prose">${text}</p>`;
 const snippets={
  usage:`<div id="action"></div>\n\n<script type="module">\n  import { mount } from './components/orbit/button.js';\n\n  const button = await mount('#action', {\n    configure(root) {\n      root.querySelector('.primary').textContent = 'Save changes';\n    },\n    onAction(event, root) {\n      if (event.target.closest('.primary')) {\n        // Connect your application's save action here.\n      }\n    }\n  });\n</script>`,
  theme:`/* Shared tokens work in both themes. */\n:root {\n  --accent: #918df6;\n  --accent-soft: #918df614;\n  --accent-text: #6558bd;\n  --radius-card: 18px;\n}\n\n[data-theme="dark"] {\n  --accent: #9580ff;\n  --accent-text: #b9aaff;\n}\n\n/* In your application: */\n/* document.documentElement.dataset.theme = 'dark'; */`,
  manual:`<div id="example">\n  <!-- Paste the component's HTML from its Code tab here. -->\n</div>\n\n<script type="module">\n  import { prepare } from './orbit/runtime/orbit.js';\n  await prepare(document.querySelector('#example'));\n</script>`
 };
 const pages={
 'getting-started':{title:'A little less setup.',description:'A practical starting point for building with Orbit. Use the components, keep the source, and make the details yours.',body:
 p('Orbit 0.2 is a library of 107 interactive HTML patterns, with CSS tokens and plain JavaScript interactions. Each component has its own page, live states, source, and a working usage example. There are no React components or server services hidden behind the examples.')+
 section('1. Add your first component',p('Run the source installer from your project directory. It copies the selected component and the shared Orbit runtime into your project. Node.js 22 or later is required.')+code(command('button'),'Terminal','shell'))+
 section('2. Make it part of your page',p('Mount an example into a container, then customize its DOM and connect your own actions. The styles, fonts, and interaction handlers load from the local runtime folder.')+code(snippets.usage,'index.html','html'))+
 section('3. Explore the states',p('Every page includes an interactive preview and additional states or layouts. Use the Preview, Usage, and Code tabs to move between the result and its implementation. State selections update the Usage example too.'))+
 section('4. Connect your product',p('Gallery records, uploads, generation, approvals, sign-in, and messages demonstrate local UI behavior. Replace their sample data and service actions before using them in a connected product. The source is intentionally included for this work.'))},
 'installation':{title:'Your source. Your project.',description:'Use the CLI for a quick start, or bring the files in manually. Both paths install the same versioned source.',body:
 section('CLI installation',p('The command downloads this site’s versioned package archive and runs its Orbit executable. It does not depend on a published npm package named orbit-ui. Your component page generates the command for its own slug.')+code(command('button slider'),'Terminal','shell')+p('The default destination is <code>./components/orbit</code>. Add <code>--dir ./ui/orbit</code> to choose another folder. Run <code>orbit list</code> through the same package command to see every slug.'))+
 section('Manual installation',p('Download the source archive from any component page. Extract it and copy <code>package/kit/runtime</code> to <code>orbit/runtime</code> in your project. Copy the component module and HTML from <code>package/kit/components</code> to <code>orbit/</code>. Keep the module next to the runtime directory.')+code(snippets.manual,'index.html','html')+p('For the module approach, use <code>mount</code> from the component’s JavaScript file instead. For the manual approach above, edit the copied HTML and call <code>prepare</code> once after insertion.'))+
 section('What gets installed',code('components/orbit/\n├── button.js       # component entry\n├── button.html     # editable template\n├── orbit.json      # installed version\n└── runtime/\n    ├── orbit.js    # mounting and enhancement\n    ├── tokens.css  # light and dark tokens\n    ├── styles.css  # base styling\n    ├── …           # shared interactions and patterns\n    └── assets/     # fonts and licenses','Files','text')+p('Version 0.2 uses a shared runtime for all patterns. Installation copies it once; adding another component reuses it. It is not a tree-shaken, per-component bundle.'))+
 section('Serving and upgrades',p('Use a development server or static host. ES modules and template requests require HTTP; opening an HTML file with a file:// URL is not supported. The CLI preserves existing files and refuses to overwrite a customized component. Install a later version into a new directory and review changes before migrating.'))},
 'theming':{title:'One shared language.',description:'Light and dark are two expressions of the same system. Start with the semantic tokens, then refine the details.',body:
 section('Choose a theme',code(`import { setTheme } from './components/orbit/runtime/orbit.js';\n\nsetTheme('dark'); // or 'light'\n\n// Persist the preference in your application if needed.\nlocalStorage.setItem('my-app-theme', 'dark');`,'theme.js','js')+p('The runtime changes the root <code>data-theme</code> attribute. It does not persist an application’s theme preference for you.'))+
 section('Use semantic colors',p('Use <code>--canvas</code> for the page, <code>--surface</code> for a raised region, <code>--subtle</code> for a quiet fill, and <code>--border</code> for separators. Use <code>--text</code>, <code>--muted</code>, and <code>--accent-text</code> for readable text.')+code(snippets.theme,'theme.css','css'))+
 section('Shape and spacing',p('Pill actions use <code>--radius-control</code>; cards use <code>--radius-card</code>. The spacing scale is 4, 8, 12, 16, 24, 32, and 48 pixels. Prefer the named spacing tokens when adding a composition.'))+
 section('Typography and icons',p('OpenRunde gives Orbit its soft, readable shape. The local font assets and their licenses are included in the source. Interface icons are Lucide SVGs, with shared stroke weight and sizing. Preserve accessible names on icon-only actions.'))},
 'motion':{title:'Movement, in moderation.',description:'Small transitions should explain a change, preserve context, and settle quickly.',body:
 section('A shared rhythm',apiTable([['--motion-fast','duration','140ms','Hover and press feedback.'],['--motion-medium','duration','240ms','Selection, disclosures, and state changes.'],['--motion-panel','duration','320ms','Panels and navigation.'],['--motion-data','duration','650ms','Number and chart entrances.']]))+
 section('Reduced motion',p('Orbit follows <code>prefers-reduced-motion: reduce</code>. Decorative travel is removed, numeric changes settle immediately, and streaming text appears without a character-by-character reveal. Progress remains understandable through text and status updates.')+code(`@media (prefers-reduced-motion: reduce) {\n  .my-component {\n    transition: none;\n    animation: none;\n  }\n}`,'motion.css','css'))+
 section('Keyboard and focus',p('Use native buttons and fields. Preserve the provided labels, role attributes, and expanded or selected states. Dropdowns and calendars handle keyboard navigation; modal dialogs contain focus and return it to the opener. A visible focus ring should remain easy to see in both themes.'))+
 section('Testing a composition',p('Try the full flow with Tab, Enter, Escape, and arrow keys. Repeat it at a narrow width, with long text, and with reduced motion enabled. Loading and error states should remain legible without animation or color alone.'))},
 'composition':{title:'Small details. Whole products.',description:'Build a page with a few well-chosen patterns and a clear hierarchy.',body:
 section('Start with a layout',p('Use App shell and Page header & breadcrumbs to establish navigation and context. Add a Data table for records or grouped fields for settings. The gallery’s four starter screens show settings, people, projects, and onboarding as connected flows.')+p('<a href="gallery.html?view=screens&screen=projects">Explore the starter screens</a>'))+
 section('Mount into separate containers',code(`<section aria-labelledby="project-title">\n  <h1 id="project-title">Projects</h1>\n  <div id="records"></div>\n</section>\n\n<script type="module">\n  import { mount } from './components/orbit/data-table.js';\n  const table = await mount('#records');\n\n  // When the enclosing page is removed:\n  // table.destroy();\n</script>`,'projects.html','html')+p('A mounted component owns the child element it inserts, not its parent container. Give each component a separate region. The runtime makes radio-group and field association IDs unique for each mount.'))+
 section('Keep services at the boundary',p('Use native field values and local action handlers as the boundary to your application. Demonstrations do not supply authentication, storage, billing, model calls, or upload services. Replace the local behavior in the copied interaction files when a real service must control loading, success, and failure.'))+
 section('Callbacks and shortcuts',p('onAction, onInput, and onChange run after native event dispatch, once Orbit has updated its controls. Read the new state from the supplied root. Do not use these deferred callbacks to cancel native events; attach a direct listener when preventDefault is needed. Reset and destroy cancel queued callbacks from the previous instance.')+p('In an embedded app, Command/Ctrl K opens Orbit’s command palette only while focus is inside a prepared palette component. Other app regions keep their own shortcuts. To provide a global Orbit shortcut, bind it explicitly in your app and call window.OrbitStarter.openCommand().'))+
 section('Global styles',p('The 0.2 runtime includes a base reset, typography, and shared styles. Use it as the foundation of a new page. When adding Orbit to a heavily styled existing product, review selector conflicts or isolate the preview in an iframe.'))},
 'api':{title:'A small, practical API.',description:'Mount a working pattern, enhance copied HTML, and keep access to the actual DOM.',body:
 section('mount(target, options)',p('Each installed component module exports an asynchronous <code>mount</code> function with its component slug already selected. It resolves after the source and styles have loaded.')+apiTable(commonAPI)+code(`import { mount } from './components/orbit/slider.js';\n\nconst slider = await mount('#events', {\n  onInput(event) {\n    if (event.target.matches('input[type="range"]')) {\n      console.log(Number(event.target.value));\n    }\n  }\n});`,'example.js','js'))+
 section('Mounted instance',apiTable([['element','Element','—','The inserted root, including its live child controls.'],['reset()','Promise<void>','—','Recreate the initial template and run configure again.'],['destroy()','void','—','Remove the inserted root and its callback listeners.']])+p('Reset recreates the template. It does not reset shared sample records or application services. Destroy a mounted instance before discarding its owning page.'))+
 section('prepare(root)',p('Enhances a subtree of copied HTML. Call once after inserting new component markup. It adds unique field associations, initializes controls, and prepares shared motion. Event behavior is delegated through the shared runtime. The wrapper keeps your application’s layout; prepare does not add gallery padding, minimum height, or flex layout. mount still creates an owned example wrapper with the preview layout.'))+
 section('Rolling percentages',p('After initialization, use <code>window.OrbitNumbers.set(element, value, { kind: \'percent\' })</code> to render a fractional value as a percentage with one decimal. For example, 0.481 renders and announces 48.1%. Existing number and currency formats remain available.'))+
 section('Other exports',apiTable([['getComponents()','Promise<Component[]>','—','Get the registered names, slugs, descriptions, markup, and token references.'],['setTheme(theme)','void','light | dark','Set the root data-theme attribute.'],['initialize()','Promise<Component[]>','—','Load shared assets once. mount and prepare call this automatically.']]))+
 section('Errors and supported environments',p('Unknown slugs and missing mount targets reject with descriptive errors. Asset loading errors also reject the mount promise. Handle these in your application’s error UI. Use a modern browser with ES modules, native dialog, Web Animations, and CSS custom properties. Popovers fall back to positioned panels when the browser does not expose the Popover API.'))},
 'migration':{title:'The details, documented.',description:'Orbit 0.2 turns the component gallery into a library you can browse, understand, and bring into a project.',body:
 section('What changed',p('Every one of the 107 component families now has a dedicated, shareable page. Preview states, usage, actual source, installation, element contracts, and guidance sit together. The source installer and manual archive contain the same runtime used by these pages.'))+
 section('What stays familiar',p('Orbit keeps its quiet surfaces, lavender accents, dark navigation, OpenRunde typography, Lucide icons, and subtle transitions. The existing gallery and its four starter screens remain available.'))+
 section('From 0.1',p('Existing gallery links can use <code>gallery.html</code> with the same view and screen query parameters. New component pages use <code>components/&lt;slug&gt;/</code>. The root page is now the documentation overview. Your customized 0.1 files are not overwritten by the installer.'))+
 section('Current boundary',p('The library delivers editable interaction examples and a shared browser runtime. It is not a React package, a hosted API, or a published shadcn registry. The CLI installs this site’s versioned source archive directly. Agent and connected-service examples continue to use local demonstration data.'))}
 };
 return pages[id];
}
