export const groups = {
 'Action':['cursor','Give people a clear next step.'], 'Form controls':['sliders','Collect a little information, thoughtfully.'],
 'Feedback & status':['bell','Make progress and outcomes easy to understand.'], 'Navigation':['layout','Keep people oriented, wherever they go.'],
 'Data display':['chart','Give numbers a clear, quiet shape.'], 'Content':['type','Put the useful details in the right place.'],
 'Container':['layers','Bring related information together.'], 'Overlay':['copy','A little more context, close by.'],
 'Table & list':['list','Make information easy to scan and act on.'], 'Chat':['chat','A place for conversation.'],
 'Layout':['layout','Connect small components into whole products.'], 'Agents':['bot','Keep automated work understandable and in your control.']
};
export const guideLinks=[['getting-started','Getting started','arrow'],['installation','Installation','terminal'],['theming','Theming','palette'],['motion','Motion & accessibility','chart'],['composition','Composition','layers'],['api','Runtime API','code'],['migration','What’s new in 0.2','circlecheck']];
const state = (id,label,description,code='')=>({id,label,description,code});
const defaultState=state('default','Default','An interactive example. Use the controls to explore its behavior.');
const disabled=state('disabled','Disabled','Unavailable controls retain their shape and cannot be activated.',`root.querySelectorAll('button, input, textarea, select').forEach(control => { control.disabled = true; });\nroot.querySelectorAll('summary, a').forEach(control => { control.inert = true; });`);
const clickState=(id,label,selector,description)=>state(id,label,description,`root.querySelector(${JSON.stringify(selector)})?.click();`);
const special={
 'button':[defaultState,state('primary','Primary','Use the filled treatment for the main action.',`root.querySelectorAll('.button').forEach(button => { button.hidden = !button.classList.contains('primary'); });`),state('danger','Destructive','Use explicit action text for a destructive operation.',`root.querySelectorAll('.button').forEach(button => { button.hidden = !button.classList.contains('danger'); });`),disabled],
 'agent-todo-list':[defaultState,clickState('running','Running','[data-agent-action="todo-run"]','Tasks advance in sequence. Stop pauses the demonstration.'),state('complete','Completed','Every task is finished and the plan can be replayed.',`root.querySelectorAll('.agent-tasks li').forEach(row => { row.className = 'is-complete'; row.querySelector('small').textContent = 'Completed'; row.querySelector('.task-percent').textContent = '100%'; row.querySelector('.task-mark').innerHTML = window.OrbitIcon('circlecheck'); });\nroot.querySelector('[data-todo-count]').textContent = '4 of 4 completed';\nroot.querySelector('[data-run-status]').textContent = 'All tasks completed';\nroot.querySelector('[data-agent-action="todo-run"]').textContent = 'Replay';`)],
 'approval-card':[defaultState,clickState('approved','Approved','[data-agent-action="approve"]','The decision replaces the actions with a confirmation and reset.'),clickState('declined','Declined','[data-agent-action="reject"]','A declined action remains clearly distinguishable from approval.')],
 'tool-approval':[defaultState,clickState('approved','Approved','[data-agent-action="approve"]','Permission is confirmed locally. No tool or service is called.'),clickState('declined','Declined','[data-agent-action="reject"]','The request is declined; nothing is executed.')],
 'streaming-response':[defaultState,clickState('streaming','Streaming','[data-agent-action="stream-start"]','Content appears progressively and can be stopped. Reduced motion reveals it immediately.')],
 'rolling-number':[defaultState,state('large','Larger value','The same digit masks handle changing value length.',`const number = root.querySelector('[data-number]');\nnumber.dataset.number = '12847';\nwindow.OrbitNumbers.set(number, 12847);`),state('zero','Zero','Zero is an explicit value, never an empty state.',`const number = root.querySelector('[data-number]');\nnumber.dataset.number = '0';\nwindow.OrbitNumbers.set(number, 0);`)],
 'badge-and-status':[defaultState,state('positive','Positive','Positive statuses use a label as well as color.',`root.querySelectorAll('.badge').forEach(badge => { badge.hidden = !badge.classList.contains('green'); });`),state('critical','Critical','Use critical status sparingly, for something that needs attention.',`root.querySelectorAll('.badge').forEach(badge => { badge.hidden = !badge.classList.contains('red'); });`)],
 'banner':[defaultState,state('success','Success','A persistent confirmation sits near the affected content.',`root.querySelector('.banner.info').hidden = true;`),state('information','Information','Supporting context stays separate from an error.',`root.querySelector('.banner:not(.info)').hidden = true;`)],
 'avatar-and-group':[defaultState,state('individual','Individual','Use the size that matches the surrounding content.',`root.children[1].hidden = true;`),state('group','Group','Overlapping avatars show a small group with a visible overflow count.',`root.children[0].hidden = true;`)],
 'table':[defaultState,state('empty','Empty','Keep the column headings while explaining why there are no rows.',`root.querySelector('tbody').innerHTML = '<tr><td colspan="3">No traffic recorded yet.</td></tr>';`)],
 'visitor-table':[defaultState,state('empty','Empty','Keep the table structure when the first visitor has yet to arrive.',`root.querySelector('tbody').innerHTML = '<tr><td colspan="4">No visitors yet.</td></tr>';`)],
 'activity-list':[defaultState,state('single','Single event','The timeline accommodates one event without changing its rhythm.',`root.querySelectorAll('.activity-item').forEach((row, index) => { row.hidden = index > 0; });`)],
 'text-input':[defaultState,state('valid','Valid','Valid input clears both the visual and semantic error.',`const input = root.querySelector('.invalid');\ninput.value = 'orbit-studio';\ninput.classList.remove('invalid');\ninput.removeAttribute('aria-invalid');\nroot.querySelector('.error').hidden = true;`),disabled],
 'data-table':[defaultState,state('empty','No results','Search preserves the table tools and offers a recoverable empty result.',`const search = root.querySelector('input[type="search"]');\nsearch.value = 'No matching project';\nsearch.dispatchEvent(new Event('input', { bubbles: true }));`)],
 'attribution-table':[defaultState,clickState('revenue','Revenue','[data-table-metric]','Revenue replaces people while the row labels remain stable.'),clickState('paused','Paused','[data-table-play]','Pause holds the live values in place.')],
 'inline-validation':[defaultState,clickState('invalid','Invalid','button[type="submit"]','Associated errors explain what is missing.'),state('valid','Valid','Successful validation confirms the corrected input.',`root.querySelector('input').value = 'alex@studio.example';\nroot.querySelector('button[type="submit"]').click();`)],
 'slider':[defaultState,state('minimum','Minimum','The thumb stops at the lower bound.',`const input = root.querySelector('input');\ninput.value = input.min;\ninput.dispatchEvent(new Event('input', { bubbles: true }));`),state('maximum','Maximum','The filled track reaches the upper bound.',`const input = root.querySelector('input');\ninput.value = input.max;\ninput.dispatchEvent(new Event('input', { bubbles: true }));`),disabled],
 'range-slider':[defaultState,state('wide','Wide range','Lower and upper values remain bounded.',`const inputs = [...root.querySelectorAll('input[type="range"]')];\ninputs[0].value = inputs[0].min; inputs[1].value = inputs[1].max;\ninputs.forEach(input => input.dispatchEvent(new Event('input', { bubbles: true })));`),disabled],
 'skeleton-and-spinner':[defaultState,state('skeleton','Skeleton','Reserve the shape of the content before it arrives.',`root.querySelector('[role="status"]')?.remove();`)],
 'progress-and-score':[defaultState,state('complete','Complete','Completion updates the text and the fill together.',`root.querySelector('.ring strong').textContent = '100';\nroot.querySelector('.ring').setAttribute('aria-label', 'Experience score: 100 out of 100');\nroot.querySelector('.performance-copy h3').textContent = 'Perfect';\nconst progress = root.querySelector('.progress');\nif (progress) { progress.setAttribute('aria-valuenow', '100'); progress.firstElementChild.style.width = '100%'; }`)],
 'tabs':[defaultState,clickState('activity','Activity','[data-tab="Activity"]','The selected tab and its content change together.'),clickState('settings','Settings','[data-tab="Settings"]','Each tab retains its own accessible panel association.')],
 'floating-navigation':[defaultState,clickState('people','People','[aria-label="People"]','The selected destination moves smoothly within the dark dock.'),clickState('realtime','Realtime','[aria-label="Realtime"]','The active destination is exposed through its pressed state.')],
 'expandable-dock':[defaultState,clickState('expanded','Expanded','[aria-label="Realtime"]','A contextual summary expands above the navigation.')],
 'wallet-card':[defaultState,clickState('concealed','Concealed','[data-extra="wallet-hide"]','Conceal the sample balance without changing its value.')]
};
export function statesFor(component) {
 if(special[component.slug]) return special[component.slug];
 const dom=new DOMParser().parseFromString(component.html,'text/html');
 if(dom.querySelector('details'))return[defaultState,state('collapsed','Collapsed','Supporting details are hidden until requested.',`root.querySelectorAll('details').forEach(details => { details.open = false; });`),state('expanded','Expanded','Supporting details remain within the same context.',`root.querySelectorAll('details').forEach(details => { details.open = true; });`)];
 if(dom.querySelector('input[type="checkbox"], input[type="radio"]'))return[defaultState,state('unselected','Unselected','Choices remain available without an initial selection.',`root.querySelectorAll('input[type="checkbox"], input[type="radio"]').forEach(input => { input.checked = false; input.dispatchEvent(new Event('change', { bubbles: true })); });`),disabled];
 if(dom.querySelector('input[type="range"],input[type="number"]'))return[defaultState,disabled];
 if(dom.querySelector('input:not([type="file"]):not([hidden]),textarea'))return[defaultState,disabled];
 if(dom.querySelector('button'))return[defaultState,disabled];
 return[defaultState,state('compact','Compact','The same content in a narrower region, using the shared spacing scale.',`root.style.maxWidth = '290px';\nroot.style.gap = 'var(--space-3)';`)];
}
export function sourceFor(slug){
 const starter=['app-shell','page-header-and-breadcrumbs','side-drawer','bottom-sheet','popover','confirmation-dialog','searchable-select','autocomplete','multiselect','command-palette','number-stepper','password-field','date-range-picker','time-picker','selectable-cards','data-table','inline-validation','error-and-retry','upload-progress','unsaved-changes','metadata-list','thumbnail-and-lightbox','divider-and-form-section'];
 const extras=['range-slider','tilt-card','marquee','pull-to-refresh','ambient-background','rotating-carousel','card-and-project-folder','masonry-grid','fixtures','asset-swap','status-island','overflow-actions','wallet-card','prediction-card','bloom-menu','morphing-search','action-swap','agent-questions'];
 const agents=['agent-todo-list','agent-message','message-bubbles','message-scroller','prompt-input','code-block','approval-card','file-diff','tool-result','streaming-response','image-generation','tool-approval','citations','agent-activity','agent-loading-states','ai-sidebar','chat-workspace','file-tree','preview-rail','otp-input','feedback-widget','notification-stack','context-menu','availability-scheduler','wheel-picker','swipeable-list','not-found'];
 if(['slider','select-and-date'].includes(slug))return'controls.js';
 if(['rolling-number','attribution-table','visitor-table'].includes(slug))return'numbers.js';
 return starter.includes(slug)?'starter.js':extras.includes(slug)?'extras.js':agents.includes(slug)?'agents.js':'app.js';
}
export function contractFor(c){
 const doc=new DOMParser().parseFromString(c.html,'text/html'),rows=[];
 const input=doc.querySelector('input:not([hidden]),textarea');
 if(input){for(const [name,type,desc]of [['value','string','Initial value of the first field. Read the current value from the input element.'],['min','number','Smallest accepted numeric value.'],['max','number','Largest accepted numeric value.'],['step','number','Increment used by keyboard and pointer changes.'],['maxlength','number','Maximum text length accepted by the field.'],['checked','boolean','Initial selection. Read or change the input.checked property.']])if(input.hasAttribute(name))rows.push([name,type,input.getAttribute(name)||'true',desc]);}
 if(doc.querySelector('button,input,textarea'))rows.push(['disabled','boolean','false','Set on individual controls to prevent interaction. Native disabled controls keep a consistent visual treatment.']);
 if(doc.querySelector('details'))rows.push(['open','boolean',String(doc.querySelector('details').open),'Set on a details element to reveal its content. Native summary interaction also updates it.']);
 if(doc.querySelector('[aria-pressed]'))rows.push(['aria-pressed','boolean',doc.querySelector('[aria-pressed]').getAttribute('aria-pressed'),'Selected state of a toggle. Use its button click behavior to keep the visual state synchronized.']);
 if(doc.querySelector('[data-number]'))rows.push(['data-number','number',doc.querySelector('[data-number]').getAttribute('data-number'),'Numeric target. Use OrbitNumbers.set(element, value) for an animated update.']);
 if(doc.querySelector('[data-options]'))rows.push(['data-options','JSON string','see source','Options used by the searchable selector. Set before enhancement.']);
 if(doc.querySelector('[data-start]'))rows.push(['data-start / data-end','YYYY-MM-DD','2026-09-04 / 2026-09-10','Committed date range stored on the trigger. The Apply action updates both values.']);
 if(doc.querySelector('[data-time]'))rows.push(['data-time','HH:mm','09:30','Committed 24-hour time stored on the trigger.']);
 if(!rows.length)rows.push(['class','string','see source','Keep structural classes from the source. Use shared CSS variables to change surface, text, and spacing.']);
 return rows;
}
export const commonAPI=[['target','string | Element','required','Selector or container element to receive this component.'],['configure','(root: Element) => void','undefined','Customize the real DOM after enhancement. Runs again when reset() is called.'],['onInput','(event, root) => void','undefined','Receive native input events for continuous edits.'],['onChange','(event, root) => void','undefined','Receive native change events when a field commits a value.'],['onAction','(event, root) => void','undefined','Receive clicks after the component’s local handler. Use event.target.closest() to identify an action.']];
