export function guideContent(id,{code,command,apiTable,commonAPI}) {
 const section=(name,body)=>`<section class="docs-section"><h2>${name}</h2>${body}</section>`;
 const p=text=>`<p class="docs-prose">${text}</p>`;
 const snippets={
  usage:`<div id="action"></div>\n\n<script type="module">\n  import { mount } from './components/syntari/button.js';\n\n  const button = await mount('#action', {\n    configure(root) {\n      root.querySelector('.primary').textContent = 'Save changes';\n    },\n    onAction(event, root) {\n      if (event.target.closest('.primary')) {\n        // Connect your application's save action here.\n      }\n    }\n  });\n</script>`,
  theme:`/* Shared tokens work in both themes. */\n:root {\n  --accent: #2f6fed;\n  --accent-soft: #2f6fed14;\n  --accent-text: #1b56c8;\n  --radius-card: 18px;\n}\n\n[data-theme="dark"] {\n  --accent: #6f9dff;\n  --accent-text: #a8c8ff;\n}\n\n/* In your application: */\n/* document.documentElement.dataset.theme = 'dark'; */`,
  manual:`<div id="example" class="specimen-body">\n  <!-- Paste the component's HTML from its Code tab here. -->\n</div>\n\n<script type="module">\n  import { prepare } from './syntari/runtime/syntari.js';\n  await prepare(document.querySelector('#example'));\n</script>`
 };
 const pages={
 'getting-started':{title:'A little less setup.',description:'A practical starting point for building with Syntari. Use the components, keep the source, and make the details yours.',body:
 p('Start by describing a screen on the renderer homepage. The registry then gives an agent component and pattern entries, tokens, contracts, and editable HTML and JavaScript source. The browser runtime supplies the working interactions.')+
 section('1. Add your first component',p('Run the source installer from your project directory. It copies the selected component and the shared Syntari runtime into your project. Node.js 22 or later is required.')+code(command('button'),'Terminal','shell'))+
 section('2. Make it part of your page',p('Mount an example into a container, then customize its DOM and connect your own actions. The styles, fonts, and interaction handlers load from the local runtime folder.')+code(snippets.usage,'index.html','html'))+
 section('3. Explore the states',p('Every page includes an interactive preview and additional states or layouts. Use the Preview, Usage, and Code tabs to move between the result and its implementation. State selections update the Usage example too.'))+
 section('4. Connect your product',p('Gallery records, uploads, generation, approvals, sign-in, and messages demonstrate local UI behavior. Replace their sample data and service actions before using them in a connected product. The source is intentionally included for this work.'))},
 'installation':{title:'Your source. Your project.',description:'Use the CLI for a quick start, or bring the files in manually. Both paths install the same versioned source.',body:
 section('CLI installation',p('Use the versioned npm package to query the registry and copy editable source. Each component page gives you the command for its own slug. The site also hosts the same versioned archive under <code>/downloads/</code> if npm is unavailable.')+code(command('button slider'),'Terminal','shell')+p('The default destination is <code>./components/syntari</code>. Add <code>--dir ./ui/syntari</code> to choose another folder. Run <code>npm exec --yes --package=syntari-ui@0.2.2 -- syntari list --json</code> to inspect every slug before installing.'))+
 section('Manual installation',p('Download the source archive from any component page. Extract it and copy <code>package/kit/runtime</code> to <code>syntari/runtime</code> in your project. Copy the component module and HTML from <code>package/kit/components</code> to <code>syntari/</code>. Keep the module next to the runtime directory.')+code(snippets.manual,'index.html','html')+p('For the module approach, use <code>mount</code> from the component’s JavaScript file instead. For the manual approach above, edit the copied HTML and call <code>prepare</code> once after insertion.'))+
 section('What gets installed',code('components/syntari/\n├── button.js       # component entry\n├── button.html     # editable template\n├── syntari.json      # installed version\n└── runtime/\n    ├── syntari.js    # mounting and enhancement\n    ├── tokens.css  # light and dark tokens\n    ├── styles.css  # base styling\n    ├── …           # shared interactions and patterns\n    └── assets/     # fonts and licenses','Files','text')+p('Version 0.2.2 uses a shared runtime for all patterns. Installation copies it once; adding another component reuses it. It is not a tree-shaken, per-component bundle.'))+
 section('Serving and upgrades',p('Use a development server or static host. ES modules and template requests require HTTP; opening an HTML file with a file:// URL is not supported. The CLI preserves existing files and refuses to overwrite a customized component. Install a later version into a new directory and review changes before migrating.'))},
 'theming':{title:'One shared language.',description:'Light and dark are two expressions of the same system. Start with the semantic tokens, then refine the details.',body:
 section('Choose a theme',code(`import { setTheme } from './components/syntari/runtime/syntari.js';\n\nsetTheme('dark'); // or 'light'\n\n// Persist the preference in your application if needed.\nlocalStorage.setItem('my-app-theme', 'dark');`,'theme.js','js')+p('The runtime changes the root <code>data-theme</code> attribute. It does not persist an application’s theme preference for you.'))+
 section('Use semantic colors',p('Use <code>--canvas</code> for the page, <code>--surface</code> for a raised region, <code>--subtle</code> for a quiet fill, and <code>--border</code> for separators. Use <code>--text</code>, <code>--muted</code>, and <code>--accent-text</code> for readable text.')+code(snippets.theme,'theme.css','css'))+
 section('Shape and spacing',p('Pill actions use <code>--radius-control</code>; cards use <code>--radius-card</code>. The spacing scale is 4, 8, 12, 16, 24, 32, and 48 pixels. Prefer the named spacing tokens when adding a composition.'))+
 section('Typography and icons',p('OpenRunde gives Syntari its soft, readable shape. The local font assets and their licenses are included in the source. Interface icons are Lucide SVGs, with shared stroke weight and sizing. Preserve accessible names on icon-only actions.'))},
 'motion':{title:'Movement, in moderation.',description:'Small transitions should explain a change, preserve context, and settle quickly.',body:
 section('A shared rhythm',apiTable([['--motion-fast','duration','140ms','Hover and press feedback.'],['--motion-medium','duration','240ms','Selection, disclosures, and state changes.'],['--motion-panel','duration','320ms','Panels and navigation.'],['--motion-data','duration','650ms','Number and chart entrances.']]))+
 section('Reduced motion',p('Syntari follows <code>prefers-reduced-motion: reduce</code>. Decorative travel is removed, numeric changes settle immediately, and streaming text appears without a character-by-character reveal. Progress remains understandable through text and status updates.')+code(`@media (prefers-reduced-motion: reduce) {\n  .my-component {\n    transition: none;\n    animation: none;\n  }\n}`,'motion.css','css'))+
 section('Keyboard and focus',p('Use native buttons and fields. Preserve the provided labels, role attributes, and expanded or selected states. Dropdowns and calendars handle keyboard navigation; modal dialogs contain focus and return it to the opener. A visible focus ring should remain easy to see in both themes.'))+
 section('Testing a composition',p('Try the full flow with Tab, Enter, Escape, and arrow keys. Repeat it at a narrow width, with long text, and with reduced motion enabled. Loading and error states should remain legible without animation or color alone.'))},
 'generative-ui':{title:'Agents can render, too.',description:'An agent describes a screen as data. Syntari decides what is allowed, then draws it with the same components a person would use.',body:
 section("The spec",p("A screen spec is JSON. It names components from the published registry, passes props, chooses one of four layouts, and can group parts behind a labelled region. It contains no markup, no code, and no framework. The <a href='generative-ui.html'>demo</a> shows a read-only report and an interactive analytics screen.")+code("{\n  \"version\": \"syntari-ir-1\",\n  \"type\": \"screen\",\n  \"layout\": \"stack\",\n  \"title\": \"Release check\",\n  \"children\": [\n    {\n      \"component\": \"syntari.banner\",\n      \"props\": {\n        \"message\": \"Build 4281 passed\",\n        \"detail\": \"128 tests in 42s.\",\n        \"tone\": \"success\"\n      }\n    },\n    {\n      \"component\": \"syntari.tool-approval\",\n      \"props\": {\n        \"title\": \"Run the migration?\",\n        \"question\": \"Apply three schema changes to the billing database in production.\",\n        \"scope\": \"billing-production · write access\"\n      },\n      \"provenance\": {\n        \"component\": \"planner\",\n        \"reason\": \"schema change needs human consent\"\n      }\n    }\n  ]\n}","request.json","json")+p("A <code>provenance</code> block may travel with any node. The renderer writes it to the element it produced, so a reviewer can ask why a region exists without reading agent logs."))+
 section("Lead with the decision",p("A screen is a sentence, not a dashboard. Put the decision first, the facts a person needs to decide next to it, and keep the evidence in a region that opens on request.")+code("{\n  \"type\": \"region\",\n  \"label\": \"Evidence · 4 checks\",\n  \"open\": false,\n  \"children\": [\n    {\n      \"component\": \"syntari.activity-list\",\n      \"props\": {\n        \"items\": [\n          { \"title\": \"Tests passed\", \"detail\": \"128 tests in 42s.\", \"time\": \"2m ago\" }\n        ]\n      }\n    }\n  ]\n}","evidence.json","json")+p("A region is a disclosure rather than a component: it renders as a native details element, so keyboard and screen-reader behaviour come from the browser. Regions nest. Components do not take children yet, so wrap a group in a region instead of nesting it inside a component."))+
 section("Render it",p("Import the module that ships next to the runtime, validate, then render. The renderer mounts the same components the library ships, so props land in real markup with real interactions and keyboard behavior.")+code("import { validate, render } from './syntari/runtime/ir.js';\n\nconst spec = await response.json();        // the model returned IR\nconst { ok, diagnostics } = await validate(spec);\n\nif (!ok) {\n  // Hand the diagnostics back to the model, or refuse the turn.\n  throw new Error(`Screen IR failed validation: ${JSON.stringify(diagnostics)}`);\n}\n\nconst screen = await render(spec, '#screen');\nscreen.diagnostics;                        // errors and repairs\nscreen.destroy();                          // removes mounts and listeners","agent-surface.js","js")+p("Validation belongs at the boundary, next to your tool call, not inside a component. Syntari decides what a component accepts; your application decides whether the agent may act at all."))+
 section("What can be rendered",p("The renderer reads the published registry. A component becomes renderable when its manifest declares both <code>props</code> and <code>ir</code>. Open the <a href='generative-ui.html'>live renderer</a> for the current component list, then inspect its manifest through <code>syntari info &lt;id&gt; --json</code>. Unsupported components become labelled fallbacks."))+
 section("Layouts",p("Layout is a closed set of four. A host may add its own, but these render without configuration.")+apiTable([["stack","layout","default","One column. Children render in source order."],["row","layout","—","Children sit side by side and wrap when space runs out."],["grid","layout","—","Responsive columns of at least 220px for cards and metrics."],["two-column","layout","—","Two even columns above 760px, one column below."]]))+
 section("Validation",p("Errors stop a node. Warnings repair one. That difference is the safety story: a model cannot invent a component, a prop, or a value and still get pixels.")+apiTable([["unknown-component","error","labelled fallback","The id is not in the registry."],["unsupported-component","error","labelled fallback","Documented, but without a prop contract."],["missing-required","error","labelled fallback","A required prop was absent."],["wrong-type","error","labelled fallback","A value arrived as the wrong kind of data."],["enum-outside-values","error","labelled fallback","A value outside the declared set, such as an unknown tone."],["over-length","error","labelled fallback","Text longer than the prop allows."],["unknown-prop","warning","prop ignored","The component has no such prop."],["unknown-layout","warning","renders as stack","The layout is not one of the four."],["nested-children-unsupported","warning","rendered as siblings","Children of a component are flattened; wrap them in a region."],["unknown-icon","warning","component default kept","The icon name is not a Lucide icon in this runtime."]])+p("Every diagnostic carries a severity, a code, a path, and a sentence written to be read by a person or a model.")+code("[\n  {\n    \"severity\": \"error\",\n    \"code\": \"unknown-component\",\n    \"path\": \"children[0].component\",\n    \"message\": \"\\\"syntari.wizard-hat\\\" is not in the Syntari registry.\"\n  }\n]","diagnostics.json","json"))+
 section("Limits",p("Budgets bound what one spec can ask for, so a runaway generation cannot paint an unbounded screen.")+apiTable([["maxNodes","limit","120","Total nodes in one spec."],["maxDepth","limit","8","Nesting levels."],["maxChildren","limit","40","Top-level nodes on one screen."],["maxListItems","limit","40","Items in any list prop."]]))+
 section("What is not supported yet",p("Chart and table cells render as text rather than decorated markup, children of a component are flattened, props are single values rather than expressions, and the renderer outputs DOM rather than React or Figma. Those are the next milestones, not this release."))},
 'composition':{title:'Small details. Whole products.',description:'Build a page with a few well-chosen patterns and a clear hierarchy.',body:
 section('Start with a layout',p('Use App shell and Page header & breadcrumbs to establish navigation and context. Add a Data table for records or grouped fields for settings. The gallery’s four starter screens show settings, people, projects, and onboarding as connected flows.')+p('<a href="gallery.html?view=screens&screen=projects">Explore the starter screens</a>'))+
 section('Mount into separate containers',code(`<section aria-labelledby="project-title">\n  <h1 id="project-title">Projects</h1>\n  <div id="records"></div>\n</section>\n\n<script type="module">\n  import { mount } from './components/syntari/data-table.js';\n  const table = await mount('#records');\n\n  // When the enclosing page is removed:\n  // table.destroy();\n</script>`,'projects.html','html')+p('A mounted component owns the child element it inserts, not its parent container. Give each component a separate region. The runtime makes radio-group and field association IDs unique for each mount.'))+
 section('Keep services at the boundary',p('Use native field values and local action handlers as the boundary to your application. Demonstrations do not supply authentication, storage, billing, model calls, or upload services. Replace the local behavior in the copied interaction files when a real service must control loading, success, and failure.'))+
 section('Global styles',p('The 0.2 runtime includes a base reset, typography, and shared styles. Use it as the foundation of a new page. When adding Syntari to a heavily styled existing product, review selector conflicts or isolate the preview in an iframe.'))},
 'api':{title:'A small, practical API.',description:'Mount a working pattern, enhance copied HTML, and keep access to the actual DOM.',body:
 section('mount(target, options)',p('Each installed component module exports an asynchronous <code>mount</code> function with its component slug already selected. It resolves after the source and styles have loaded.')+apiTable(commonAPI)+code(`import { mount } from './components/syntari/slider.js';\n\nconst slider = await mount('#events', {\n  onInput(event) {\n    if (event.target.matches('input[type="range"]')) {\n      console.log(Number(event.target.value));\n    }\n  }\n});`,'example.js','js'))+
 section('Mounted instance',apiTable([['element','Element','—','The inserted root, including its live child controls.'],['reset()','Promise<void>','—','Recreate the initial template and run configure again.'],['destroy()','void','—','Remove the inserted root and its callback listeners.']])+p('Reset recreates the template. It does not reset shared sample records or application services. Destroy a mounted instance before discarding its owning page.'))+
 section('prepare(root)',p('Enhances a subtree of copied HTML. Call once after inserting new component markup. It adds unique field associations, initializes controls, and prepares shared motion. Event behavior is delegated through the shared runtime.'))+
 section('Other exports',apiTable([['getComponents()','Promise<Component[]>','—','Get the registered names, slugs, descriptions, markup, and token references.'],['setTheme(theme)','void','light | dark','Set the root data-theme attribute.'],['initialize()','Promise<Component[]>','—','Load shared assets once. mount and prepare call this automatically.']]))+
 section('Errors and supported environments',p('Unknown slugs and missing mount targets reject with descriptive errors. Asset loading errors also reject the mount promise. Handle these in your application’s error UI. Use a modern browser with ES modules, native dialog, Web Animations, and CSS custom properties. Popovers fall back to positioned panels when the browser does not expose the Popover API.'))},
 'migration':{title:'The details, documented.',description:'Syntari 0.2.2 brings the renderer to the homepage and keeps editable components available for projects.',body:
 section('What changed',p('Each catalog component has a dedicated, shareable page. Preview states, usage, actual source, installation, element contracts, and guidance sit together. The source installer and manual archive contain the same runtime used by these pages.'))+
 section('Workspace navigation',p('The App shell and starter screens share sidebar and topbar layouts, a collapsible rail, and a mobile drawer. Switching layouts keeps your current page and unsaved form edits. The full-screen workspace preview is available from Starter screens.'))+
 section('What stays familiar',p('Syntari keeps its quiet surfaces, lavender accents, dark navigation, OpenRunde typography, Lucide icons, and subtle transitions. The existing gallery and its four starter screens remain available.'))+
 section('From 0.1',p('Existing gallery links can use <code>gallery.html</code> with the same view and screen query parameters. New component pages use <code>components/&lt;slug&gt;/</code>. The root page is the renderer; the library remains at <code>library.html</code>. Gallery and Components share the same Syntari interface; use the view switch to move between them. Your customized 0.1 files are not overwritten by the installer.'))+
 section('Current boundary',p('Syntari publishes static registry JSON, editable interaction examples, and a shared browser runtime. The CLI copies source into your project. The renderer checks Screen IR and component props; your application still authorizes model tool calls and connected services. Examples use local demonstration data.'))}
 };
 return pages[id];
}
