/* Additional reference patterns, adapted to Syntari rather than imported styles. */
(() => {
 const e=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const b=(label,a,attrs='')=>`<button type="button" class="button small" data-extra="${a}" ${attrs}>${label}</button>`;
 const wrap=(kind,body)=>`<div class="extra-demo" data-extra-kind="${kind}">${body}</div>`;
 const status='<p class="hint" role="status" data-extra-status></p>';
 const folder=()=>wrap('folder',`<details class="project-folder"><summary>${icon('folder')}<span>Brand assets<small>3 files</small></span>${icon('down')}</summary><div>${['Identity','Guidelines','Color studies'].map(t=>b(icon('file')+t,'folder-file',`data-title="${t}"`)).join('')}</div></details>${status}`);
 const rows=[
 ['Range slider','Form controls','Two bounds / keyboard','A budget interval with independent, labeled lower and upper controls.',wrap('range',`<div class="row spread"><span>Monthly budget</span><output data-range-output>$200 – $800</output></div><label class="field">Minimum<input type="range" class="range" min="0" max="1000" step="10" value="200" style="--range-fill:20%" data-bound="min" aria-label="Minimum budget"><output class="sr-only">200</output></label><label class="field">Maximum<input type="range" class="range" min="0" max="1000" step="10" value="800" style="--range-fill:80%" data-bound="max" aria-label="Maximum budget"><output class="sr-only">800</output></label>`) ],
 ['Tilt card','Container','Pointer / reduced motion','A restrained perspective response on pointer movement, without changing the content hierarchy.',wrap('tilt',`<div class="syntari-tilt" tabindex="0"><span class="avatar blue"></span><h3>Brand exploration</h3><p>Identity concepts, color studies, and project files.</p>${b('Open project '+icon('arrow'),'tilt-open')}</div>${status}`)],
 ['Marquee','Content','Play / pause','A pausable horizontal strip. Motion stops when reduced motion is requested.',wrap('marquee',`<div class="marquee-window"><div class="marquee-track">${['Design','Build','Refine','Design','Build','Refine'].map((t,i)=>`<span ${i>2?'aria-hidden="true"':''}>${icon('circlecheck')}${t}</span>`).join('')}</div></div>${b('Play','marquee-toggle','aria-pressed="false"')}`)],
 ['Pull to refresh','Feedback & status','Gesture / button','Refresh a short feed using a downward gesture or accessible button.',wrap('refresh',`<div class="refresh-feed"><span class="empty-icon">${icon('rotate-ccw')}</span><h3>You’re up to date.</h3><p class="hint" role="status">Updated just now</p></div>${b('Refresh','refresh')}`)],
 ['Ambient background','Content','Play / pause','A lightweight CSS interpretation of the reference shader effect, using only Syntari palette tokens.',wrap('ambient',`<div class="ambient-stage"><span></span><span></span><span></span><strong>Room to think.</strong></div>${b('Animate background','ambient-toggle','aria-pressed="false"')}`)],
 ['Rotating carousel','Content','Previous / next','Three artwork cards rotate through a shared stage, with explicit controls and reduced motion.',wrap('carousel',`<div class="carousel-stage">${['Ideas','In progress','Made real'].map((t,i)=>`<div class="carousel-card" data-card="${i}" ${i?'hidden':''}><span class="avatar ${i===1?'blue':i===2?'mint':''}"></span><h3>${t}</h3><p>${['Capture ideas and references.','Review the work in progress.','Explore the finished project.'][i]}</p></div>`).join('')}</div><div class="row spread">${b(icon('chevron'),'carousel-prev','aria-label="Previous card"')}<span class="hint" data-carousel-count role="status">1 of 3</span>${b(icon('chevron'),'carousel-next','aria-label="Next card"')}</div>`)],
 ['Card & project folder','Container','Expand / select', 'A folder opens into a compact set of file actions.',folder()],
 ['Masonry grid','Layout','Load more / bounded','An uneven grid with explicit loading instead of an endless automatic fetch.',wrap('masonry',`<div class="masonry-grid">${['Explorations','Identity','Color','Type'].map((t,i)=>`<div style="--tile-height:${80+(i%3)*30}px">${icon('image')}<span>${t}</span></div>`).join('')}</div>${b('Load more','masonry-more')}${status}`)],
 ['Fixtures','Data display','Switch / inspect','A compact schedule pattern with selectable fixtures and local detail feedback.',wrap('fixtures',`<div class="fixture-list">${[['Studio A','Studio B','10:00'],['North','South','12:30'],['East','West','16:00']].map(([a,c,t])=>b(`<span>${a} <span class="muted">vs</span> ${c}</span><time>${t}</time>`,'fixture',`aria-pressed="false" data-title="${a} vs ${c} at ${t}"`)).join('')}</div>${status}`)],
 ['Asset swap','Form controls','Coin select / quote / reverse','A local illustrative crypto convert form: each field carries its own asset select, enter an amount, and review the order. No wallet, trading, or network transaction is connected.',wrap('swap',`<div class="field swap-field"><span>From</span><div class="input-shell swap-input"><input name="amount" type="number" min="0" step="0.01" inputmode="decimal" value="100" data-swap-amount aria-label="Amount to convert from"><div class="dropdown ds-select swap-coin" data-swap-side="from"><button type="button" class="control-trigger" data-select-toggle aria-label="Asset to convert from" aria-haspopup="listbox" aria-expanded="false"><span class="coin-badge coin-usdc" data-coin-mark>◈</span><span data-select-label>USDC</span>${icon('down')}</button><div class="dropdown-panel control-panel swap-coin-panel" role="listbox" aria-label="Asset to convert from" hidden>${[['USDC','coin-usdc','◈'],['DAI','coin-dai','◉'],['ETH','coin-eth','◆'],['BTC','coin-btc','₿']].map((c,i)=>`<button type="button" role="option" aria-selected="${!i}" data-option="${c[0]}"><span class="coin-badge ${c[1]}">${c[2]}</span><span>${c[0]}</span><span class="option-check">${icon('check')}</span></button>`).join('')}</div></div></div></div><button type="button" class="swap-flip" data-extra="swap-reverse" aria-label="Reverse assets">${icon('arrow-up-down')}</button><div class="field swap-field"><span>To</span><div class="input-shell swap-input"><output data-swap-output>99.58</output><div class="dropdown ds-select swap-coin" data-swap-side="to"><button type="button" class="control-trigger" data-select-toggle aria-label="Asset to convert to" aria-haspopup="listbox" aria-expanded="false"><span class="coin-badge coin-dai" data-coin-mark>◉</span><span data-select-label>DAI</span>${icon('down')}</button><div class="dropdown-panel control-panel swap-coin-panel" role="listbox" aria-label="Asset to convert to" hidden>${[['USDC','coin-usdc','◈'],['DAI','coin-dai','◉'],['ETH','coin-eth','◆'],['BTC','coin-btc','₿']].map((c,i)=>`<button type="button" role="option" aria-selected="${!i}" data-option="${c[0]}"><span class="coin-badge ${c[1]}">${c[2]}</span><span>${c[0]}</span><span class="option-check">${icon('check')}</span></button>`).join('')}</div></div></div></div><p class="hint" data-swap-note>Rate 1:1 · Network fee ~$0.42 · You’ll receive 99.58 DAI</p><button type="button" class="button primary" data-extra="swap-review">Review order</button>${status}`)],
 ['Status island','Feedback & status','Expand / collapse','A dark floating surface reveals task context without switching pages.',wrap('island',`<details class="status-island"><summary>${icon('circlecheck')}<span>Workspace synced</span>${icon('down')}</summary><p>All 3 changes are saved.</p><div class="row">${icon('file')} Brand assets <span class="muted">just now</span></div></details>`)],
 ['Overflow actions','Action','Disclosure / selection','Low-frequency actions share the standard Syntari menu surface.',wrap('overflow',`<details class="overflow-demo"><summary>${icon('more')} More actions</summary><div>${['Duplicate','Move to folder','Archive'].map(t=>b(t,'overflow-choice',`data-title="${t}"`)).join('')}</div></details>${status}`)],
 ['Wallet card','Content','Balance privacy / copy','A sample account surface with concealed balance and a copyable demonstration identifier.',wrap('wallet',`<div class="wallet-surface"><div class="row spread"><span>Demo wallet</span>${b(icon('eye'),'wallet-hide','aria-label="Hide balance" aria-pressed="false"')}</div><strong data-wallet-balance>$1,250.00</strong><span class="hint">Sample balance · no connected account</span><div class="row spread"><code>syntari-demo-0001</code>${b(icon('copy'),'wallet-copy','aria-label="Copy demo identifier"')}</div></div>`)],
 ['Prediction card','Data display','Choose / confirm','A product-planning prediction sample with local choices; no betting or payment.',wrap('prediction',`<h3>Will the next milestone ship this week?</h3><p class="hint">Team forecast · local preview</p><div class="prediction-meter"><span></span></div><div class="row spread"><span>Yes · 72%</span><span>No · 28%</span></div><div class="row">${b('Yes','predict','data-title="Yes" aria-pressed="false"')}${b('No','predict','data-title="No" aria-pressed="false"')}</div>${status}`)],
 ['Bloom menu','Action','Expand / choose','Circular actions float above a central trigger that clearly changes between Create and Close.',wrap('bloom',`<div class="bloom-anchor"><div class="bloom-options" role="group" aria-label="Create options" hidden>${b(icon('file'),'bloom-choice','aria-label="New document" data-title="Document"')}${b(icon('folder'),'bloom-choice','aria-label="New folder" data-title="Folder"')}${b(icon('chat'),'bloom-choice','aria-label="New conversation" data-title="Conversation"')}</div>${b(icon('plus')+'<span>Create</span>','bloom-toggle','aria-expanded="false"')}</div>${status}`)],
 ['Morphing search','Navigation','Expand / search / clear','An inline search expands in place and filters a small set of recent projects.',wrap('search',`${b(icon('search')+' Find a project','search-expand','aria-expanded="false"')}<div class="morph-search-field" hidden><label class="field">Find a project<input type="search" data-extra-search placeholder="Search projects…"></label>${b('Close','search-close')}</div><ul class="search-projects">${['Brand refresh','Website exploration','Customer research'].map(t=>`<li>${t}</li>`).join('')}</ul>${status}`)],
 ['Action swap','Action','Idle / working / complete','A single action changes its label and icon as work progresses.',wrap('action',`${b(icon('download')+' Prepare export','action-swap')}${status}`)],
 ['Agent questions','Agents','Choice / text / review','A small guided approval flow combines radio options, free text, and a reviewable result.',wrap('questions',`<form data-question-form><div data-question-stage><h3>What should we focus on?</h3><fieldset><legend class="sr-only">Focus</legend>${['Design','Behavior','Accessibility'].map((t,i)=>`<label class="choice"><input type="radio" name="focus" value="${t}" ${i===0?'checked':''}>${t}</label>`).join('')}</fieldset><label class="field">Anything to preserve?<textarea name="notes" rows="2" maxlength="200" placeholder="Optional details"></textarea></label></div><p role="status" class="hint" data-question-result>Step 1 of 2</p><button type="submit" class="button small primary">Review response</button></form>`)]
];rows.forEach(r=>add(...r));
const dataFamilies=[
 ['Chart bars','Data display','Two series / legend','Grouped columns compare two series across periods, with the numbers in a summary a screen reader can read.',wrap('chartbars',`<figure class="chart-figure"><figcaption><strong>Relative return by checkpoint</strong><span class="hint">Indexed · first period = 0</span></figcaption><div class="chart-columns" role="img" aria-label="Alpha and Beta by year. 1995: 18 and 9. 2001: 24 and 14. 2007: 34 and 22. 2013: 49 and 41. 2019: 89 and 98. 2025: 113 and 176.">${[[1995,18,9],[2001,24,14],[2007,34,22],[2013,49,41],[2019,89,98],[2025,113,176]].map(([year,alpha,beta])=>`<div class="chart-column"><span class="column-value">${alpha}</span><span class="column-pair"><span class="column-fill series-a" style="--fill:${Math.round(alpha/180*100)}%"></span><span class="column-fill series-b" style="--fill:${Math.round(beta/180*100)}%"></span></span><span class="column-label">${year}</span></div>`).join('')}</div><ul class="chart-legend"><li><span class="legend-swatch series-a"></span>Alpha</li><li><span class="legend-swatch series-b"></span>Beta</li></ul></figure>`,['--accent','--fg-3','--border','--text','--muted','--motion-data'])],
 ['Chart line','Data display','Two series / points','A line chart with points and a quiet grid. Series colours come from the shared tokens rather than a palette of their own.',wrap('chartline',(()=>{const rows=[[1995,18,9],[2001,24,14],[2007,34,22],[2013,49,41],[2019,89,98],[2025,113,176]],W=360,H=150,P=22,MAX=180;const x=i=>P+i*((W-P*2)/(rows.length-1)),y=v=>H-P-(v/MAX)*(H-P*2);const line=s=>rows.map((r,i)=>`${x(i).toFixed(1)},${y(r[s]).toFixed(1)}`).join(' ');return `<figure class="chart-figure"><figcaption><strong>Relative return over time</strong><span class="hint">Indexed</span></figcaption><svg class="chart-svg" viewBox="0 0 ${W} ${H}" role="img" aria-label="Alpha and Beta indexed return from 1995 to 2025. Both rise; Beta overtakes Alpha after 2019."><g class="chart-grid">${[0,1,2,3].map(i=>`<line x1="${P}" x2="${W-P}" y1="${(P+i*((H-P*2)/3)).toFixed(1)}" y2="${(P+i*((H-P*2)/3)).toFixed(1)}"></line>`).join('')}</g><polyline class="chart-series series-a" points="${line(1)}"></polyline><polyline class="chart-series series-b" points="${line(2)}"></polyline>${rows.map((r,i)=>`<circle class="chart-dot series-a" cx="${x(i).toFixed(1)}" cy="${y(r[1]).toFixed(1)}" r="3.5"></circle><circle class="chart-dot series-b" cx="${x(i).toFixed(1)}" cy="${y(r[2]).toFixed(1)}" r="3.5"></circle>`).join('')}</svg><div class="chart-axis">${rows.map(r=>`<span>${r[0]}</span>`).join('')}</div><ul class="chart-legend"><li><span class="legend-swatch series-a"></span>Alpha</li><li><span class="legend-swatch series-b"></span>Beta</li></ul></figure>`})(),['--accent','--fg-3','--border','--text','--muted'])],
 ['Chart donut','Data display','Shares / centre total','A ring shows how one whole splits, with the total held in the centre and a legend carrying the exact numbers.',wrap('chartdonut',(()=>{const C=2*Math.PI*54,slices=[['Approved',62,'series-a'],['Waiting',23,'series-b'],['Declined',15,'series-c']];let offset=0;const arcs=slices.map(([label,value,cls])=>{const len=C*value/100,seg=`<circle class="donut-segment ${cls}" r="54" cx="70" cy="70" stroke-dasharray="${len.toFixed(1)} ${(C-len).toFixed(1)}" stroke-dashoffset="${(-offset).toFixed(1)}"></circle>`;offset+=len;return seg}).join('');return `<figure class="chart-figure"><figcaption><strong>Decisions this week</strong><span class="hint">96 reviewed</span></figcaption><div class="donut-wrap"><svg viewBox="0 0 140 140" role="img" aria-label="Decisions: 62 percent approved, 23 percent waiting, 15 percent declined."><circle class="donut-track" r="54" cx="70" cy="70"></circle><g transform="rotate(-90 70 70)">${arcs}</g></svg><span class="donut-centre"><strong>96</strong><small>decisions</small></span></div><ul class="chart-legend donut-legend">${slices.map(([label,value,cls])=>`<li><span class="legend-swatch ${cls}"></span>${label}<b>${value}%</b></li>`).join('')}</ul></figure>`})(),['--accent','--fg-3','--red-4','--surface','--text','--muted'])],
 ['Heatmap','Data display','Density / scale','A compact grid where one intensity ramp carries the comparison, with the scale beside it.',wrap('heatmap',(()=>{const days=['Mon','Tue','Wed','Thu','Fri','Sat','Sun'],cells=[];for(let d=0;d<days.length;d++){for(let w=0;w<12;w++){const level=(d*3+w*5+((w*d)%7)+1)%5;cells.push(`<span class="heat-cell" data-level="${level}" title="${days[d]} · week ${w+1}"></span>`)}}return `<figure class="chart-figure"><figcaption><strong>Runs by hour and day</strong><span class="hint">Twelve weeks</span></figcaption><div class="heatmap" role="img" aria-label="Run density by weekday across twelve weeks. Weekday mornings are busiest; weekends stay quiet."><div class="heat-days">${days.map(d=>`<span>${d.slice(0,1)}</span>`).join('')}</div><div class="heat-grid">${cells.join('')}</div></div><div class="heat-scale"><span class="hint">Less</span>${[0,1,2,3,4].map(l=>`<span class="heat-cell" data-level="${l}"></span>`).join('')}<span class="hint">More</span></div></figure>`})(),['--blue-a1','--blue-a2','--blue-a3','--accent','--bg-3','--text'])],
 ['Treemap','Data display','Weighted areas','Tiles sized by share, so the shape of the whole is readable before any number is.',wrap('treemap',`<figure class="chart-figure"><figcaption><strong>Render volume by surface</strong><span class="hint">12,480 renders</span></figcaption><div class="treemap" role="img" aria-label="Share of renders: chat apps 34 percent, dashboards 24, agent tools 18, reports 14, digests 7, other 3.">${[['Chat apps',34,'span 3;grid-row:span 2'],['Dashboards',24,'span 3'],['Agent tools',18,'span 3'],['Reports',14,'span 2'],['Digests',7,'span 2'],['Other',3,'span 2']].map(([label,share,style])=>`<div class="tree-tile" style="grid-column:${style}"><strong>${label}</strong><span>${share}%</span></div>`).join('')}</div></figure>`,['--surface','--bg-2','--border','--text','--muted'])],
 ['Network graph','Data display','Nodes / edges','Relationships drawn as nodes and edges, with the busiest node carrying the emphasis.',wrap('networkgraph',`<figure class="chart-figure"><figcaption><strong>How the workspace connects</strong><span class="hint">Six services</span></figcaption><svg class="chart-svg graph-svg" viewBox="0 0 360 200" role="img" aria-label="Six services connected around the gateway: gateway to planner, tools, memory, and review; review to tools and store."><g class="graph-edges"><line x1="70" y1="70" x2="160" y2="46"></line><line x1="70" y1="70" x2="132" y2="132"></line><line x1="160" y1="46" x2="132" y2="132"></line><line x1="160" y1="46" x2="252" y2="80"></line><line x1="252" y1="80" x2="308" y2="146"></line><line x1="132" y1="132" x2="210" y2="164"></line><line x1="252" y1="80" x2="210" y2="164"></line></g><g class="graph-nodes">${[['Gateway',70,70,'hub'],['Planner',160,46,''],['Tools',132,132,''],['Memory',252,80,''],['Review',308,146,''],['Store',210,164,'']].map(([label,cx,cy,cls])=>`<g class="graph-node ${cls}"><circle cx="${cx}" cy="${cy}" r="${cls?'22':'18'}"></circle><text x="${cx}" y="${Number(cy)+4}">${label}</text></g>`).join('')}</g></svg><ul class="chart-legend"><li><span class="legend-swatch series-a"></span>Gateway</li><li><span class="legend-swatch series-b"></span>Service</li></ul></figure>`,['--accent','--surface','--border','--text','--muted'])],
 ['Gantt chart','Data display','Schedule / today','Rows of work with a span and a marker for today, at a grain people can read at a glance.',wrap('gantt',`<figure class="chart-figure"><figcaption><strong>Release plan</strong><span class="hint">Six weeks</span></figcaption><div class="gantt"><div class="gantt-head">${['W1','W2','W3','W4','W5','W6'].map(w=>`<span>${w}</span>`).join('')}</div>${[['Schema audit',0,22,'done'],['Migration dry run',18,30,'done'],['Snapshot and backfill',42,26,'now'],['Verification',62,24,''],['Rollout',78,20,'']].map(([label,start,span,state])=>`<div class="gantt-row"><span class="gantt-label">${label}</span><span class="gantt-track"><span class="gantt-bar ${state}" style="--start:${start}%;--span:${span}%"></span></span></div>`).join('')}<span class="gantt-today" style="--at:56%" aria-hidden="true"></span></div><p class="hint">Today sits in the third week.</p></figure>`,['--accent','--bg-3','--border','--text','--muted','--success-text'])],
 ['Comparison table','Table & list','Metric / advantage','The same metric measured across options, with the advantage column naming the winner in words rather than colour alone.',wrap('comparison',`<div class="table-scroll" tabindex="0" role="region" aria-label="Comparisons at the same grain"><table class="comparison-table"><caption class="sr-only">Two options measured on the same metrics</caption><thead><tr><th scope="col">Metric</th><th scope="col">Alpha</th><th scope="col">Beta</th><th scope="col">Advantage</th></tr></thead><tbody>${[['Cumulative return','≈ 2.3M%','≈ 5.7M%','Beta'],['Largest drawdown','−58%','−44%','Beta'],['Recovery after a shock','11–28 months','5–14 months','Beta'],['Split factor','20 for 1','7 for 1','Alpha'],['Current narrative','Platform breadth','Installed base','Tie']].map(([metric,alpha,beta,winner])=>`<tr><th scope="row">${metric}</th><td>${alpha}</td><td>${beta}</td><td><span class="badge ${winner==='Tie'?'':'accent'}">${winner}</span></td></tr>`).join('')}</tbody></table></div>`,['--surface','--bg-2','--border','--text','--muted','--accent-soft'])],
 ['Stat row','Data display','Four measures','A row of measures with a label, a value, a change, and the note that explains it.',wrap('statrow',`<div class="stat-row">${[['Runs','1,284','+18.6%','green','since last week'],['Approvals','96','−4.1%','amber','fewer waiting'],['p95 latency','820ms','+40ms','red','this week'],['Tokens saved','1.9M','+12%','green','versus prompts']].map(([label,value,badge,tone,note])=>`<div class="stat-card"><span class="stat-label">${label}</span><strong>${value}</strong><span class="badge ${tone}">${badge}</span><small>${note}</small></div>`).join('')}</div>`,['--surface','--border','--text','--muted','--green-a1','--amber-a1','--red-a1'])],
 ['Process ledger','Data display','Stages / durations','A pipeline shown as stages with their durations and a total, so the cost of each step is visible.',wrap('ledger',`<div class="ledger"><ol class="process-ledger"><li class="done"><span class="stage-mark">${icon('check')}</span><span class="stage-body"><strong>Resolve the request</strong><small>Match the intent against the catalog</small></span><span class="stage-time">0.3ms</span></li><li class="done"><span class="stage-mark">${icon('check')}</span><span class="stage-body"><strong>Choose the layout</strong><small>Two columns, no nested regions</small></span><span class="stage-time">0.1ms</span></li><li class="done"><span class="stage-mark">${icon('check')}</span><span class="stage-body"><strong>Render the parts</strong><small>Six components, seven props</small></span><span class="stage-time">2.1ms</span></li><li class="current"><span class="stage-mark">${icon('clock')}</span><span class="stage-body"><strong>Scope the styles</strong><small>Runs now</small></span><span class="stage-time">—</span></li></ol><p class="ledger-total">Total so far <strong>2.4ms</strong> <span class="hint">· under the 5ms budget</span></p></div>`,['--surface','--border','--text','--muted','--accent-text','--success-text'])],
 ['Transport controls','Action','Play / pause / step','Controls for something that runs: play, pause, step, and a speed that states its own value.',wrap('transport',`<div class="transport" data-transport><div class="transport-buttons"><button type="button" class="button small primary" data-transport-play aria-pressed="false">Play</button><button type="button" class="button small" data-transport-step>Step</button><button type="button" class="button small ghost" data-transport-reset>Reset</button></div><label class="transport-speed">Speed<input class="range" type="range" min="1" max="30" value="8" data-transport-speed aria-describedby="transport-speed-value"><output id="transport-speed-value" data-transport-value>8 fps</output></label><p class="hint" data-transport-status role="status">Paused at step 1 of 40</p><p class="hint">Shortcut: <kbd>space</kbd> play or pause · <kbd>s</kbd> step</p></div>`,['--accent','--surface','--border','--text','--muted'])],
 ['Live readout','Feedback & status','Running / values','A small panel of measures with a live status, for anything that changes while someone watches.',wrap('readout',`<div class="live-readout"><div class="readout-head"><span class="status-dot"></span><strong>Simulation</strong><span class="badge green">Running</span></div><dl class="readout-values"><div><dt>Generation</dt><dd data-readout-generation>27</dd></div><div><dt>Live cells</dt><dd>297</dd></div><div><dt>Speed</dt><dd>8 fps</dd></div><div><dt>Elapsed</dt><dd>1m 12s</dd></div></dl><p class="hint">Values update while the run is active.</p></div>`,['--surface','--border','--text','--muted','--green-4'])],
 ['Feature grid','Content','Four cards','A short row of capabilities: an icon, a claim, the explanation, and the footnote that qualifies it.',wrap('features',`<div class="feature-grid">${[['chat','In-line answers','Render rich components inside any conversation instead of pasting markup.','Replaces blobs of raw HTML.'],['bot','Agent frameworks','Connect through an SDK or an HTTP endpoint. Agents stay unaware of CSS.','Works with any orchestrator.'],['grid','Internal dashboards','Build data-rich screens from structured intents: charts, tables, and trackers.','No chart library required.'],['layers','Your own tokens','Drop the components into a product that already has a design system.','Tokens override everything.']].map(([ic,title,copy,note])=>`<article class="feature-card"><span class="feature-mark">${icon(ic)}</span><h3>${title}</h3><p>${copy}</p><small>${note}</small></article>`).join('')}</div>`,['--surface','--border','--text','--muted','--accent-text'])],
 ['Pricing table','Table & list','Plans / matrix','A plan matrix where included, limited, and absent stay readable without relying on colour.',wrap('pricing',`<div class="table-scroll" tabindex="0" role="region" aria-label="Plans compared line by line"><table class="pricing-table"><caption class="sr-only">Plans compared line by line</caption><thead><tr><th scope="col"><span class="hint">Plan</span></th>${[['Free','€0','For a first look'],['Standard','€24','Per month'],['Growth','€96','Per month']].map(([plan,price,note],i)=>`<th scope="col" class="${i===1?'highlight':''}"><strong>${plan}</strong><span class="plan-price">${price}</span><small>${note}</small></th>`).join('')}</tr></thead><tbody>${[['Projects','1','10','Unlimited'],['Seats','1','5','25'],['API calls','1,000 / month','50,000 / month','500,000 / month'],['Custom tokens','no','yes','yes'],['Audit log','no','yes','yes'],['Batch rendering','no','no','yes'],['Support','Community','Email','Priority'],['SLA','no','no','99.9%']].map(([row,...cells])=>`<tr><th scope="row">${row}</th>${cells.map((cell,i)=>`<td class="${i===1?'highlight':''}">${cell==='yes'?icon('check'):cell==='no'?'<span class="plan-absent">Not included</span>':cell}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`,['--surface','--bg-2','--border','--text','--muted','--accent-soft'])],
 ['CTA band','Content','Headline / one action','A closing call to action: one statement, one next step, and no competing links.',wrap('cta',`<section class="cta-band"><div><h3>Small details. Whole products.</h3><p>Bring the components into your product and keep the details consistent.</p></div><a class="button primary" href="components/button/">Get started ${icon('arrow')}</a></section>`,['--surface','--border','--text','--muted','--accent'])],
 ['Page footer','Content','Link columns / status','The end of a page: the mark, the promise, grouped links, and whether the service is up.',wrap('footer',`<div class="page-footer"><div class="footer-brand"><span class="brand-mark" aria-hidden="true"></span><strong>Syntari</strong><p>A design system that agents can use, verify, and evolve.</p></div><nav class="footer-links" aria-label="Footer"><div><h3>Product</h3><a href="library.html">Components</a><a href="gallery.html">Gallery</a><a href="guides/getting-started/">Getting started</a></div><div><h3>Reference</h3><a href="guides/generative-ui/">Generative UI</a><a href="registry/README.md">Registry</a><a href="guides/api/">Runtime API</a></div><div><h3>Project</h3><a href="https://github.com/SyntariUI/syntari">GitHub</a><a href="HISTORY.md">Changelog</a></div></nav><div class="footer-base"><span>MIT licensed · Built in the open</span><span class="footer-status"><span class="status-dot"></span> All systems operational</span></div></div>`,['--surface','--border','--text','--muted','--green-4'])]
];
dataFamilies.forEach(r=>add(...r));
const northStarFamilies=[
 ['Area chart','Data display','Line / area / axes','A line with its area filled, a labelled axis, and gridlines. The summary states the range for screen readers.',wrap('areachart',(()=>{const values=[43,41,39,40,46,48,44,41,39,42,46,48,44,41,40,45,50,52,47,44,42,48,53,57,58,55,49,45,42,48],W=360,H=160,PAD={top:18,bottom:24,left:12,right:12},MIN=30,MAX=60;const x=i=>PAD.left+i*((W-PAD.left-PAD.right)/(values.length-1)),y=v=>H-PAD.bottom-((v-MIN)/(MAX-MIN))*(H-PAD.top-PAD.bottom);const line=values.map((v,i)=>`${i?'L':'M'}${x(i).toFixed(1)},${y(v).toFixed(1)}`).join(' ');return `<figure class="chart-figure area-figure"><figcaption><strong>Mention rate</strong><span class="hint">Last 30 days</span></figcaption><div class="plot" role="img" aria-label="Mention rate over the last 30 days: it runs between 39 and 58 percent, ending near 48 percent."><div class="plot-axis" aria-hidden="true">${[60,50,40,30].map(t=>`<span>${t}%</span>`).join('')}</div><svg class="chart-svg" viewBox="0 0 ${W} ${H}" data-inset="${PAD.top} ${PAD.bottom} ${PAD.left} ${PAD.right}" data-scale="${MIN} ${MAX}" aria-hidden="true"><g class="chart-grid">${[60,50,40,30].map(t=>`<line x1="${PAD.left}" x2="${W-PAD.right}" y1="${y(t).toFixed(1)}" y2="${y(t).toFixed(1)}"></line>`).join('')}</g><path class="area-fill" d="${line} L${x(values.length-1).toFixed(1)},${H-PAD.bottom} L${x(0).toFixed(1)},${H-PAD.bottom} Z"></path><path class="chart-series series-a area-line" d="${line}"></path></svg></div><div class="plot-labels" aria-hidden="true"><span>Day 1</span><span>Day 10</span><span>Day 20</span><span>Day 30</span></div></figure>`})(),['--accent','--accent-soft','--border','--text','--muted'])],
 ['Chart toolbar','Data display','Compare / view','The controls that belong above a chart: a comparison, a view switch, and room for a legend.',wrap('charttools',`<div class="chart-toolbar" role="group" aria-label="Chart options"><label class="choice"><input type="checkbox" data-chart-compare checked> Compare with the prior period</label><button type="button" class="text-button" data-chart-view aria-pressed="false">View daily numbers</button><span class="chart-toolbar-legend"><span class="legend-swatch series-a"></span>Mention rate</span></div>`,['--text','--muted','--accent','--border'])],
 ['Metric strip','Data display','Segmented measures','A row of measures where the active one is the thing being charted. Choosing another changes the focus.',wrap('metricstrip',`<div class="metric-strip" role="group" aria-label="Measures">${[['eye','Mention rate','45.4%','3.3 pp','up','of sampled answers'],['link','Citations','1,155','5.2%','up','distinct sources'],['globe','AI referrals','54','3.8%','up','sessions from answers'],['target','Leads','2','50.0%','down','converted from AI traffic']].map(([ic,label,value,delta,dir,meaning],i)=>`<button type="button" class="metric-item ${i===0?'active':''}" data-metric aria-pressed="${i===0}"><span class="metric-label">${icon(ic)}${label}</span><span class="metric-value">${value}</span><span class="metric-delta ${dir}">${delta}</span><span class="metric-meaning">${meaning}</span></button>`).join('')}</div>`,['--surface','--bg-2','--border','--text','--muted','--success-text','--danger-text'])],
 ['Headline metric','Data display','Value / denominator','The one number a screen is about, with an optional total it is measured against.',wrap('headline',`<div class="headline-row">${[['Recommendation share','45.4%','','3.3 pp','up'],['Lost questions','12','/ 12','50.0%','down']].map(([label,value,total,delta,dir])=>`<div class="headline-metric"><span class="metric-label">${label}</span><p class="headline-value"><span class="headline-number">${value}</span> <span class="headline-total">${total}</span></p><span class="metric-delta ${dir}">${dir==='up'?'↗':'↘'} ${delta}</span></div>`).join('')}</div>`,['--text','--muted','--success-text','--danger-text'])],
 ['Filter bar','Action','Period / filters','The row that scopes a view: a period selector, a filter action, and the chips that describe the current scope.',wrap('filterbar',`<div class="filter-bar"><div class="dropdown ds-select"><button type="button" class="control-trigger" data-select-toggle aria-label="Reporting period" aria-haspopup="listbox" aria-expanded="false"><span class="icon lucide icon-calendar" aria-hidden="true"><svg viewBox="0 0 24 24"><rect width="18" height="18" x="3" y="4" rx="2"></rect><path d="M3 10h18"></path></svg></span><span data-select-label>Last 30 days</span>${icon('down')}</button><div class="dropdown-panel control-panel" role="listbox" aria-label="Periods" hidden>${['Last 7 days','Last 30 days','Last 90 days'].map((period,i)=>`<button type="button" role="option" aria-selected="${i===1}" data-option="${period}"><span>${period}</span><span class="option-check">${icon('check')}</span></button>`).join('')}</div></div><button type="button" class="icon-button" data-filter-action aria-label="Filters">${icon('sliders')}</button><button type="button" class="icon-button" data-settings-action aria-label="Chart settings">${icon('gauge')}</button></div>`,['--surface','--border','--text','--muted','--accent'])],
 ['Source list','Table & list','Ranked share','A short ranked list with share bars, for the sources or answers behind a number.',wrap('sources',`<ul class="rank-list">${[['ChatGPT',42],['Perplexity',26],['Google AI',18],['Copilot',9],['Others',5]].map(([name,share])=>`<li><span class="rank-name">${name}</span><span class="rank-track"><span class="rank-fill" style="--share:${share}%"></span></span><span class="rank-share">${share}%</span></li>`).join('')}</ul>`,['--surface','--bg-3','--accent','--text','--muted'])]
];
northStarFamilies.forEach(r=>add(...r));
 function report(root,text){const status=root.querySelector('[data-extra-status]');if(status)SyntariMotion.feedback(status,text)}
 function swapNote(root){const note=root.querySelector('[data-swap-note]'),amount=Math.max(0,Number(root.querySelector('[data-swap-amount]').value)||0),fee=0.42,received=Math.max(0,amount-fee),code=root.querySelector('.swap-coin[data-swap-side=to] [data-select-label]').textContent;root.querySelector('[data-swap-output]').textContent=received.toFixed(2);if(note)note.textContent=`Rate 1:1 · Network fee ~$${fee.toFixed(2)} · You’ll receive ${received.toFixed(2)} ${code}`}
 function animate(el){if(!matchMedia('(prefers-reduced-motion: reduce)').matches)SyntariMotion.panel(el)}
 function setBloom(root,open,restoreFocus=false){
  const options=root.querySelector('.bloom-options'),trigger=root.querySelector('[data-extra=bloom-toggle]'),choices=[...options.querySelectorAll('[data-extra=bloom-choice]')];
  trigger.setAttribute('aria-expanded',open);root.toggleAttribute('data-open',open);trigger.innerHTML=icon(open?'x':'plus')+`<span>${open?'Close':'Create'}</span>`;
  if(open){options.hidden=false;options.inert=false;choices.forEach((choice,index)=>SyntariMotion.animate(choice,[{opacity:0,transform:'translateY(12px) scale(.78)'},{opacity:1,transform:'translateY(0) scale(1)'}],240,{delay:index*38,fill:'backwards'}));}
  else if(matchMedia('(prefers-reduced-motion: reduce)').matches){options.hidden=true;options.inert=false;}
  else {options.inert=true;const animations=choices.slice().reverse().map((choice,index)=>SyntariMotion.animate(choice,[{opacity:1,transform:'translateY(0) scale(1)'},{opacity:0,transform:'translateY(8px) scale(.82)'}],150,{delay:index*24,fill:'forwards'}));Promise.all(animations.map(a=>a?.finished.catch(()=>{}))).then(()=>{if(trigger.getAttribute('aria-expanded')==='false'){options.hidden=true;options.inert=false}})}
  if(restoreFocus)trigger.focus();
 }
 document.addEventListener('click',async ev=>{const activeBloom=ev.target.closest('[data-extra-kind=bloom]');document.querySelectorAll('[data-extra-kind=bloom][data-open]').forEach(root=>{if(root!==activeBloom)setBloom(root,false)});const el=ev.target.closest('[data-extra]');if(!el)return;const root=el.closest('[data-extra-kind]'),a=el.dataset.extra;
 if(a==='folder-file'||a==='fixture'){root.querySelectorAll(`[data-extra="${a}"]`).forEach(x=>x.setAttribute('aria-pressed',x===el));report(root,el.dataset.title+' selected.');}
 if(a==='tilt-open'){report(root,'Project preview opened. Ready for your next idea.');SyntariStarter.openProject();}
 if(a==='marquee-toggle'||a==='ambient-toggle'){const active=root.classList.toggle('is-playing');el.setAttribute('aria-pressed',active);el.textContent=active?'Pause':a==='marquee-toggle'?'Play':'Animate background'}
 if(a==='refresh'||a==='action-swap'){
  el.disabled=true;el.setAttribute('aria-busy','true');root.dataset.phase='working';
  el.innerHTML='<span class="spinner" aria-hidden="true"></span><span>'+(a==='refresh'?'Refreshing…':'Preparing…')+'</span>';animate(el.lastElementChild);
  setTimeout(()=>{if(!root.isConnected)return;el.disabled=false;el.removeAttribute('aria-busy');root.dataset.phase='complete';
   el.innerHTML=icon('circlecheck')+'<span>'+(a==='refresh'?'Refresh again':'Prepare again')+'</span>';animate(el.lastElementChild);animate(el.firstElementChild);
   if(a==='refresh')SyntariMotion.feedback(root.querySelector('[role=status]'),'Updated at '+new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'}));
   else report(root,'Export ready. You can prepare it again.');
  },850);
 }
 if(a==='carousel-next'||a==='carousel-prev'){let i=(Number(root.dataset.index||0)+(a==='carousel-next'?1:2))%3;root.dataset.index=i;root.querySelectorAll('[data-card]').forEach((card,n)=>card.hidden=n!==i);root.querySelector('[data-carousel-count]').textContent=`${i+1} of 3`;SyntariMotion.animate(root.querySelector(`[data-card="${i}"]`),[{opacity:0,transform:`translateX(${a==='carousel-next'?18:-18}px)`},{opacity:1,transform:'translateX(0)'}],280)}
 if(a==='masonry-more'){const count=root.querySelectorAll('.masonry-grid>div').length;for(let i=0;i<3;i++){const tile=document.createElement('div');tile.style.setProperty('--tile-height',(80+(i%3)*30)+'px');tile.innerHTML=icon('image')+'<span>Study '+(count+i+1)+'</span>';root.querySelector('.masonry-grid').append(tile);animate(tile)}report(root,`${count+3} studies loaded`);if(count>=10){el.disabled=true;el.textContent='All studies loaded'}}
 if(a==='swap-reverse'){const read=picker=>({code:picker.querySelector('[data-select-label]').textContent,cls:picker.querySelector('[data-coin-mark]').className,mark:picker.querySelector('[data-coin-mark]').textContent});const write=(picker,value)=>{picker.querySelector('[data-select-label]').textContent=value.code;const mark=picker.querySelector('[data-coin-mark]');mark.className=value.cls;mark.textContent=value.mark;picker.querySelectorAll('[data-option]').forEach(option=>option.setAttribute('aria-selected',String(option.dataset.option===value.code)))};const from=root.querySelector('.swap-coin[data-swap-side=from]'),to=root.querySelector('.swap-coin[data-swap-side=to]'),first=read(from),second=read(to);write(from,second);write(to,first);swapNote(root);animate(root);report(root,'Assets reversed. Fixed demo rate.')}
 if(a==='swap-review'){const amount=Number(root.querySelector('[data-swap-amount]').value),from=root.querySelector('.swap-coin[data-swap-side=from] [data-select-label]').textContent,to=root.querySelector('.swap-coin[data-swap-side=to] [data-select-label]').textContent;report(root,amount>0?`Review: convert ${amount.toFixed(2)} ${from} to ${to} at the fixed 1:1 demo rate. Nothing will be sent.`:'Enter an amount greater than zero.')}
 if(a==='overflow-choice'){root.querySelector('details').open=false;report(root,el.dataset.title+' selected in preview.');root.querySelector('summary').focus()}
 if(a==='wallet-hide'){const hidden=el.getAttribute('aria-pressed')!=='true';el.setAttribute('aria-pressed',hidden);el.setAttribute('aria-label',hidden?'Show balance':'Hide balance');el.innerHTML=icon(hidden?'eye-off':'eye');SyntariMotion.feedback(root.querySelector('[data-wallet-balance]'),hidden?'••••••':'$1,250.00')}
 if(a==='wallet-copy'){try{await navigator.clipboard.writeText('syntari-demo-0001');showToast('Demo identifier copied.')}catch{showToast('Copy unavailable. Select the identifier to copy.')}}
 if(a==='predict'){root.querySelectorAll('[data-extra=predict]').forEach(x=>x.setAttribute('aria-pressed',x===el));report(root,`${el.dataset.title} selected. Your local forecast is saved.`)}
 if(a==='bloom-toggle')setBloom(root,el.getAttribute('aria-expanded')!=='true')
 if(a==='bloom-choice'){report(root,el.dataset.title+' selected.');setBloom(root,false,true)}
 if(a==='search-expand'||a==='search-close'){const open=a==='search-expand';root.querySelector('.morph-search-field').hidden=!open;root.querySelector('[data-extra=search-expand]').hidden=open;root.querySelector('[data-extra=search-expand]').setAttribute('aria-expanded',open);if(open){animate(root.querySelector('.morph-search-field'));root.querySelector('input').focus()}else{root.querySelector('[data-extra=search-expand]').focus()}}
 });
 document.addEventListener('keydown',ev=>{const root=ev.target.closest('[data-extra-kind=bloom]');if(root&&ev.key==='Escape'&&root.hasAttribute('data-open')){ev.preventDefault();setBloom(root,false,true)}});
 document.addEventListener('click',e=>{const option=e.target.closest('[data-extra-kind=swap] .swap-coin [data-option]');if(!option)return;const root=option.closest('[data-extra-kind]'),picker=option.closest('.swap-coin'),badge=option.querySelector('.coin-badge'),mark=picker.querySelector('[data-coin-mark]');if(badge&&mark){mark.className=badge.className;mark.textContent=badge.textContent}swapNote(root)});
 document.addEventListener('input',ev=>{const root=ev.target.closest('[data-extra-kind]');if(!root)return;if(ev.target.hasAttribute('data-bound')){const min=root.querySelector('[data-bound=min]'),max=root.querySelector('[data-bound=max]');if(+min.value>+max.value){if(ev.target===min)max.value=min.value;else min.value=max.value}root.querySelector('[data-range-output]').textContent=`$${min.value} – $${max.value}`;[min,max].forEach(x=>{x.closest('label').querySelector('output').textContent=x.value;x.style.setProperty('--range-fill',(+x.value/10)+'%')})}if(ev.target.hasAttribute('data-swap-amount'))swapNote(root);if(ev.target.hasAttribute('data-extra-search')){let n=0;root.querySelectorAll('li').forEach(li=>{li.hidden=!li.textContent.toLowerCase().includes(ev.target.value.toLowerCase());if(!li.hidden)n++});report(root,n?`${n} ${n===1?'project':'projects'}`:'No matching projects.');animate(root.querySelector('.search-projects'))}});
 document.addEventListener('submit',ev=>{const form=ev.target;if(!form.matches('[data-question-form]'))return;ev.preventDefault();const result=form.querySelector('[data-question-result]');if(form.dataset.review){result.textContent='Response saved in this preview.';form.querySelector('button').textContent='Start again';form.dataset.review='';form.dataset.complete='true'}else if(form.dataset.complete){form.dataset.complete='';form.querySelector('[data-question-stage]').hidden=false;result.textContent='Step 1 of 2';form.querySelector('button').textContent='Review response'}else{form.dataset.review='true';result.textContent=`Review: focus on ${form.elements.focus.value.toLowerCase()}. ${form.elements.notes.value||'No additional constraints.'}`;form.querySelector('[data-question-stage]').hidden=true;form.querySelector('button').textContent='Confirm response'}});
 document.addEventListener('pointermove',ev=>{const tilt=ev.target.closest('.syntari-tilt');if(!tilt||ev.pointerType==='touch'||matchMedia('(prefers-reduced-motion: reduce)').matches)return;const r=tilt.getBoundingClientRect();tilt.style.transform=`perspective(700px) rotateX(${(0.5-(ev.clientY-r.top)/r.height)*7}deg) rotateY(${((ev.clientX-r.left)/r.width-0.5)*7}deg)`});document.addEventListener('pointerout',ev=>{const tilt=ev.target.closest('.syntari-tilt');if(tilt&&!tilt.contains(ev.relatedTarget))tilt.style.transform=''});
 let pull=null;document.addEventListener('pointerdown',ev=>{const root=ev.target.closest('[data-extra-kind=refresh]');if(root&&!ev.target.closest('button'))pull={root,y:ev.clientY}});document.addEventListener('pointerup',ev=>{if(pull&&ev.clientY-pull.y>70)pull.root.querySelector('[data-extra=refresh]').click();pull=null});document.addEventListener('pointercancel',()=>pull=null);
 let bloomId=0;function prepare(root){root.querySelectorAll('[data-bound]').forEach(input=>input.style.setProperty('--range-fill',(+input.value/10)+'%'));root.querySelectorAll('[data-transport]').forEach(showTransport);root.querySelectorAll('[data-extra-kind=bloom]').forEach(bloom=>{const options=bloom.querySelector('.bloom-options'),trigger=bloom.querySelector('[data-extra=bloom-toggle]');if(!options.id)options.id=`syntari-bloom-options-${++bloomId}`;trigger.setAttribute('aria-controls',options.id)})}
 window.SyntariExtras={prepare};
 document.addEventListener('click',e=>{const trigger=e.target.closest('[data-extra-kind=swap] [data-select-toggle]');if(!trigger)return;const panel=trigger.nextElementSibling;requestAnimationFrame(()=>{const box=panel.getBoundingClientRect(),overflow=box.right-(innerWidth-12);if(overflow>0)panel.style.left=`${Math.max(12,parseFloat(panel.style.left)-overflow)}px`})});
 const transport=new WeakMap();
 const transportOf=root=>{if(!transport.has(root))transport.set(root,{step:1,playing:false});return transport.get(root)};
 function showTransport(root){const state=transportOf(root),button=root.querySelector('[data-transport-play]'),status=root.querySelector('[data-transport-status]'),speed=root.querySelector('[data-transport-value]'),readout=root.querySelector('[data-readout-generation]');if(button){button.setAttribute('aria-pressed',String(state.playing));button.textContent=state.playing?'Pause':'Play'}if(status)status.textContent=(state.playing?'Playing':'Paused')+' at step '+state.step+' of '+(root.dataset.transportSteps||40);if(speed)speed.textContent=root.querySelector('[data-transport-speed]').value+' fps';if(readout)readout.textContent=String(state.step*3+24)}
 function advanceTransports(){document.querySelectorAll('[data-transport]').forEach(root=>{const state=transportOf(root);if(!state.playing)return;state.step=state.step>=(Number(root.dataset.transportSteps)||40)?1:state.step+1;showTransport(root)})}
 setInterval(advanceTransports,700);
 document.addEventListener('click',event=>{const root=event.target.closest('[data-transport]');if(!root)return;const state=transportOf(root);
  if(event.target.closest('[data-transport-play]')){state.playing=!state.playing;showTransport(root);SyntariMotion.feedback(root.querySelector('[data-transport-status]'),(state.playing?'Playing':'Paused')+' at step '+state.step+' of 40');return}
  if(event.target.closest('[data-transport-step]')){state.step=state.step>=(Number(root.dataset.transportSteps)||40)?1:state.step+1;showTransport(root);return}
  if(event.target.closest('[data-transport-reset]')){state.step=1;state.playing=false;showTransport(root);return}
 });
 document.addEventListener('input',event=>{const root=event.target.closest('[data-transport]');if(!root||!event.target.matches('[data-transport-speed]'))return;showTransport(root);SyntariMotion.feedback(root.querySelector('[data-transport-status]'),'Speed '+event.target.value+' frames per second')});
 document.addEventListener('click',event=>{
  const metric=event.target.closest('[data-metric]');
  if(metric){const strip=metric.closest('.metric-strip');if(!strip)return;strip.querySelectorAll('[data-metric]').forEach(other=>{const on=other===metric;other.classList.toggle('active',on);other.setAttribute('aria-pressed',String(on))});SyntariMotion.feedback(metric.querySelector('.metric-value'),metric.querySelector('.metric-label').textContent.trim()+' selected');return}
  const view=event.target.closest('[data-chart-view]');
  if(view){const on=view.getAttribute('aria-pressed')!=='true';view.setAttribute('aria-pressed',String(on));view.textContent=on?'View weekly totals':'View daily numbers'}
 });
 renderGallery();if(window.SyntariEmbed)return;const initial=new URLSearchParams(location.search);if(initial.get('view')==='screens'){const screen=initial.get('screen')||'settings';setView('screens');SyntariStarter.showScreen(screen)}else if(initial.get('view')==='foundations')setView('foundations');else if(initial.get('category') in categoryIcons)setView('gallery',initial.get('category'));
})();
