/* Additional reference patterns, adapted to Syntari rather than imported styles. */
(() => {
 const e=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const b=(label,a,attrs='')=>`<button type="button" class="button small" data-extra="${a}" ${attrs}>${label}</button>`;
 const wrap=(kind,body)=>`<div class="extra-demo" data-extra-kind="${kind}">${body}</div>`;
 const status='<p class="hint" role="status" data-extra-status></p>';
 const folder=()=>wrap('folder',`<details class="project-folder"><summary>${icon('folder')}<span>Brand assets<small>3 files</small></span>${icon('down')}</summary><div>${['Identity','Guidelines','Color studies'].map(t=>b(icon('file')+t,'folder-file',`data-title="${t}"`)).join('')}</div></details>${status}`);
 const rows=[
 ['Range slider','Form controls','Two bounds / keyboard','A budget interval with independent, labeled lower and upper controls.',wrap('range',`<div class="row spread"><span>Monthly budget</span><output data-range-output>$200 – $800</output></div><label class="field">Minimum<input type="range" class="range" min="0" max="1000" step="10" value="200" style="--range-fill:20%" data-bound="min" aria-label="Minimum budget"><output class="sr-only">200</output></label><label class="field">Maximum<input type="range" class="range" min="0" max="1000" step="10" value="800" style="--range-fill:80%" data-bound="max" aria-label="Maximum budget"><output class="sr-only">800</output></label>`) ],
 ['Tilt card','Container','Pointer / reduced motion','A restrained perspective response on pointer movement, without changing the content hierarchy.',wrap('tilt',`<div class="syntari-tilt" tabindex="0"><span class="avatar blue"></span><h3>Brand exploration</h3><p>Identity concepts, color studies, and project files.</p>${b('Open project '+icon('arrow'),'tilt-open')}</div>${status}`)],
 ['Marquee','Content','Play / pause','A pausable horizontal strip. Motion stops when reduced motion is requested.',wrap('marquee',`<div class="marquee-window"><div class="marquee-track">${['Design','Build','Refine','Design','Build','Refine'].map((t,i)=>`<span ${i>2?'aria-hidden="true"':''}>${icon('circlecheck')}${t}</span>`).join('')}</div></div>${b('Play','marquee-toggle','aria-pressed="false"')}`)],
 ['Pull to refresh','Feedback & status','Gesture / button','Refresh a short feed using a downward gesture or accessible button.',wrap('refresh',`<div class="refresh-feed"><span class="empty-icon">${icon('rotate-ccw')}</span><h3>You’re up to date.</h3><p class="hint" role="status">Updated just now</p></div>${b('Refresh','refresh')}`)],
 ['Ambient background','Content','Play / pause','A lightweight CSS interpretation of the reference shader effect, using only Syntari palette tokens.',wrap('ambient',`<div class="ambient-stage"><span></span><span></span><span></span><strong>Room to think.</strong></div>${b('Animate background','ambient-toggle','aria-pressed="false"')}`)],
 ['Rotating carousel','Content','Previous / next','Three artwork cards rotate through a shared stage, with explicit controls and reduced motion.',wrap('carousel',`<div class="carousel-stage">${['Ideas','In progress','Made real'].map((t,i)=>`<div class="carousel-card" data-card="${i}" ${i?'hidden':''}><span class="avatar ${i===1?'blue':i===2?'mint':''}"></span><h3>${t}</h3><p>${['Capture ideas and references.','Review the work in progress.','Explore the finished project.'][i]}</p></div>`).join('')}</div><div class="row spread">${b(icon('chevron'),'carousel-prev','aria-label="Previous card"')}<span class="hint" data-carousel-count role="status">1 of 3</span>${b(icon('chevron'),'carousel-next','aria-label="Next card"')}</div>`)],
 ['Card & project folder','Container','Expand / select', 'A folder opens into a compact set of file actions.',folder()],
 ['Masonry grid','Layout','Load more / bounded','An uneven grid with explicit loading instead of an endless automatic fetch.',wrap('masonry',`<div class="masonry-grid">${['Explorations','Identity','Color','Type'].map((t,i)=>`<div style="--tile-height:${80+(i%3)*30}px">${icon('image')}<span>${t}</span></div>`).join('')}</div>${b('Load more','masonry-more')}${status}`)],
 ['Fixtures','Data display','Switch / inspect','A compact schedule pattern with selectable fixtures and local detail feedback.',wrap('fixtures',`<div class="fixture-list">${[['Studio A','Studio B','10:00'],['North','South','12:30'],['East','West','16:00']].map(([a,c,t])=>b(`<span>${a} <span class="muted">vs</span> ${c}</span><time>${t}</time>`,'fixture',`aria-pressed="false" data-title="${a} vs ${c} at ${t}"`)).join('')}</div>${status}`)],
 ['Asset swap','Form controls','Coin select / quote / reverse','A local illustrative crypto swap: pick the asset, enter an amount, and preview the quote. No wallet, trading, or network transaction is connected.',wrap('swap',`<div class="field"><span>From</span><div class="swap-input"><input name="amount" type="number" min="0" step="0.01" value="100" data-swap-amount aria-label="Amount to swap"><div class="dropdown ds-select swap-coin"><button type="button" class="control-trigger" data-select-toggle aria-label="Choose asset to swap" aria-haspopup="listbox" aria-expanded="false"><span class="coin-badge coin-usdc" data-coin-mark>◈</span><span data-select-label>USDC</span>${icon('down')}</button><div class="dropdown-panel control-panel swap-coin-panel" role="listbox" aria-label="Assets" hidden>${[['USDC','coin-usdc','◈'],['DAI','coin-dai','◉'],['ETH','coin-eth','◆'],['BTC','coin-btc','₿']].map((c,i)=>`<button type="button" role="option" aria-selected="${!i}" data-option="${c[0]}"><span class="coin-badge ${c[1]}">${c[2]}</span><span>${c[0]}</span><span class="option-check">${icon('check')}</span></button>`).join('')}</div></div></div></div>${b(icon('arrow-up-down')+' Reverse assets','swap-reverse')}<div class="swap-quote"><span data-swap-label>To · DAI</span><output data-swap-output>100.00</output></div><p class="hint" data-swap-note>Rate 1:1 · Network fee ~$0.42 · You’ll receive 99.58 DAI</p>${b('Preview swap','swap-preview')}${status}`)],
 ['Status island','Feedback & status','Expand / collapse','A dark floating surface reveals task context without switching pages.',wrap('island',`<details class="status-island"><summary>${icon('circlecheck')}<span>Workspace synced</span>${icon('down')}</summary><p>All 3 changes are saved.</p><div class="row">${icon('file')} Brand assets <span class="muted">just now</span></div></details>`)],
 ['Overflow actions','Action','Disclosure / selection','Low-frequency actions share the standard Syntari menu surface.',wrap('overflow',`<details class="overflow-demo"><summary>${icon('more')} More actions</summary><div>${['Duplicate','Move to folder','Archive'].map(t=>b(t,'overflow-choice',`data-title="${t}"`)).join('')}</div></details>${status}`)],
 ['Wallet card','Content','Balance privacy / copy','A sample account surface with concealed balance and a copyable demonstration identifier.',wrap('wallet',`<div class="wallet-surface"><div class="row spread"><span>Demo wallet</span>${b(icon('eye'),'wallet-hide','aria-label="Hide balance" aria-pressed="false"')}</div><strong data-wallet-balance>$1,250.00</strong><span class="hint">Sample balance · no connected account</span><div class="row spread"><code>syntari-demo-0001</code>${b(icon('copy'),'wallet-copy','aria-label="Copy demo identifier"')}</div></div>`)],
 ['Prediction card','Data display','Choose / confirm','A product-planning prediction sample with local choices; no betting or payment.',wrap('prediction',`<h3>Will the next milestone ship this week?</h3><p class="hint">Team forecast · local preview</p><div class="prediction-meter"><span></span></div><div class="row spread"><span>Yes · 72%</span><span>No · 28%</span></div><div class="row">${b('Yes','predict','data-title="Yes" aria-pressed="false"')}${b('No','predict','data-title="No" aria-pressed="false"')}</div>${status}`)],
 ['Bloom menu','Action','Expand / choose','Circular actions float above a central trigger that clearly changes between Create and Close.',wrap('bloom',`<div class="bloom-anchor"><div class="bloom-options" role="group" aria-label="Create options" hidden>${b(icon('file'),'bloom-choice','aria-label="New document" data-title="Document"')}${b(icon('folder'),'bloom-choice','aria-label="New folder" data-title="Folder"')}${b(icon('chat'),'bloom-choice','aria-label="New conversation" data-title="Conversation"')}</div>${b(icon('plus')+'<span>Create</span>','bloom-toggle','aria-expanded="false"')}</div>${status}`)],
 ['Morphing search','Navigation','Expand / search / clear','An inline search expands in place and filters a small set of recent projects.',wrap('search',`${b(icon('search')+' Find a project','search-expand','aria-expanded="false"')}<div class="morph-search-field" hidden><label class="field">Find a project<input type="search" data-extra-search placeholder="Search projects…"></label>${b('Close','search-close')}</div><ul class="search-projects">${['Brand refresh','Website exploration','Customer research'].map(t=>`<li>${t}</li>`).join('')}</ul>${status}`)],
 ['Action swap','Action','Idle / working / complete','A single action changes its label and icon as work progresses.',wrap('action',`${b(icon('download')+' Prepare export','action-swap')}${status}`)],
 ['Agent questions','Agents','Choice / text / review','A small guided approval flow combines radio options, free text, and a reviewable result.',wrap('questions',`<form data-question-form><div data-question-stage><h3>What should we focus on?</h3><fieldset><legend class="sr-only">Focus</legend>${['Design','Behavior','Accessibility'].map((t,i)=>`<label class="choice"><input type="radio" name="focus" value="${t}" ${i===0?'checked':''}>${t}</label>`).join('')}</fieldset><label class="field">Anything to preserve?<textarea name="notes" rows="2" maxlength="200" placeholder="Optional details"></textarea></label></div><p role="status" class="hint" data-question-result>Step 1 of 2</p><button type="submit" class="button small primary">Review response</button></form>`)]
 ];rows.forEach(r=>add(...r));
 function report(root,text){const status=root.querySelector('[data-extra-status]');if(status)SyntariMotion.feedback(status,text)}
 function animate(el){if(!matchMedia('(prefers-reduced-motion: reduce)').matches)SyntariMotion.panel(el)}
 function setBloom(root,open,restoreFocus=false){
  const options=root.querySelector('.bloom-options'),trigger=root.querySelector('[data-extra=bloom-toggle]'),choices=[...options.querySelectorAll('[data-extra=bloom-choice]')];
  trigger.setAttribute('aria-expanded',open);root.toggleAttribute('data-open',open);trigger.innerHTML=icon(open?'x':'plus')+`<span>${open?'Close':'Create'}</span>`;
  if(open){options.hidden=false;options.inert=false;choices.forEach((choice,index)=>SyntariMotion.animate(choice,[{opacity:0,transform:'translateY(12px) scale(.78)'},{opacity:1,transform:'translateY(0) scale(1)'}],240,{delay:index*38,fill:'backwards'}));}
  else if(matchMedia('(prefers-reduced-motion: reduce)').matches){options.hidden=true;options.inert=false;}
  else {options.inert=true;const animations=choices.slice().reverse().map((choice,index)=>SyntariMotion.animate(choice,[{opacity:1,transform:'translateY(0) scale(1)'},{opacity:0,transform:'translateY(8px) scale(.82)'}],150,{delay:index*24,fill:'forwards'}));Promise.all(animations.map(a=>a?.finished.catch(()=>{}))).then(()=>{if(trigger.getAttribute('aria-expanded')==='false'){options.hidden=true;options.inert=false}})}
  if(restoreFocus)trigger.focus();
 }
 document.addEventListener('click',async ev=>{const activeBloom=ev.target.closest('[data-extra-kind=bloom]');document.querySelectorAll('[data-extra-kind=bloom][data-open]').forEach(root=>{if(root!==activeBloom)setBloom(root,false)});const el=ev.target.closest('[data-extra]');if(!el)return;const root=el.closest('[data-extra-kind]'),a=el.dataset.extra;
 if(a==='folder-file'||a==='fixture'){root.querySelectorAll(`[data-extra="${a}"]`).forEach(x=>x.setAttribute('aria-pressed',x===el));report(root,el.dataset.title+' selected.');}
 if(a==='tilt-open'){report(root,'Project preview opened. Ready for your next idea.');SyntariStarter.openProject();}
 if(a==='marquee-toggle'||a==='ambient-toggle'){const active=root.classList.toggle('is-playing');el.setAttribute('aria-pressed',active);el.textContent=active?'Pause':a==='marquee-toggle'?'Play':'Animate background'}
 if(a==='refresh'||a==='action-swap'){
  el.disabled=true;el.setAttribute('aria-busy','true');root.dataset.phase='working';
  el.innerHTML='<span class="spinner" aria-hidden="true"></span><span>'+(a==='refresh'?'Refreshing…':'Preparing…')+'</span>';animate(el.lastElementChild);
  setTimeout(()=>{if(!root.isConnected)return;el.disabled=false;el.removeAttribute('aria-busy');root.dataset.phase='complete';
   el.innerHTML=icon('circlecheck')+'<span>'+(a==='refresh'?'Refresh again':'Prepare again')+'</span>';animate(el.lastElementChild);animate(el.firstElementChild);
   if(a==='refresh')SyntariMotion.feedback(root.querySelector('[role=status]'),'Updated at '+new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'}));
   else report(root,'Export ready. You can prepare it again.');
  },850);
 }
 if(a==='carousel-next'||a==='carousel-prev'){let i=(Number(root.dataset.index||0)+(a==='carousel-next'?1:2))%3;root.dataset.index=i;root.querySelectorAll('[data-card]').forEach((card,n)=>card.hidden=n!==i);root.querySelector('[data-carousel-count]').textContent=`${i+1} of 3`;SyntariMotion.animate(root.querySelector(`[data-card="${i}"]`),[{opacity:0,transform:`translateX(${a==='carousel-next'?18:-18}px)`},{opacity:1,transform:'translateX(0)'}],280)}
 if(a==='masonry-more'){const count=root.querySelectorAll('.masonry-grid>div').length;for(let i=0;i<3;i++){const tile=document.createElement('div');tile.style.setProperty('--tile-height',(80+(i%3)*30)+'px');tile.innerHTML=icon('image')+'<span>Study '+(count+i+1)+'</span>';root.querySelector('.masonry-grid').append(tile);animate(tile)}report(root,`${count+3} studies loaded`);if(count>=10){el.disabled=true;el.textContent='All studies loaded'}}
 if(a==='swap-reverse'){const reverse=root.dataset.reverse!=='true';root.dataset.reverse=reverse;const to=reverse?'DAI':'USDC',other=reverse?'USDC':'DAI',picker=root.querySelector('.swap-coin');picker.querySelector('[data-select-label]').textContent=to;const mark=picker.querySelector('[data-coin-mark]');mark.className='coin-badge coin-'+(to==='USDC'?'usdc':'dai');mark.textContent=to==='USDC'?'◈':'◉';root.querySelector('[data-swap-label]').textContent='To · '+other;const note=root.querySelector('[data-swap-note]');if(note)note.textContent='Rate 1:1 · Network fee ~$0.42 · You’ll receive 99.58 '+other;animate(root.querySelector('.swap-quote'));animate(root.querySelector('.swap-input'));report(root,'Assets reversed. Fixed demo rate.')}
 if(a==='swap-preview'){const amount=Number(root.querySelector('input').value);report(root,amount>0?`Preview: swap ${amount.toFixed(2)} at the fixed 1:1 demo rate. Nothing will be sent.`:'Enter an amount greater than zero.')}
 if(a==='overflow-choice'){root.querySelector('details').open=false;report(root,el.dataset.title+' selected in preview.');root.querySelector('summary').focus()}
 if(a==='wallet-hide'){const hidden=el.getAttribute('aria-pressed')!=='true';el.setAttribute('aria-pressed',hidden);el.setAttribute('aria-label',hidden?'Show balance':'Hide balance');el.innerHTML=icon(hidden?'eye-off':'eye');SyntariMotion.feedback(root.querySelector('[data-wallet-balance]'),hidden?'••••••':'$1,250.00')}
 if(a==='wallet-copy'){try{await navigator.clipboard.writeText('syntari-demo-0001');showToast('Demo identifier copied.')}catch{showToast('Copy unavailable. Select the identifier to copy.')}}
 if(a==='predict'){root.querySelectorAll('[data-extra=predict]').forEach(x=>x.setAttribute('aria-pressed',x===el));report(root,`${el.dataset.title} selected. Your local forecast is saved.`)}
 if(a==='bloom-toggle')setBloom(root,el.getAttribute('aria-expanded')!=='true')
 if(a==='bloom-choice'){report(root,el.dataset.title+' selected.');setBloom(root,false,true)}
 if(a==='search-expand'||a==='search-close'){const open=a==='search-expand';root.querySelector('.morph-search-field').hidden=!open;root.querySelector('[data-extra=search-expand]').hidden=open;root.querySelector('[data-extra=search-expand]').setAttribute('aria-expanded',open);if(open){animate(root.querySelector('.morph-search-field'));root.querySelector('input').focus()}else{root.querySelector('[data-extra=search-expand]').focus()}}
 });
 document.addEventListener('keydown',ev=>{const root=ev.target.closest('[data-extra-kind=bloom]');if(root&&ev.key==='Escape'&&root.hasAttribute('data-open')){ev.preventDefault();setBloom(root,false,true)}});
 document.addEventListener('click',e=>{const option=e.target.closest('.swap-coin [data-option]');if(!option)return;const root=option.closest('[data-extra-kind]');const to=root.querySelector('[data-swap-label]').textContent.replace('To · ','');const note=root.querySelector('[data-swap-note]');if(note)note.textContent='Rate 1:1 · Network fee ~$0.42 · You’ll receive 99.58 '+to});
 document.addEventListener('input',ev=>{const root=ev.target.closest('[data-extra-kind]');if(!root)return;if(ev.target.hasAttribute('data-bound')){const min=root.querySelector('[data-bound=min]'),max=root.querySelector('[data-bound=max]');if(+min.value>+max.value){if(ev.target===min)max.value=min.value;else min.value=max.value}root.querySelector('[data-range-output]').textContent=`$${min.value} – $${max.value}`;[min,max].forEach(x=>{x.closest('label').querySelector('output').textContent=x.value;x.style.setProperty('--range-fill',(+x.value/10)+'%')})}if(ev.target.hasAttribute('data-swap-amount'))root.querySelector('[data-swap-output]').textContent=Math.max(0,Number(ev.target.value)||0).toFixed(2);if(ev.target.hasAttribute('data-extra-search')){let n=0;root.querySelectorAll('li').forEach(li=>{li.hidden=!li.textContent.toLowerCase().includes(ev.target.value.toLowerCase());if(!li.hidden)n++});report(root,n?`${n} ${n===1?'project':'projects'}`:'No matching projects.');animate(root.querySelector('.search-projects'))}});
 document.addEventListener('submit',ev=>{const form=ev.target;if(!form.matches('[data-question-form]'))return;ev.preventDefault();const result=form.querySelector('[data-question-result]');if(form.dataset.review){result.textContent='Response saved in this preview.';form.querySelector('button').textContent='Start again';form.dataset.review='';form.dataset.complete='true'}else if(form.dataset.complete){form.dataset.complete='';form.querySelector('[data-question-stage]').hidden=false;result.textContent='Step 1 of 2';form.querySelector('button').textContent='Review response'}else{form.dataset.review='true';result.textContent=`Review: focus on ${form.elements.focus.value.toLowerCase()}. ${form.elements.notes.value||'No additional constraints.'}`;form.querySelector('[data-question-stage]').hidden=true;form.querySelector('button').textContent='Confirm response'}});
 document.addEventListener('pointermove',ev=>{const tilt=ev.target.closest('.syntari-tilt');if(!tilt||ev.pointerType==='touch'||matchMedia('(prefers-reduced-motion: reduce)').matches)return;const r=tilt.getBoundingClientRect();tilt.style.setProperty('--tilt-x',((ev.clientX-r.left)/r.width*100)+'%');tilt.style.setProperty('--tilt-y',((ev.clientY-r.top)/r.height*100)+'%');tilt.style.transform=`perspective(700px) rotateX(${(0.5-(ev.clientY-r.top)/r.height)*7}deg) rotateY(${((ev.clientX-r.left)/r.width-0.5)*7}deg)`});document.addEventListener('pointerout',ev=>{const tilt=ev.target.closest('.syntari-tilt');if(tilt&&!tilt.contains(ev.relatedTarget))tilt.style.transform=''});
 let pull=null;document.addEventListener('pointerdown',ev=>{const root=ev.target.closest('[data-extra-kind=refresh]');if(root&&!ev.target.closest('button'))pull={root,y:ev.clientY}});document.addEventListener('pointerup',ev=>{if(pull&&ev.clientY-pull.y>70)pull.root.querySelector('[data-extra=refresh]').click();pull=null});document.addEventListener('pointercancel',()=>pull=null);
 let bloomId=0;function prepare(root){root.querySelectorAll('[data-bound]').forEach(input=>input.style.setProperty('--range-fill',(+input.value/10)+'%'));root.querySelectorAll('[data-extra-kind=bloom]').forEach(bloom=>{const options=bloom.querySelector('.bloom-options'),trigger=bloom.querySelector('[data-extra=bloom-toggle]');if(!options.id)options.id=`syntari-bloom-options-${++bloomId}`;trigger.setAttribute('aria-controls',options.id)})}
 window.SyntariExtras={prepare};
 renderGallery();if(window.SyntariEmbed)return;const initial=new URLSearchParams(location.search);if(initial.get('view')==='screens'){const screen=initial.get('screen')||'settings';setView('screens');SyntariStarter.showScreen(screen)}else if(initial.get('view')==='foundations')setView('foundations');else if(initial.get('category') in categoryIcons)setView('gallery',initial.get('category'));
})();
