/* Orbit starter patterns. Plain DOM components, local demo state, no service calls. */
(() => {
 const h=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const unique=()=>`orbit-${Math.random().toString(36).slice(2,10)}`;
 const button=(text,attrs='',cls='')=>`<button type="button" class="button ${cls}" ${attrs}>${text}</button>`;
 const field=(label,input,help='')=>`<label class="field"><span>${label}</span>${input}${help?`<span class="hint">${help}</span>`:''}</label>`;
 const projects=[
 {id:1,name:'Brand refresh',detail:'Identity, guidelines, and a fresh perspective.',status:'Active',updated:'2026-09-10',owner:'Jamie Chen'},
 {id:2,name:'Website exploration',detail:'A simpler way to tell our story.',status:'Active',updated:'2026-09-09',owner:'Alex Morgan'},
 {id:3,name:'Customer research',detail:'Conversations that shape the next release.',status:'Review',updated:'2026-09-08',owner:'Sam Rivera'},
 {id:4,name:'Mobile companion',detail:'The useful things, wherever you are.',status:'Active',updated:'2026-09-07',owner:'Jamie Chen'},
 {id:5,name:'Autumn campaign',detail:'Thoughtful touchpoints for a new season.',status:'Review',updated:'2026-09-06',owner:'Alex Morgan'},
 {id:6,name:'Design foundations',detail:'A shared language for the whole team.',status:'Archived',updated:'2026-09-05',owner:'Sam Rivera'},
 {id:7,name:'Help center',detail:'Clear answers, one search away.',status:'Active',updated:'2026-09-04',owner:'Jamie Chen'},
 {id:8,name:'Release notes',detail:'A little context for everything new.',status:'Archived',updated:'2026-09-03',owner:'Alex Morgan'}];
 const members=[
 {id:11,name:'Alex Morgan',detail:'alex@studio.example',status:'Active',updated:'Owner',owner:'Design'},
 {id:12,name:'Jamie Chen',detail:'jamie@studio.example',status:'Active',updated:'Admin',owner:'Product'},
 {id:13,name:'Sam Rivera',detail:'sam@studio.example',status:'Active',updated:'Member',owner:'Engineering'},
 {id:14,name:'Robin Park',detail:'robin@studio.example',status:'Invited',updated:'Member',owner:'Design'},
 {id:15,name:'Casey Lewis',detail:'casey@studio.example',status:'Active',updated:'Member',owner:'Product'},
 {id:16,name:'Taylor Reed',detail:'taylor@studio.example',status:'Invited',updated:'Member',owner:'Operations'}];
 let profile={name:'Alex Morgan',email:'alex@studio.example',bio:'Making useful things with thoughtful people.',digest:true,updates:false};
 try{const saved=JSON.parse(localStorage.getItem('orbit-profile')||'null');if(saved&&typeof saved.name==='string'&&typeof saved.email==='string')profile={...profile,...saved}}catch{}
 let currentScreen='settings',onboardStep=0,onboard={email:'',workspace:'',purpose:'Product'},layerAction=null,layerAfterClose=null;
 const tableStates=new WeakMap(),comboStates=new WeakMap(),uploadJobs=new WeakMap();
 const tableRoots=new Set();
 const combo=(label,options,mode='single',placeholder='Search or choose…')=>`<div class="field combo-field" data-starter-combo data-mode="${mode}" data-options="${h(JSON.stringify(options))}"><label>${label}</label><div class="combo-input">${icon('search')}<input type="text" role="combobox" aria-label="${label}" aria-expanded="false" aria-autocomplete="list" autocomplete="off" placeholder="${placeholder}"><button type="button" class="combo-clear" aria-label="Clear ${label}" data-combo-clear>${icon('x')}</button></div><div class="starter-options" role="listbox" aria-label="${label} options" hidden></div>${mode==='multiple'?'<div class="row combo-chips" aria-label="Selected values"></div>':''}<span class="sr-only" role="status"></span></div>`;
 const stepper=(label='Seats',value=3,min=1,max=20)=>`<div class="field"><label>${label}</label><div class="number-stepper"><button type="button" aria-label="Decrease ${label}" data-number-step="-1">${icon('minus' in paths?'minus':'x')}</button><input type="number" inputmode="numeric" min="${min}" max="${max}" value="${value}" aria-label="${label}"><button type="button" aria-label="Increase ${label}" data-number-step="1">${icon('plus')}</button></div><span class="hint">${min}–${max} ${label.toLowerCase()}</span></div>`;
 const password=(label='Password',name='password')=>`<label class="field">${label}<span class="password-control"><input type="password" name="${name}" minlength="8" required autocomplete="new-password" placeholder="At least 8 characters"><button type="button" data-password-toggle aria-label="Show ${label.toLowerCase()}" aria-pressed="false">${icon('eye' in paths?'eye':'lock')}</button></span></label>`;
 const selectable=(name='plan')=>`<fieldset class="selectable-cards"><legend>Choose your workspace</legend>${[['Personal','A space for your own ideas.','smile'],['Team','Bring a few good people.','layers']].map(([title,copy,ic],i)=>`<label><input type="radio" name="${name}" value="${title}" ${!i?'checked':''}><span>${icon(ic)}<strong>${title}</strong><small>${copy}</small><span class="selection-check">${icon('check')}</span></span></label>`).join('')}</fieldset>`;
 const table=(kind='projects')=>`<section class="data-table" data-starter-table data-kind="${kind}"><div class="data-table-toolbar"><label class="search table-search">${icon('search')}<input type="search" aria-label="Search ${kind}" placeholder="Search ${kind}…"></label><div class="row">${button('All statuses '+icon('down'),'data-table-status','small') }<details class="column-picker"><summary>${icon('sliders')} Columns</summary><div>${['status','updated'].map(k=>`<label class="choice"><input type="checkbox" checked data-table-column="${k}">${k==='updated'?(kind==='members'?'Role':'Updated'):'Status'}</label>`).join('')}</div></details></div></div><div data-table-selection class="table-selection" hidden><span role="status"></span>${button('Archive selected','data-table-bulk','small')}</div><div class="table-scroll" data-table-grid></div><div class="table-foot"><span data-table-count role="status"></span><div class="row">${button(icon('chevron'),'data-table-page="-1" aria-label="Previous results"','small previous-results')}<span data-table-page-label></span>${button(icon('chevron'),'data-table-page="1" aria-label="Next results"','small')}</div></div></section>`;
 const thumb=(color='lavender',label='Brand exploration')=>`<button type="button" class="asset-thumbnail ${color}" data-lightbox="${h(label)}" aria-label="Preview ${h(label)}"><span class="asset-art" aria-hidden="true"><span></span><span></span><span></span></span><span class="thumbnail-caption">${h(label)} ${icon('external')}</span></button>`;
 const dateRange=()=>`<div class="field"><span>Reporting period</span><button type="button" class="control-trigger" data-date-range data-start="2026-09-04" data-end="2026-09-10"><span>Sep 4 – Sep 10, 2026</span>${icon('calendar')}</button><span class="hint">Choose a start and end date.</span></div>`;
 const timePicker=()=>`<div class="field"><span>Meeting time</span><button type="button" class="control-trigger" data-time-picker data-time="09:30"><span>09:30</span>${icon('clock' in paths?'clock':'gauge')}</button><span class="hint">Your local time</span></div>`;
 const metadata=()=>`<dl class="metadata-list"><div><dt>Owner</dt><dd><span class="avatar tiny blue"></span> Jamie Chen</dd></div><div><dt>Status</dt><dd>${badge('Active','green')}</dd></div><div><dt>Created</dt><dd>September 4, 2026</dd></div><div><dt>Visibility</dt><dd>${icon('lock')} Team only</dd></div></dl>`;
 const validation=()=>`<form class="validation-demo" data-validation-form novalidate>${field('Work email','<input type="email" name="email" placeholder="you@studio.com" required>')}<p class="form-error" role="alert" hidden></p><button class="button primary" type="submit">Continue ${icon('arrow')}</button><p class="hint">Try an incomplete email to see validation.</p></form>`;
 const upload=()=>`<div class="upload-demo"><div class="row"><span class="empty-icon">${icon('upload')}</span><div><h3>Workspace assets</h3><p class="hint">Simulated upload · no file is sent</p></div></div><div class="progress" role="progressbar" aria-label="Demo upload" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0"><span style="width:0%"></span></div><div class="row spread"><span data-upload-label role="status">Ready to upload</span><div class="row">${button('Start upload','data-upload-start','small')}${button('Cancel','data-upload-cancel disabled','small ghost')}</div></div></div>`;
 const unsaved=()=>`<form class="unsaved-demo" data-unsaved-form>${field('Workspace name','<input name="workspace" value="Orbit Studio" required maxlength="60">')}<div class="unsaved-bar" hidden><span>Unsaved changes</span><div class="row">${button('Discard','data-discard-draft','small ghost')}<button class="button primary small" type="submit">Save</button></div></div><p class="hint" data-saved-label>Edit the name to preview the save bar.</p></form>`;
 const pageHeader=()=>`<div class="sample-page-header"><nav class="breadcrumbs" aria-label="Breadcrumb">${button('Workspace','data-breadcrumb="Workspace"','ghost small')}${icon('chevron')}<span aria-current="page">Projects</span></nav><div class="row spread"><div><h2>Projects</h2><p>Room for your next idea.</p></div>${button(icon('plus')+' New project','data-create-record','small')}</div></div>`;
 const shell=()=>`<div class="mini-app-shell"><aside><button type="button" aria-label="Collapse sidebar" data-mini-collapse>${icon('layout')}</button>${['Projects','People','Settings'].map((x,i)=>`<button type="button" data-mini-nav="${x}" aria-pressed="${!i}" class="${!i?'active':''}">${icon(['folder','smile','settings'][i])}<span>${x}</span></button>`).join('')}</aside><div><span class="hint">Orbit Studio</span><h3 data-mini-heading>Projects</h3><p data-mini-copy>Everything you’re working on, together.</p><div class="mini-shell-lines" aria-hidden="true"><span></span><span></span><span></span></div></div><nav class="mini-mobile-nav" aria-label="Mobile navigation">${['Projects','People','Settings'].map((x,i)=>`<button type="button" data-mini-nav="${x}" aria-label="${x}" aria-pressed="${!i}">${icon(['folder','smile','settings'][i])}</button>`).join('')}</nav></div>`;

 function register(){
  add('App shell','Layout','Responsive / collapsible','A reusable sidebar, content region, and mobile navigation. The composed screens use the same pattern.',shell());
  add('Page header & breadcrumbs','Navigation','Context / actions','A page title, supporting description, breadcrumb trail, and primary action share a reusable alignment.',pageHeader());
  add('Side drawer','Overlay','Details / editing','Inspect and edit a record without losing your place. Native modal semantics keep keyboard focus inside until dismissed.',`<div class="empty-icon">${icon('layout')}</div>${button('Open project details '+icon('arrow'),'data-open-drawer')}<span class="label-caption">A little more context, close by.</span>`);
  add('Bottom sheet','Overlay','Mobile / desktop','A compact action surface rises from the bottom, with Escape and backdrop dismissal.',`<div class="empty-icon">${icon('layers')}</div>${button('Share workspace','data-open-sheet')}<span class="label-caption">Actions within reach.</span>`);
  add('Popover','Overlay','Contextual controls','Small controls appear next to their trigger and dismiss on outside click or Escape.',`<div class="starter-popover"><button type="button" class="button" data-popover-toggle aria-expanded="false">${icon('bell')} Notification preferences</button><div class="starter-popover-panel" hidden><h3>Keep me in the loop</h3><label class="choice"><input type="checkbox" checked>Mentions and replies</label><label class="choice"><input type="checkbox">Weekly summary</label><p class="hint">Changes apply to this preview.</p></div></div>`);
  add('Confirmation dialog','Overlay','Destructive / cancel','Confirm a consequential action with a clear description, safe cancel action, and explicit outcome.',`<div class="mini-card"><h3>Archive this project?</h3><p>You can restore it from archived projects.</p>${button('Archive project','data-demo-confirm','small danger')}</div>`);
  add('Searchable select','Form controls','Filter / keyboard','Search a list of options. Arrow keys move the active option; Enter commits and Escape dismisses.',combo('Assign to',['Alex Morgan','Jamie Chen','Sam Rivera','Robin Park','Casey Lewis']));
  add('Autocomplete','Form controls','Suggestions / custom values','Suggestions narrow as you type. Choose an existing value or keep a custom value.',combo('Project name',['Brand refresh','Website exploration','Mobile companion','Customer research'],'free','Start typing a project…'));
  add('Multiselect','Form controls','Search / removable chips','Select several values from a searchable list. Remove selected chips without reopening the list.',combo('Project labels',['Design','Research','Engineering','Marketing','Operations'],'multiple','Find a label…'));
  add('Command palette','Overlay','Search / shortcuts','Find screens, components, and common actions with the keyboard. Open anywhere with Command/Ctrl K.',`${button(icon('search')+' Search or jump to… <kbd>⌘ K</kbd>','data-open-command')}<span class="label-caption">One place to find your way.</span>`);
  add('Number stepper','Form controls','Bounds / keyboard','Increment, decrement, or enter a number. Boundary buttons disable at the minimum and maximum.',stepper());
  add('Password field','Form controls','Reveal / concealed','Reveal a password without changing its value. The toggle exposes its pressed state and updates its label.',`<div class="stack">${password()}<p class="hint">Use at least 8 characters.</p></div>`);
  add('Date range picker','Form controls','Range / presets','Choose two dates across months, or use a quick preset. Apply commits the selection; cancel preserves the original value.',dateRange());
  add('Time picker','Form controls','Hours / minutes','A time control with custom steppers and explicit confirmation, styled with the shared popup surface.',timePicker());
  add('Selectable cards','Form controls','Single selection','A richer radio option combines a title, description, and Lucide icon. Native radio semantics preserve keyboard behavior.',selectable());
  add('Data table','Table & list','Sort / filter / bulk actions','Sort, search, filter, hide columns, select rows, paginate, expand details, and edit records. Actions update local preview data.',table());
  add('Inline validation','Feedback & status','Invalid / success','Associated inline errors explain how to correct an invalid field. Valid input replaces the error with confirmation.',validation());
  add('Error & retry','Feedback & status','Error / loading / recovered','Recover from a failed load without losing context. Retry shows a loading state before replacing the error.',`<div class="retry-demo"><div class="empty-icon">${icon('info')}</div><h3>Couldn’t load your projects</h3><p>Try again to pick up where you left off.</p>${button('Try again','data-retry')}</div>`);
  add('Upload progress','Feedback & status','Progress / cancel / complete','A bounded progress simulation with cancel and retry. Screen-reader updates announce milestones, not every frame.',upload());
  add('Unsaved changes','Feedback & status','Edit / save / discard','A contextual save bar appears when values differ from the saved version. Discard restores the original.',unsaved());
  add('Metadata list','Content','Labels / values','Aligned labels and values display the details that accompany a record.',metadata());
  add('Thumbnail & lightbox','Content','Preview / zoom','Local abstract artwork demonstrates an asset thumbnail and larger lightbox preview. Escape returns focus to the thumbnail.',`<div class="thumbnail-pair">${thumb()}${thumb('mint','Color studies')}</div>`);
  add('Divider & form section','Layout','Grouped fields','A titled section and quiet divider separate related fields without adding another card.',`<div class="form-section-demo"><div><h3>Workspace details</h3><p>The basics, in one place.</p></div>${field('Name','<input value="Orbit Studio">')}<hr class="ds-divider"><div class="row spread"><span>Private workspace</span><label class="switch"><input type="checkbox" role="switch" aria-label="Private workspace" checked><span></span></label></div></div>`);
 }

 function position(panel,trigger){const r=trigger.getBoundingClientRect(),w=Math.min(Number(panel.dataset.width)||Math.max(240,r.width),innerWidth-24);panel.style.width=`${w}px`;panel.style.left=`${Math.max(12,Math.min(r.left,innerWidth-w-12))}px`;panel.style.top=`${r.bottom+6}px`;const height=panel.getBoundingClientRect().height;if(r.bottom+height+8>innerHeight&&r.top-height-6>10)panel.style.top=`${r.top-height-6}px`;}
 function closeFloating(restore=false){document.querySelectorAll('.starter-options:not([hidden]),.starter-popover-panel:not([hidden]),.row-action-menu:not([hidden])').forEach(panel=>{const trigger=panel.parentElement.querySelector('[role=combobox],[data-popover-toggle],[data-row-actions]');if(trigger)trigger.setAttribute('aria-expanded','false');OrbitMotion.visibility(panel,false);if(restore)trigger?.focus()})}
 function ensureCombo(root){if(comboStates.has(root))return comboStates.get(root);const input=root.querySelector('input'),list=root.querySelector('[role=listbox]'),label=root.querySelector('label'),id=unique();input.id=id;label.htmlFor=id;list.id=id+'-options';input.setAttribute('aria-controls',list.id);if(root.dataset.mode==='multiple')list.setAttribute('aria-multiselectable','true');const state={options:JSON.parse(root.dataset.options),selected:[],active:-1,filtered:[]};comboStates.set(root,state);return state}
 function renderCombo(root,open=true){const s=ensureCombo(root),input=root.querySelector('input'),list=root.querySelector('[role=listbox]'),term=input.value.toLowerCase();s.filtered=s.options.filter(x=>x.toLowerCase().includes(term));if(root.dataset.mode==='free'&&input.value.trim()&&!s.filtered.includes(input.value.trim()))s.filtered.push(input.value.trim());s.active=Math.min(s.active,s.filtered.length-1);list.innerHTML=s.filtered.length?s.filtered.map((x,i)=>`<button type="button" role="option" tabindex="-1" id="${list.id}-${i}" aria-selected="${s.selected.includes(x)}" data-combo-option="${h(x)}" class="${s.active===i?'active':''}"><span>${h(x)}</span>${s.selected.includes(x)?icon('check'):''}</button>`).join(''):'<div class="combo-no-results">No matches. Try another search.</div>';if(s.active>=0)input.setAttribute('aria-activedescendant',`${list.id}-${s.active}`);else input.removeAttribute('aria-activedescendant');if(open){list.hidden=false;list.inert=false;input.setAttribute('aria-expanded','true');position(list,root.querySelector('.combo-input'))}if(root.dataset.mode==='multiple')root.querySelector('.combo-chips').innerHTML=s.selected.map(x=>`<span class="chip">${h(x)}<button type="button" data-combo-remove="${h(x)}" aria-label="Remove ${h(x)}">${icon('x')}</button></span>`).join('');root.querySelector('.combo-clear').hidden=!input.value;}
 function chooseCombo(root,value){const s=ensureCombo(root),input=root.querySelector('input');if(root.dataset.mode==='multiple'){s.selected=s.selected.includes(value)?s.selected.filter(x=>x!==value):[...s.selected,value];input.value='';s.active=-1;renderCombo(root);input.focus()}else{s.selected=[value];input.value=value;renderCombo(root,false);closeFloating();input.focus();input.setAttribute('aria-expanded','false')}root.querySelector('[role=status]').textContent=root.dataset.mode==='multiple'?`${s.selected.length} selected`:value;}
 function refreshTables(){for(const root of tableRoots){if(!root.isConnected){tableRoots.delete(root);continue}renderTable(root)}}
 function ensureTable(root){if(tableStates.has(root))return tableStates.get(root);const state={query:'',status:'All statuses',sort:'name',direction:1,page:1,size:5,selected:new Set(),expanded:new Set(),columns:{status:true,updated:true}};tableStates.set(root,state);tableRoots.add(root);return state}
 function rowsFor(root){return root.dataset.kind==='members'?members:projects}
 function renderTable(root){const s=ensureTable(root),member=root.dataset.kind==='members',all=rowsFor(root);let rows=all.filter(r=>(s.status==='All statuses'||r.status===s.status)&&`${r.name} ${r.detail} ${r.owner}`.toLowerCase().includes(s.query.toLowerCase())).sort((a,b)=>String(a[s.sort]).localeCompare(String(b[s.sort]),'en',{numeric:true})*s.direction);const pages=Math.max(1,Math.ceil(rows.length/s.size));s.page=Math.min(s.page,pages);const visible=rows.slice((s.page-1)*s.size,s.page*s.size),colCount=3+Number(s.columns.status)+Number(s.columns.updated);
 root.querySelector('[data-table-grid]').innerHTML=`<table class="advanced-table"><caption class="sr-only">${member?'Team members':'Workspace projects'}</caption><thead><tr><th class="check-cell"><label class="choice"><input type="checkbox" data-table-all aria-label="Select all visible rows" ${!visible.length?'disabled':''}></label></th><th scope="col" aria-sort="${s.sort==='name'?(s.direction===1?'ascending':'descending'):'none'}"><button type="button" data-table-sort="name">${member?'Member':'Project'} ${icon('down')}</button></th>${s.columns.status?`<th scope="col" aria-sort="${s.sort==='status'?(s.direction===1?'ascending':'descending'):'none'}"><button type="button" data-table-sort="status">Status ${icon('down')}</button></th>`:''}${s.columns.updated?`<th scope="col" aria-sort="${s.sort==='updated'?(s.direction===1?'ascending':'descending'):'none'}"><button type="button" data-table-sort="updated">${member?'Role':'Updated'} ${icon('down')}</button></th>`:''}<th scope="col"><span class="sr-only">Actions</span></th></tr></thead><tbody>${visible.length?visible.map(r=>`<tr class="${s.selected.has(r.id)?'is-selected':''}"><td class="check-cell"><label class="choice"><input type="checkbox" data-table-select="${r.id}" aria-label="Select ${h(r.name)}" ${s.selected.has(r.id)?'checked':''}></label></td><th scope="row"><button type="button" class="record-name" data-table-expand="${r.id}" aria-expanded="${s.expanded.has(r.id)}">${icon('chevron')}<span>${h(r.name)}<small>${h(member?r.detail:r.owner)}</small></span></button></th>${s.columns.status?`<td>${badge(h(r.status),r.status==='Active'?'green':r.status==='Archived'?'':'purple')}</td>`:''}${s.columns.updated?`<td class="table-secondary">${h(member?r.updated:new Date(r.updated+'T12:00:00').toLocaleDateString('en-US',{month:'short',day:'numeric'}))}</td>`:''}<td><div class="record-actions"><button type="button" class="icon-button" data-row-actions aria-label="Actions for ${h(r.name)}" aria-expanded="false">${icon('more')}</button><div class="dropdown-panel row-action-menu" data-width="175" hidden><button type="button" data-record-edit="${r.id}">${icon('edit')} ${member?'Edit member':'Edit project'}</button><button type="button" data-record-archive="${r.id}">${icon('folder')} ${r.status==='Archived'?'Restore':'Archive'}</button></div></div></td></tr>${s.expanded.has(r.id)?`<tr class="expanded-record"><td colspan="${colCount}"><p>${h(r.detail)}</p><span>${member?'Team: '+h(r.owner):'Owner: '+h(r.owner)}</span>${button('Open details '+icon('arrow'),`data-record-edit="${r.id}"`,'small ghost')}</td></tr>`:''}`).join(''):`<tr><td colspan="${colCount}"><div class="table-empty">${icon('search')}<h3>No matching ${member?'members':'projects'}</h3><p>Try another name or clear the filters.</p>${button('Clear filters','data-table-reset','small')}</div></td></tr>`}</tbody></table>`;
 const allInput=root.querySelector('[data-table-all]');allInput.checked=visible.length>0&&visible.every(r=>s.selected.has(r.id));allInput.indeterminate=!allInput.checked&&visible.some(r=>s.selected.has(r.id));s.visible=visible.map(r=>r.id);const bar=root.querySelector('[data-table-selection]');bar.hidden=s.selected.size===0;bar.querySelector('span').textContent=`${s.selected.size} selected`;root.querySelector('[data-table-count]').textContent=rows.length?`${(s.page-1)*s.size+1}–${Math.min(s.page*s.size,rows.length)} of ${rows.length}`:'0 results';root.querySelector('[data-table-page-label]').textContent=`${s.page} / ${pages}`;root.querySelector('[data-table-page="-1"]').disabled=s.page===1;root.querySelector('[data-table-page="1"]').disabled=s.page===pages;
 }
 function layer(){return document.querySelector('#starter-dialog')}
 function openLayer({title,body,kind='',footer='',action=null,afterClose=null}){const dialog=layer();layerAction=action;layerAfterClose=afterClose;dialog.className=`starter-layer ${kind}`;dialog.innerHTML=`<div class="dialog-heading"><div><p class="muted">Orbit Studio</p><h2 id="starter-layer-title">${h(title)}</h2></div><button type="button" class="icon-button" data-close aria-label="Close ${h(title)}">${icon('x')}</button></div><div class="starter-layer-body">${body}</div>${footer?`<div class="dialog-footer">${footer}</div>`:''}`;prepare(dialog);OrbitMotion.showDialog(dialog);return dialog}
 function confirmAction(title,message,action,label='Archive'){openLayer({title,body:`<p class="layer-description">${h(message)}</p>`,kind:'confirmation',footer:button('Cancel','data-close','ghost')+button(label,'data-layer-confirm','danger'),action})}
 function openRecord(row,kind='projects'){const member=kind==='members';openLayer({title:member?'Member details':'Project details',kind:'drawer',body:`<form data-record-form data-id="${row.id}" data-kind="${kind}">${field(member?'Full name':'Project name',`<input name="name" required maxlength="80" value="${h(row.name)}">`)}${field(member?'Email address':'Description',member?`<input type="email" name="detail" required value="${h(row.detail)}">`:`<textarea name="detail" rows="3" maxlength="300">${h(row.detail)}</textarea>`)}${member?`<fieldset class="role-choices"><legend>Role</legend>${['Member','Admin','Owner'].map(x=>`<label class="choice"><input type="radio" name="role" value="${x}" ${row.updated===x?'checked':''}>${x}</label>`).join('')}</fieldset>`:`<dl class="metadata-list"><div><dt>Owner</dt><dd>${h(row.owner)}</dd></div><div><dt>Status</dt><dd>${badge(row.status,row.status==='Active'?'green':'purple')}</dd></div></dl>`}<p class="form-error" role="alert" hidden></p><div class="drawer-note">${icon('info')} Edits are saved to this local preview.</div><div class="form-actions">${button('Cancel','data-close','ghost')}<button type="submit" class="button primary">Save changes</button></div></form>`})}
 function createRecord(member=false){openLayer({title:member?'Invite a teammate':'Create a project',body:`<form data-create-form data-kind="${member?'members':'projects'}">${field(member?'Full name':'Project name','<input name="name" required maxlength="80" placeholder="'+(member?'Jamie Chen':'A new idea')+'">')}${field(member?'Email address':'Description',member?'<input type="email" name="detail" required placeholder="jamie@studio.com">':'<input name="detail" placeholder="What are you working on?" maxlength="300">')}${member?'<p class="hint">A local preview invitation. No email is sent.</p>':''}<p class="form-error" role="alert" hidden></p><div class="form-actions">${button('Cancel','data-close','ghost')}<button class="button primary" type="submit">${member?'Add invitation':'Create project'}</button></div></form>`})}
 function openCommand(){openLayer({title:'Find your way',kind:'command-layer',body:`<label class="command-search">${icon('search')}<input type="search" data-command-search placeholder="Search screens and components…" aria-label="Search commands" autocomplete="off" role="combobox" aria-expanded="true" aria-controls="command-results" aria-autocomplete="list"><kbd>esc</kbd></label><div id="command-results" role="listbox" aria-label="Commands"></div><p class="hint">↑ ↓ to move · Enter to open</p>`});renderCommands('');layer().querySelector('input').focus()}
 let commands=[],commandIndex=0;
 function renderCommands(term){const source=[...['settings','team','projects','onboarding'].map(name=>({name:{settings:'Account settings',team:'Team management',projects:'Project workspace',onboarding:'Sign-in & onboarding'}[name],screen:name})),...components.map(c=>({name:c.name,component:c.name}))];commands=source.filter(x=>x.name.toLowerCase().includes(term.toLowerCase())).slice(0,9);commandIndex=0;document.querySelector('#command-results').innerHTML=commands.length?commands.map((c,i)=>`<button type="button" role="option" aria-selected="${!i}" tabindex="-1" id="command-${i}" data-command-index="${i}">${icon(c.screen?'layout':'grid')}<span>${h(c.name)}<small>${c.screen?'Screen':'Component'}</small></span>${icon('arrow')}</button>`).join(''):'<div class="combo-no-results">No matches. Try “settings” or “table”.</div>';layer().querySelector('input').setAttribute('aria-activedescendant',commands.length?'command-0':'')}
 function runCommand(index){const command=commands[index];if(!command)return;OrbitMotion.closeDialog(layer());setTimeout(()=>{if(command.screen){setView('screens');showScreen(command.screen)}else{setView('gallery');query=command.component;document.querySelector('#search').value=query;renderGallery();document.querySelector('#search').focus()}},160)}
 const dateFrom=s=>{const [y,m,d]=s.split('-').map(Number);return new Date(y,m-1,d,12)};
 const iso=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
 const shortDate=s=>dateFrom(s).toLocaleDateString('en-US',{month:'short',day:'numeric'});
 let rangeState=null;
 function openRange(trigger){rangeState={trigger,start:trigger.dataset.start,end:trigger.dataset.end,month:trigger.dataset.start,phase:'start'};openLayer({title:'Choose a date range',kind:'range-layer',body:'<div id="range-body"></div>',footer:button('Cancel','data-close','ghost')+button('Apply range','data-range-apply','primary')});renderRange()}
 function rangeMonth(date){const y=date.getFullYear(),m=date.getMonth(),offset=(new Date(y,m,1).getDay()+6)%7,count=new Date(y,m+1,0).getDate();return `<section class="range-month"><h3>${date.toLocaleDateString('en-US',{month:'long',year:'numeric'})}</h3><div class="calendar-week" aria-hidden="true">${['M','T','W','T','F','S','S'].map(x=>`<span>${x}</span>`).join('')}</div><div class="range-days" role="grid" aria-label="${date.toLocaleDateString('en-US',{month:'long',year:'numeric'})}">${Array.from({length:Math.ceil((offset+count)/7)},(_,week)=>`<div role="row">${Array.from({length:7},(_,day)=>{const n=week*7+day-offset+1;if(n<1||n>count)return '<span role="gridcell"></span>';const s=iso(new Date(y,m,n,12)),inRange=rangeState.start&&rangeState.end&&s>=rangeState.start&&s<=rangeState.end,edge=s===rangeState.start||s===rangeState.end;return `<span role="gridcell" aria-selected="${!!inRange}" class="${inRange?'in-range':''}"><button type="button" data-range-day="${s}" class="${edge?'range-edge':''}" tabindex="${s===rangeState.start?0:-1}" aria-label="${dateFrom(s).toLocaleDateString('en-US',{month:'long',day:'numeric',year:'numeric'})}">${n}</button></span>`}).join('')}</div>`).join('')}</div></section>`}
 function renderRange(focus){const current=dateFrom(rangeState.month);current.setDate(1);const next=new Date(current.getFullYear(),current.getMonth()+1,1,12);document.querySelector('#range-body').innerHTML=`<div class="range-presets">${button('Last 7 days','data-range-preset="7"','small')}${button('Last 30 days','data-range-preset="30"','small')}<div class="row">${button(icon('chevron'),'data-range-month="-1" aria-label="Previous range month"','small previous-results')}${button(icon('chevron'),'data-range-month="1" aria-label="Next range month"','small')}</div></div><p class="hint" role="status">${rangeState.phase==='end'?'Choose the end date.':'Choose a start date, then an end date.'}</p><div class="range-calendars">${rangeMonth(current)}${rangeMonth(next)}</div><div class="range-summary">${rangeState.start?shortDate(rangeState.start):'Start date'} <span>–</span> ${rangeState.end?shortDate(rangeState.end):'End date'}</div>`;layer().querySelector('[data-range-apply]').disabled=!rangeState.end;if(!layer().querySelector('[data-range-day][tabindex="0"]'))layer().querySelector('[data-range-day]').tabIndex=0;if(focus)layer().querySelector(`[data-range-day="${focus}"]`)?.focus()}
 function openTime(trigger){const [hour,minute]=trigger.dataset.time.split(':');openLayer({title:'Choose a time',kind:'time-layer',body:`<form data-time-form><div class="time-fields">${stepper('Hours',Number(hour),0,23)}<span>:</span>${stepper('Minutes',Number(minute),0,59)}</div><p class="hint">24-hour format · local time</p><div class="form-actions">${button('Cancel','data-close','ghost')}<button class="button primary" type="submit">Apply time</button></div></form>`});layer().querySelector('form')._timeTrigger=trigger}

 const screenMeta={settings:['Account settings','A few details that make this space yours.'],team:['Good people. Shared ideas.','Manage your team and make room for someone new.'],projects:['A place for work in progress.','Every project, a little closer to the finish.'],onboarding:['Welcome to your next idea.','Sign in and make yourself at home.']};
 function shellScreen(content,name){return `<div class="product-shell" data-product-shell><aside class="product-sidebar"><div class="product-wordmark"><span class="brand-mark"></span><span>Orbit Studio</span></div><button type="button" class="icon-button shell-collapse" data-shell-collapse aria-label="Collapse product sidebar" aria-expanded="true">${icon('layout')}</button><nav aria-label="Product navigation">${[['projects','folder','Projects'],['team','smile','People'],['settings','settings','Settings']].map(([key,ic,label])=>`<button type="button" data-screen="${key}" class="${key===name?'active':''}" ${key===name?'aria-current="page"':''}>${icon(ic)}<span>${label}</span>${key==='team'?`<small>${members.length}</small>`:''}</button>`).join('')}</nav><div class="product-user"><span class="avatar blue tiny"></span><span>${h(profile.name)}<small>Personal workspace</small></span></div></aside><div class="product-main"><div class="product-topbar"><button class="icon-button product-menu-button" type="button" data-product-menu aria-label="Open product navigation" aria-expanded="false">${icon('list')}</button><nav class="breadcrumbs" aria-label="Screen breadcrumb"><span>Workspace</span>${icon('chevron')}<span aria-current="page">${{settings:'Settings',team:'People',projects:'Projects'}[name]}</span></nav><button class="product-command" type="button" data-open-command>${icon('search')}<span>Search anything</span><kbd>⌘ K</kbd></button></div>${content}<div class="product-foot"><span class="status-dot"></span> All systems operational <span>Local interactive preview</span></div></div></div>`}
 function settingsScreen(){return shellScreen(`<div class="product-heading"><div><h2>Your space, your way.</h2><p>Manage your profile and the details that matter.</p></div><span class="avatar blue"></span></div><form class="settings-form" data-settings-form novalidate><section class="settings-section"><div><h3>Profile</h3><p>How you appear to your teammates.</p></div><div class="settings-fields">${field('Full name',`<input name="name" value="${h(profile.name)}" required maxlength="80" autocomplete="name">`)}${field('Email address',`<input type="email" name="email" value="${h(profile.email)}" required autocomplete="email">`)}${field('About you',`<textarea name="bio" rows="3" maxlength="240">${h(profile.bio)}</textarea>`,'A line or two is plenty.')}</div></section><section class="settings-section"><div><h3>Notifications</h3><p>A little less noise.</p></div><div class="settings-fields"><div class="switch-row"><div>Weekly digest<p>A short recap of your workspace.</p></div><label class="switch"><input type="checkbox" name="digest" role="switch" aria-label="Weekly digest" ${profile.digest?'checked':''}><span></span></label></div><div class="switch-row"><div>Product updates<p>Useful things, as we build them.</p></div><label class="switch"><input type="checkbox" name="updates" role="switch" aria-label="Product updates" ${profile.updates?'checked':''}><span></span></label></div></div></section><p class="form-error" role="alert" hidden></p><div class="settings-savebar" hidden><span>You have unsaved changes</span><div class="row">${button('Discard','data-settings-discard','ghost small')}<button type="submit" class="button primary small">Save changes</button></div></div></form><section class="settings-section security-section"><div><h3>Security</h3><p>Keep your account yours.</p></div><div class="settings-fields"><div class="row spread"><div><h3>Password</h3><p class="hint">Update your sign-in password.</p></div>${button('Change password','data-change-password','small')}</div></div></section>`, 'settings')}
 function teamScreen(){return shellScreen(`<div class="product-heading"><div><h2>Your people.</h2><p>A little more company. A lot more possibility.</p></div>${button(icon('plus')+' Invite member','data-invite-member','primary')}</div><div class="team-summary"><div class="avatars"><span class="avatar"></span><span class="avatar blue"></span><span class="avatar mint"></span><span class="avatar-count">+${Math.max(0,members.length-3)}</span></div><span><strong>${members.length} teammates</strong><small>One shared workspace</small></span><span class="badge purple">Studio plan</span></div><div class="product-table-wrap">${table('members')}</div>`, 'team')}
 function projectsScreen(){return shellScreen(`<div class="product-heading"><div><h2>Work in good company.</h2><p>A home for everything you’re making.</p></div>${button(icon('plus')+' New project','data-create-record','primary')}</div><div class="project-overview"><div><span>In progress</span><strong>${projects.filter(x=>x.status==='Active').length}</strong></div><div><span>Ready for review</span><strong>${projects.filter(x=>x.status==='Review').length}</strong></div><div><span>Archived</span><strong>${projects.filter(x=>x.status==='Archived').length}</strong></div><div class="overview-note">${icon('circlecheck')}<span>A little progress,<br>every day.</span></div></div><div class="product-table-wrap">${table('projects')}</div>`, 'projects')}
 function authScreen(){let content='';if(onboardStep===0)content=`<span class="brand-mark"></span><h2>Good to see you.</h2><p>Sign in to your workspace.</p><form data-auth-form novalidate>${field('Email address','<input type="email" name="email" autocomplete="email" placeholder="you@studio.com" required>')}${password('Password','password')}<p class="form-error" role="alert" hidden></p><button class="button primary" type="submit">Continue ${icon('arrow')}</button></form><span class="auth-note">Demo sign-in · use any email and 8-character password.</span>`;
 else if(onboardStep===1)content=`<div class="onboard-progress"><span class="current"></span><span></span><span></span></div><h2>Make it your own.</h2><p>Start with a name for your workspace.</p><form data-onboard-workspace>${field('Workspace name',`<input name="workspace" required maxlength="60" value="${h(onboard.workspace)}" placeholder="Your studio">`)}${selectable('onboard-plan')}<div class="form-actions">${button('Back','data-onboard-back','ghost')}<button class="button primary" type="submit">Continue ${icon('arrow')}</button></div></form>`;
 else if(onboardStep===2)content=`<div class="onboard-progress"><span class="done"></span><span class="current"></span><span></span></div><h2>What brings you here?</h2><p>Give your workspace a starting point.</p><form data-onboard-purpose><fieldset class="purpose-options"><legend class="sr-only">Workspace purpose</legend>${['Product','Design','Research'].map((x,i)=>`<label class="choice"><input type="radio" name="purpose" value="${x}" ${onboard.purpose===x?'checked':''}>${icon(['layers','palette','search'][i])}${x}</label>`).join('')}</fieldset><div class="form-actions">${button('Back','data-onboard-back','ghost')}<button class="button primary" type="submit">Create workspace ${icon('arrow')}</button></div></form>`;
 else content=`<div class="onboard-progress"><span class="done"></span><span class="done"></span><span class="done"></span></div><div class="onboard-success">${icon('circlecheck')}</div><h2>You’re right at home.</h2><p><strong>${h(onboard.workspace)}</strong> is ready for its first idea.</p>${button('Open workspace '+icon('arrow'),'data-screen="projects"','primary')}${button('Start again','data-auth-reset','ghost small')}`;
 return `<div class="auth-stage"><div class="auth-art" aria-hidden="true"><div class="orbit-shape"><span></span><span></span><span></span></div><p>A little space.<br>A lot of possibility.</p></div><div class="auth-card">${content}</div></div>`}
 function showScreen(name){currentScreen=name in screenMeta?name:'settings';const root=document.querySelector('#screens');root.innerHTML=`<div class="screens-heading"><div><h2>Whole screens. Shared building blocks.</h2><p>Working patterns for your next product.</p></div><span class="badge purple">4 starter screens</span></div><nav class="screen-picker" aria-label="Starter screens">${[['settings','settings','Account settings'],['team','smile','Team management'],['projects','folder','Project workspace'],['onboarding','lock','Sign-in & onboarding']].map(([key,ic,label])=>`<button type="button" data-screen="${key}" class="${key===currentScreen?'active':''}" aria-current="${key===currentScreen?'page':'false'}">${icon(ic)}${label}</button>`).join('')}</nav><div id="screen-stage">${{settings:settingsScreen,team:teamScreen,projects:projectsScreen,onboarding:authScreen}[currentScreen]()}</div>`;prepare(root);OrbitMotion.panel(document.querySelector('#screen-stage'));}
 function error(form,text,input){const target=form.querySelector('.form-error');if(target){target.hidden=false;target.textContent=text;if(!target.id)target.id=unique();if(input){input.setAttribute('aria-invalid','true');input.setAttribute('aria-describedby',target.id);input.focus()}}}
 function settingsValue(form){return {name:form.elements.name.value.trim(),email:form.elements.email.value.trim(),bio:form.elements.bio.value,digest:form.elements.digest.checked,updates:form.elements.updates.checked}}
 function settingsDirty(form){form.querySelector('.settings-savebar').hidden=JSON.stringify(settingsValue(form))===JSON.stringify(profile)}
 function refreshScreen(){if(view==='screens')showScreen(currentScreen)}
 function prepare(root=document){root.querySelectorAll('[data-starter-combo]').forEach(ensureCombo);root.querySelectorAll('[data-starter-table]').forEach(renderTable);root.querySelectorAll('.number-stepper').forEach(updateStepper);root.querySelectorAll('[data-unsaved-form]').forEach(form=>{if(!form.dataset.saved)form.dataset.saved=form.elements.workspace.value});root.querySelectorAll('[data-validation-form] input,[data-auth-form] input').forEach(input=>{if(!input.id)input.id=unique()});root.querySelectorAll('.selectable-cards').forEach(set=>{if(set.dataset.ready)return;set.dataset.ready='true';const inputs=set.querySelectorAll('input'),name=unique();inputs.forEach(input=>input.name=name)});}
 function updateStepper(root){const input=root.querySelector('input'),value=Number(input.value);root.querySelector('[data-number-step="-1"]').disabled=value<=Number(input.min);root.querySelector('[data-number-step="1"]').disabled=value>=Number(input.max)}
