/* Syntari starter patterns. Plain DOM components, local demo state, no service calls. */
(() => {
 const h=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const unique=()=>`syntari-${Math.random().toString(36).slice(2,10)}`;
 const button=(text,attrs='',cls='')=>`<button type="button" class="button ${cls}" ${attrs}>${text}</button>`;
 const field=(label,input,help='')=>`<label class="field"><span>${label}</span>${input}${help?`<span class="hint">${help}</span>`:''}</label>`;
 const projects=[
 {id:1,name:'Brand refresh',detail:'Identity, guidelines, and a fresh perspective.',status:'Active',updated:'2026-09-10',owner:'Jamie Chen'},
 {id:2,name:'Website exploration',detail:'A simpler way to tell our story.',status:'Active',updated:'2026-09-09',owner:'Alex Morgan'},
 {id:3,name:'Customer research',detail:'Conversations that shape the next release.',status:'Review',updated:'2026-09-08',owner:'Sam Rivera'},
 {id:4,name:'Mobile companion',detail:'The useful things, wherever you are.',status:'Active',updated:'2026-09-07',owner:'Jamie Chen'},
 {id:5,name:'Autumn campaign',detail:'Thoughtful touchpoints for a new season.',status:'Review',updated:'2026-09-06',owner:'Alex Morgan'},
 {id:6,name:'Design foundations',detail:'A shared language for the whole team.',status:'Archived',updated:'2026-09-05',owner:'Sam Rivera'},
 {id:7,name:'Help center',detail:'Clear answers, one search away.',status:'Active',updated:'2026-09-04',owner:'Jamie Chen'},
 {id:8,name:'Release notes',detail:'A little context for everything new.',status:'Archived',updated:'2026-09-03',owner:'Alex Morgan'}];
 const members=[
 {id:11,name:'Alex Morgan',detail:'alex@studio.example',status:'Active',updated:'Owner',owner:'Design'},
 {id:12,name:'Jamie Chen',detail:'jamie@studio.example',status:'Active',updated:'Admin',owner:'Product'},
 {id:13,name:'Sam Rivera',detail:'sam@studio.example',status:'Active',updated:'Member',owner:'Engineering'},
 {id:14,name:'Robin Park',detail:'robin@studio.example',status:'Invited',updated:'Member',owner:'Design'},
 {id:15,name:'Casey Lewis',detail:'casey@studio.example',status:'Active',updated:'Member',owner:'Product'},
 {id:16,name:'Taylor Reed',detail:'taylor@studio.example',status:'Invited',updated:'Member',owner:'Operations'}];
 let profile={name:'Alex Morgan',email:'alex@studio.example',bio:'Making useful things with thoughtful people.',digest:true,updates:false};
 try{const saved=JSON.parse(localStorage.getItem('syntari-profile')||'null');if(saved&&typeof saved.name==='string'&&typeof saved.email==='string')profile={...profile,...saved}}catch{}
 let currentScreen='settings',onboardStep=0,onboard={email:'',workspace:'',purpose:'Product'},layerAction=null,layerAfterClose=null;
 const tableStates=new WeakMap(),comboStates=new WeakMap(),uploadJobs=new WeakMap();
 const tableRoots=new Set();
 const combo=(label,options,mode='single',placeholder='Search or choose…')=>`<div class="field combo-field" data-starter-combo data-mode="${mode}" data-options="${h(JSON.stringify(options))}"><label>${label}</label><div class="combo-input">${icon('search')}<input type="text" role="combobox" aria-label="${label}" aria-expanded="false" aria-autocomplete="list" autocomplete="off" placeholder="${placeholder}"><button type="button" class="combo-clear" aria-label="Clear ${label}" data-combo-clear>${icon('x')}</button></div><div class="starter-options" role="listbox" aria-label="${label} options" hidden></div>${mode==='multiple'?'<div class="row combo-chips" aria-label="Selected values"></div>':''}<span class="sr-only" role="status"></span></div>`;
 const stepper=(label='Seats',value=3,min=1,max=20)=>`<div class="field"><label>${label}</label><div class="number-stepper"><button type="button" aria-label="Decrease ${label}" data-number-step="-1">${icon('minus' in paths?'minus':'x')}</button><input type="number" inputmode="numeric" min="${min}" max="${max}" value="${value}" aria-label="${label}"><button type="button" aria-label="Increase ${label}" data-number-step="1">${icon('plus')}</button></div><span class="hint">${min}–${max} ${label.toLowerCase()}</span></div>`;
 const password=(label='Password',name='password')=>`<label class="field">${label}<span class="password-control"><input type="password" name="${name}" minlength="8" required autocomplete="new-password" placeholder="At least 8 characters"><button type="button" data-password-toggle aria-label="Show ${label.toLowerCase()}" aria-pressed="false">${icon('eye' in paths?'eye':'lock')}</button></span></label>`;
 const selectable=(name='plan')=>`<fieldset class="selectable-cards"><legend>Choose your workspace</legend>${[['Personal','A space for your own ideas.','smile'],['Team','Bring a few good people.','layers']].map(([title,copy,ic],i)=>`<label><input type="radio" name="${name}" value="${title}" ${!i?'checked':''}><span>${icon(ic)}<strong>${title}</strong><small>${copy}</small><span class="selection-check">${icon('check')}</span></span></label>`).join('')}</fieldset>`;
 const table=(kind='projects')=>`<section class="data-table" data-starter-table data-kind="${kind}"><div class="data-table-toolbar"><label class="search table-search">${icon('search')}<input type="search" aria-label="Search ${kind}" placeholder="Search ${kind}…"></label><div class="row"><div class="record-actions"><button type="button" class="button small" data-table-status data-popover-toggle aria-expanded="false">All statuses ${icon('down')}</button><div class="starter-popover-panel dropdown-panel" hidden>${(kind==='members'?['All statuses','Active','Invited','Archived']:['All statuses','Active','Review','Archived']).map(status=>button(status,`data-table-filter="${status}"`,'ghost small')).join('')}</div></div><details class="column-picker"><summary>${icon('sliders')} Columns</summary><div>${['status','updated'].map(k=>`<label class="choice"><input type="checkbox" checked data-table-column="${k}">${k==='updated'?(kind==='members'?'Role':'Updated'):'Status'}</label>`).join('')}</div></details></div></div><div data-table-selection class="table-selection" hidden><span role="status"></span>${button('Archive selected','data-table-bulk','small')}</div><div class="table-scroll" data-table-grid></div><div class="table-foot"><span data-table-count role="status"></span><div class="row">${button(icon('chevron'),'data-table-page="-1" aria-label="Previous results"','small previous-results')}<span data-table-page-label></span>${button(icon('chevron'),'data-table-page="1" aria-label="Next results"','small')}</div></div></section>`;
 const simpleTable=()=>{
  const budgets=[4200,7800,2400,5600,3100],progress=[72,38,100,54,16];
  return `<section class="simple-table" data-simple-table aria-label="Project overview"><div class="simple-table-heading"><h3>Projects</h3><span class="hint">5 projects</span></div><div class="table-scroll" tabindex="0" role="region" aria-label="Sortable projects"><table><caption class="sr-only">Projects with owner, status, progress, budget, and update date. Select a column heading to sort.</caption><thead><tr>${[['name','Project'],['status','Status'],['progress','Progress'],['budget','Budget'],['updated','Updated']].map(([key,label])=>`<th scope="col" aria-sort="none"><button type="button" data-simple-sort="${key}">${label}${icon('down')}</button></th>`).join('')}<th scope="col"><span class="sr-only">Details</span></th></tr></thead><tbody>${projects.slice(0,5).map((r,i)=>`<tr data-name="${h(r.name)}" data-status="${r.status}" data-progress="${progress[i]}" data-budget="${budgets[i]}" data-updated="${r.updated}"><th scope="row"><span class="simple-project"><span class="avatar tiny ${['blue','mint',''][i%3]}" aria-hidden="true"></span><span>${h(r.name)}<small>${h(r.owner)}</small></span></span></th><td>${badge(r.status,r.status==='Active'?'green':'accent')}</td><td><span class="simple-progress"><span class="simple-progress-track" aria-hidden="true"><span style="width:${progress[i]}%"></span></span><span>${progress[i]}%</span></span></td><td class="simple-budget">$${budgets[i].toLocaleString('en-US')}</td><td><time datetime="${r.updated}">Sep ${Number(r.updated.slice(-2))}</time></td><td><button type="button" class="icon-button" data-simple-open="${r.id}" aria-label="Open ${h(r.name)}">${icon('arrow')}</button></td></tr>`).join('')}</tbody></table></div><p class="sr-only" role="status" data-simple-status></p></section>`;
 };
 const thumb=(color='lavender',label='Brand exploration')=>`<button type="button" class="asset-thumbnail ${color}" data-lightbox="${h(label)}" aria-label="Preview ${h(label)}"><span class="asset-art" aria-hidden="true"><span></span><span></span><span></span></span><span class="thumbnail-caption">${h(label)} ${icon('external')}</span></button>`;
 const dateRange=()=>`<div class="field"><span>Reporting period</span><button type="button" class="control-trigger" data-date-range data-start="2026-09-04" data-end="2026-09-10"><span>Sep 4 – Sep 10, 2026</span>${icon('calendar')}</button><span class="hint">Choose a start and end date.</span></div>`;
 const timePicker=()=>`<div class="field"><span>Meeting time</span><button type="button" class="control-trigger" data-time-picker data-time="09:30"><span>09:30</span>${icon('clock' in paths?'clock':'gauge')}</button><span class="hint">Your local time</span></div>`;
 const timeWheel=(label,name,value,max)=>`<div class="time-wheel-field"><span>${label}</span><div class="time-wheel" role="listbox" aria-label="${label}" tabindex="0" data-time-wheel="${name}" aria-activedescendant="time-${name}-${value}">${Array.from({length:max+1},(_,number)=>`<button type="button" role="option" id="time-${name}-${number}" data-time-option="${number}" aria-selected="${number===value}" tabindex="-1">${String(number).padStart(2,'0')}</button>`).join('')}</div><input type="hidden" name="${name}" value="${value}"></div>`;
 const metadata=()=>`<dl class="metadata-list"><div><dt>Owner</dt><dd><span class="avatar tiny blue"></span> Jamie Chen</dd></div><div><dt>Status</dt><dd>${badge('Active','green')}</dd></div><div><dt>Created</dt><dd>September 4, 2026</dd></div><div><dt>Visibility</dt><dd>${icon('lock')} Team only</dd></div></dl>`;
 const validation=()=>`<form class="validation-demo" data-validation-form novalidate>${field('Work email','<input type="email" name="email" placeholder="you@studio.com" required>')}<p class="form-error" role="alert" hidden></p><button class="button primary" type="submit">Continue ${icon('arrow')}</button><p class="hint">Try an incomplete email to see validation.</p></form>`;
 const upload=()=>`<div class="upload-demo"><div class="row"><span class="empty-icon">${icon('upload')}</span><div><h3>Workspace assets</h3><p class="hint">Simulated upload · no file is sent</p></div></div><div class="progress" role="progressbar" aria-label="Demo upload" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0"><span style="width:0%"></span></div><div class="row spread"><span data-upload-label role="status">Ready to upload</span><div class="row">${button('Start upload','data-upload-start','small')}${button('Cancel','data-upload-cancel disabled hidden','small secondary')}</div></div></div>`;
 const unsaved=()=>`<form class="unsaved-demo" data-unsaved-form>${field('Workspace name','<input name="workspace" value="Syntari Studio" required maxlength="60">')}<div class="unsaved-bar" hidden><span>Unsaved changes</span><div class="row">${button('Discard','data-discard-draft','small secondary')}<button class="button primary small" type="submit">Save</button></div></div><p class="hint" data-saved-label>Edit the name to preview the save bar.</p></form>`;
 const pageHeader=()=>`<div class="sample-page-header"><nav class="breadcrumbs" aria-label="Breadcrumb"><a href="#workspace" data-breadcrumb="Workspace">Workspace</a>${icon('chevron')}<span aria-current="page">Projects</span></nav><div class="row spread"><div><h2>Projects</h2><p>Room for your next idea.</p></div>${button(icon('plus')+' New project','data-create-record','small primary')}</div></div>`;
 const navigationItems=()=>[['projects','folder','Projects'],['team','smile','People'],['settings','settings','Settings']].map(([key,icon,label])=>({key,icon,label,href:`gallery.html?view=screens&screen=${key}`,...(key==='team'?{count:members.length}:{})}));
 let navigationPreference={layout:'sidebar',collapsed:false};
 try{const saved=JSON.parse(localStorage.getItem('syntari-navigation')||'null');if(saved&&['sidebar','topbar'].includes(saved.layout))navigationPreference={layout:saved.layout,collapsed:['true','expanded'].includes(saved.collapsed)?saved.collapsed:false}}catch{}
 const miniContent=(key='projects')=>`<div class="syntari-mini-content"><h3 data-mini-heading>${{projects:'Projects',team:'People',settings:'Settings'}[key]}</h3><p data-mini-copy>${{projects:'Everything you’re working on, together.',team:'A shared space for good people and new ideas.',settings:'The details that make this workspace yours.'}[key]}</p>${key==='projects'?`<div class="syntari-mini-stats"><div><small>In progress</small><strong>4</strong></div><div><small>In review</small><strong>2</strong></div></div>${projects.slice(0,2).map(row=>`<div class="syntari-mini-row"><span class="avatar tiny blue" aria-hidden="true"></span><span>${h(row.name)}</span>${badge(row.status,'green')}</div>`).join('')}`:key==='team'?members.slice(0,3).map(row=>`<div class="syntari-mini-row"><span class="avatar tiny blue" aria-hidden="true"></span><span>${h(row.name)}</span>${badge(row.updated)}</div>`).join(''):`<dl class="metadata-list"><div><dt>Workspace</dt><dd>Syntari Studio</dd></div><div><dt>Visibility</dt><dd>${icon('lock')} Team only</dd></div><div><dt>Plan</dt><dd>Personal</dd></div></dl>`}</div>`;
 const shell=()=>window.SyntariNavigation.render({content:miniContent(),items:navigationItems(),active:'projects',pinned:projects.slice(0,2),compact:true});

 function register(){
  add('App shell','Layout','Sidebar / topbar / mobile','One navigation system with sidebar and topbar layouts, a collapsible rail, and a keyboard-accessible mobile drawer. Starter screens use the same component.',shell());
  add('Page header & breadcrumbs','Navigation','Context / actions','A page title, supporting description, breadcrumb trail, and primary action share a reusable alignment.',pageHeader());
  add('Side drawer','Overlay','Details / editing','Inspect and edit a record without losing your place. Native modal semantics keep keyboard focus inside until dismissed.',`<div class="empty-icon">${icon('layout')}</div>${button('Open project details '+icon('arrow'),'data-open-drawer')}<span class="label-caption">A little more context, close by.</span>`);
  add('Bottom sheet','Overlay','Mobile / desktop','A compact action surface rises from the bottom, with Escape and backdrop dismissal.',`<div class="empty-icon">${icon('layers')}</div>${button('Share workspace','data-open-sheet')}<span class="label-caption">Actions within reach.</span>`);
  add('Popover','Overlay','Contextual controls','Small controls appear next to their trigger and dismiss on outside click or Escape.',`<div class="starter-popover"><button type="button" class="button" data-popover-toggle aria-expanded="false">${icon('bell')} Notification preferences</button><div class="starter-popover-panel" hidden><h3>Keep me in the loop</h3><label class="choice"><input type="checkbox" checked>Mentions and replies</label><label class="choice"><input type="checkbox">Weekly summary</label><p class="hint">Changes apply to this preview.</p></div></div>`);
  add('Confirmation dialog','Overlay','Destructive / cancel','Confirm a consequential action with a clear description, safe cancel action, and explicit outcome.',`<div class="mini-card"><h3>Archive this project?</h3><p>You can restore it from archived projects.</p>${button('Archive project','data-demo-confirm','small danger')}</div>`);
  add('Searchable select','Form controls','Filter / keyboard','Search a list of options. Arrow keys move the active option; Enter commits and Escape dismisses.',combo('Assign to',['Alex Morgan','Jamie Chen','Sam Rivera','Robin Park','Casey Lewis']));
  add('Autocomplete','Form controls','Suggestions / custom values','Suggestions narrow as you type. Choose an existing value or keep a custom value.',combo('Project name',['Brand refresh','Website exploration','Mobile companion','Customer research'],'free','Start typing a project…'));
  add('Multiselect','Form controls','Search / removable chips','Select several values from a searchable list. Remove selected chips without reopening the list.',combo('Project labels',['Design','Research','Engineering','Marketing','Operations'],'multiple','Find a label…'));
  add('Command palette','Overlay','Search / shortcuts','Find screens, components, and common actions with the keyboard. Open anywhere with Command/Ctrl K.',`${button(icon('search')+' Search or jump to… <kbd>⌘ K</kbd>','data-open-command')}<span class="label-caption">One place to find your way.</span>`);
  add('Number stepper','Form controls','Bounds / keyboard','Increment, decrement, or enter a number. Boundary buttons disable at the minimum and maximum.',stepper());
  add('Password field','Form controls','Reveal / concealed','Reveal a password without changing its value. The toggle exposes its pressed state and updates its label.',`<div class="stack">${password()}<p class="hint">Use at least 8 characters.</p></div>`);
  add('Date range picker','Form controls','Range / presets','Choose two dates across months, or use a quick preset. Apply commits the selection; cancel preserves the original value.',dateRange());
  add('Time picker','Form controls','Wheel / keyboard','A tactile hour-and-minute wheel with momentum scrolling, keyboard control, and explicit confirmation.',timePicker());
  add('Selectable cards','Form controls','Single selection','A richer radio option combines a title, description, and Lucide icon. Native radio semantics preserve keyboard behavior.',selectable());
  add('Simple data table','Table & list','Sort / mixed cells','A quiet table with one record per line. Sort project names, status, progress, currency, and dates without extra toolbars or bulk controls.',simpleTable());
  add('Data table','Table & list','Sort / filter / bulk actions','Sort, search, filter, hide columns, select rows, paginate, expand details, and edit records. Actions update local preview data.',table());
  add('Inline validation','Feedback & status','Invalid / success','Associated inline errors explain how to correct an invalid field. Valid input replaces the error with confirmation.',validation());
  add('Error & retry','Feedback & status','Error / loading / recovered','Recover from a failed load without losing context. Retry shows a loading state before replacing the error.',`<div class="retry-demo"><div class="empty-icon">${icon('info')}</div><h3>Couldn’t load your projects</h3><p>Try again to pick up where you left off.</p>${button('Try again','data-retry')}</div>`);
  add('Upload progress','Feedback & status','Progress / cancel / complete','A bounded progress simulation with cancel and retry. Screen-reader updates announce milestones, not every frame.',upload());
  add('Unsaved changes','Feedback & status','Edit / save / discard','A contextual save bar appears when values differ from the saved version. Discard restores the original.',unsaved());
  add('Metadata list','Content','Labels / values','Aligned labels and values display the details that accompany a record.',metadata());
  add('Thumbnail & lightbox','Content','Preview / zoom','Local abstract artwork demonstrates an asset thumbnail and larger lightbox preview. Escape returns focus to the thumbnail.',`<div class="thumbnail-pair">${thumb()}${thumb('mint','Color studies')}</div>`);
  add('Divider & form section','Layout','Grouped fields','A titled section and quiet divider separate related fields without adding another card.',`<div class="form-section-demo"><div><h3>Workspace details</h3><p>The basics, in one place.</p></div>${field('Name','<input value="Syntari Studio">')}<hr class="ds-divider"><div class="row spread"><span>Private workspace</span><label class="switch"><input type="checkbox" role="switch" aria-label="Private workspace" checked><span></span></label></div></div>`);
 }

 function position(panel,trigger){SyntariMotion.settleAncestors(panel);const r=trigger.getBoundingClientRect(),w=Math.min(Number(panel.dataset.width)||Math.max(240,r.width),innerWidth-24);panel.style.width=`${w}px`;panel.style.left=`${Math.max(12,Math.min(r.left,innerWidth-w-12))}px`;panel.style.top=`${r.bottom+6}px`;const height=panel.getBoundingClientRect().height;if(r.bottom+height+8>innerHeight&&r.top-height-6>10)panel.style.top=`${r.top-height-6}px`;}
 function closeFloating(restore=false){document.querySelectorAll('.starter-options:not([hidden]),.starter-popover-panel:not([hidden]),.row-action-menu:not([hidden])').forEach(panel=>{const trigger=panel.parentElement.querySelector('[role=combobox],[data-popover-toggle],[data-row-actions]');if(trigger)trigger.setAttribute('aria-expanded','false');SyntariMotion.visibility(panel,false);if(restore)trigger?.focus()})}
 function ensureCombo(root){if(comboStates.has(root))return comboStates.get(root);const input=root.querySelector('input'),list=root.querySelector('[role=listbox]'),label=root.querySelector('label'),id=unique();input.id=id;label.htmlFor=id;list.id=id+'-options';input.setAttribute('aria-controls',list.id);if(root.dataset.mode==='multiple')list.setAttribute('aria-multiselectable','true');const state={options:JSON.parse(root.dataset.options),selected:[],active:-1,filtered:[]};comboStates.set(root,state);return state}
 function renderCombo(root,open=true){const s=ensureCombo(root),input=root.querySelector('input'),list=root.querySelector('[role=listbox]'),term=input.value.toLowerCase();s.filtered=s.options.filter(x=>x.toLowerCase().includes(term));if(root.dataset.mode==='free'&&input.value.trim()&&!s.filtered.includes(input.value.trim()))s.filtered.push(input.value.trim());s.active=Math.min(s.active,s.filtered.length-1);list.innerHTML=s.filtered.length?s.filtered.map((x,i)=>`<button type="button" role="option" tabindex="-1" id="${list.id}-${i}" aria-selected="${s.selected.includes(x)}" data-combo-option="${h(x)}" class="${s.active===i?'active':''}"><span>${h(x)}</span>${s.selected.includes(x)?icon('check'):''}</button>`).join(''):'<div class="combo-no-results">No matches. Try another search.</div>';if(s.active>=0)input.setAttribute('aria-activedescendant',`${list.id}-${s.active}`);else input.removeAttribute('aria-activedescendant');if(open){if(list.hidden||list.inert)SyntariMotion.visibility(list,true);list.hidden=false;list.inert=false;input.setAttribute('aria-expanded','true');position(list,root.querySelector('.combo-input'))}if(root.dataset.mode==='multiple')root.querySelector('.combo-chips').innerHTML=s.selected.map(x=>`<span class="chip">${h(x)}<button type="button" data-combo-remove="${h(x)}" aria-label="Remove ${h(x)}">${icon('x')}</button></span>`).join('');root.querySelector('.combo-clear').hidden=!input.value;}
 function chooseCombo(root,value){const s=ensureCombo(root),input=root.querySelector('input');if(root.dataset.mode==='multiple'){s.selected=s.selected.includes(value)?s.selected.filter(x=>x!==value):[...s.selected,value];input.value='';s.active=-1;renderCombo(root);input.focus()}else{s.selected=[value];input.value=value;renderCombo(root,false);closeFloating();input.focus();input.setAttribute('aria-expanded','false')}root.querySelector('[role=status]').textContent=root.dataset.mode==='multiple'?`${s.selected.length} selected`:value;}
 function sortSimple(root,key,descending=false){
  const heading=root.querySelector(`[data-simple-sort="${key}"]`);
  root.querySelectorAll('th[aria-sort]').forEach(th=>th.setAttribute('aria-sort',th===heading.parentElement?(descending?'descending':'ascending'):'none'));
  const body=root.querySelector('tbody'),rows=[...body.children];
  rows.sort((a,z)=>{const av=a.dataset[key],zv=z.dataset[key],comparison=['progress','budget'].includes(key)?Number(av)-Number(zv):av.localeCompare(zv,'en',{numeric:true});return comparison*(descending?-1:1)});
  SyntariMotion.rearrange(body,()=>body.append(...rows));
  root.querySelector('[data-simple-status]').textContent=`Sorted by ${heading.textContent.trim()}, ${descending?'descending':'ascending'}.`;
 }
 function refreshTables(){
  for(const root of tableRoots){if(!root.isConnected){tableRoots.delete(root);continue}renderTable(root)}
  document.querySelectorAll('[data-simple-table]').forEach(root=>{
   root.querySelectorAll('tbody tr').forEach(tr=>{
    const button=tr.querySelector('[data-simple-open]'),record=projects.find(r=>r.id===Number(button.dataset.simpleOpen));if(!record)return;
    tr.dataset.name=record.name;tr.dataset.status=record.status;
    const label=tr.querySelector('.simple-project>span:last-child');label.replaceChildren(document.createTextNode(record.name));
    const owner=document.createElement('small');owner.textContent=record.owner;label.append(owner);
    button.setAttribute('aria-label','Open '+record.name);
    const mark=tr.querySelector('.badge');mark.textContent=record.status;mark.className='badge '+(record.status==='Active'?'green':record.status==='Archived'?'':'accent');
   });
   const active=root.querySelector('th[aria-sort]:not([aria-sort=none]) button');if(active)sortSimple(root,active.dataset.simpleSort,active.parentElement.getAttribute('aria-sort')==='descending');
  });
 }
 function ensureTable(root){if(tableStates.has(root))return tableStates.get(root);const state={query:'',status:'All statuses',sort:'name',direction:1,page:1,size:5,selected:new Set(),expanded:new Set(),columns:{status:true,updated:true}};tableStates.set(root,state);tableRoots.add(root);return state}
 function rowsFor(root){return root.dataset.kind==='members'?members:projects}
 function renderTable(root){const s=ensureTable(root),member=root.dataset.kind==='members',all=rowsFor(root);let rows=all.filter(r=>(s.status==='All statuses'||r.status===s.status)&&`${r.name} ${r.detail} ${r.owner}`.toLowerCase().includes(s.query.toLowerCase())).sort((a,b)=>String(a[s.sort]).localeCompare(String(b[s.sort]),'en',{numeric:true})*s.direction);const pages=Math.max(1,Math.ceil(rows.length/s.size));s.page=Math.min(s.page,pages);const visible=rows.slice((s.page-1)*s.size,s.page*s.size),colCount=3+Number(s.columns.status)+Number(s.columns.updated);
 root.querySelector('[data-table-grid]').innerHTML=`<table class="advanced-table"><caption class="sr-only">${member?'Team members':'Workspace projects'}</caption><thead><tr><th class="check-cell"><label class="choice"><input type="checkbox" data-table-all aria-label="Select all visible rows" ${!visible.length?'disabled':''}></label></th><th scope="col" aria-sort="${s.sort==='name'?(s.direction===1?'ascending':'descending'):'none'}"><button type="button" data-table-sort="name">${member?'Member':'Project'} ${icon('down')}</button></th>${s.columns.status?`<th scope="col" aria-sort="${s.sort==='status'?(s.direction===1?'ascending':'descending'):'none'}"><button type="button" data-table-sort="status">Status ${icon('down')}</button></th>`:''}${s.columns.updated?`<th scope="col" aria-sort="${s.sort==='updated'?(s.direction===1?'ascending':'descending'):'none'}"><button type="button" data-table-sort="updated">${member?'Role':'Updated'} ${icon('down')}</button></th>`:''}<th scope="col"><span class="sr-only">Actions</span></th></tr></thead><tbody>${visible.length?visible.map(r=>`<tr class="${s.selected.has(r.id)?'is-selected':''}"><td class="check-cell"><label class="choice"><input type="checkbox" data-table-select="${r.id}" aria-label="Select ${h(r.name)}" ${s.selected.has(r.id)?'checked':''}></label></td><th scope="row"><button type="button" class="record-name" data-table-expand="${r.id}" aria-expanded="${s.expanded.has(r.id)}">${icon('chevron')}<span>${h(r.name)}<small>${h(member?r.detail:r.owner)}</small></span></button></th>${s.columns.status?`<td>${badge(h(r.status),r.status==='Active'?'green':r.status==='Archived'?'':'accent')}</td>`:''}${s.columns.updated?`<td class="table-secondary">${h(member?r.updated:new Date(r.updated+'T12:00:00').toLocaleDateString('en-US',{month:'short',day:'numeric'}))}</td>`:''}<td><div class="record-actions"><button type="button" class="icon-button" data-row-actions aria-label="Actions for ${h(r.name)}" aria-expanded="false">${icon('more')}</button><div class="dropdown-panel row-action-menu" data-width="175" hidden><button type="button" data-record-edit="${r.id}">${icon('edit')} ${member?'Edit member':'Edit project'}</button><button type="button" data-record-archive="${r.id}">${icon('folder')} ${r.status==='Archived'?'Restore':'Archive'}</button></div></div></td></tr>${s.expanded.has(r.id)?`<tr class="expanded-record"><td colspan="${colCount}"><p>${h(r.detail)}</p><span>${member?'Team: '+h(r.owner):'Owner: '+h(r.owner)}</span>${button('Open details '+icon('arrow'),`data-record-edit="${r.id}"`,'small ghost')}</td></tr>`:''}`).join(''):`<tr><td colspan="${colCount}"><div class="table-empty">${icon('search')}<h3>No matching ${member?'members':'projects'}</h3><p>Try another name or clear the filters.</p>${button('Clear filters','data-table-reset','small')}</div></td></tr>`}</tbody></table>`;
 const allInput=root.querySelector('[data-table-all]');allInput.checked=visible.length>0&&visible.every(r=>s.selected.has(r.id));allInput.indeterminate=!allInput.checked&&visible.some(r=>s.selected.has(r.id));s.visible=visible.map(r=>r.id);const bar=root.querySelector('[data-table-selection]');bar.hidden=s.selected.size===0;bar.querySelector('span').textContent=`${s.selected.size} selected`;root.querySelector('[data-table-count]').textContent=rows.length?`${(s.page-1)*s.size+1}–${Math.min(s.page*s.size,rows.length)} of ${rows.length}`:'0 results';root.querySelector('[data-table-page-label]').textContent=`${s.page} / ${pages}`;root.querySelector('[data-table-page="-1"]').disabled=s.page===1;root.querySelector('[data-table-page="1"]').disabled=s.page===pages;
 }
 function layer(){return document.querySelector('#starter-dialog')}
 function openLayer({title,body,kind='',footer='',action=null,afterClose=null}){const dialog=layer();layerAction=action;layerAfterClose=afterClose;dialog.className=`starter-layer ${kind}`;dialog.innerHTML=`<div class="dialog-heading"><div><p class="muted">Syntari Studio</p><h2 id="starter-layer-title">${h(title)}</h2></div><button type="button" class="icon-button" data-close aria-label="Close ${h(title)}">${icon('x')}</button></div><div class="starter-layer-body">${body}</div>${footer?`<div class="dialog-footer">${footer}</div>`:''}`;prepare(dialog);SyntariMotion.showDialog(dialog);return dialog}
 function confirmAction(title,message,action,label='Archive'){openLayer({title,body:`<p class="layer-description">${h(message)}</p>`,kind:'confirmation',footer:button('Cancel','data-close','secondary')+button(label,'data-layer-confirm','danger'),action})}
 function openRecord(row,kind='projects'){const member=kind==='members';openLayer({title:member?'Member details':'Project details',kind:'drawer',body:`<form data-record-form data-id="${row.id}" data-kind="${kind}">${field(member?'Full name':'Project name',`<input name="name" required maxlength="80" value="${h(row.name)}">`)}${field(member?'Email address':'Description',member?`<input type="email" name="detail" required value="${h(row.detail)}">`:`<textarea name="detail" rows="3" maxlength="300">${h(row.detail)}</textarea>`)}${member?`<fieldset class="role-choices"><legend>Role</legend>${['Member','Admin','Owner'].map(x=>`<label class="choice"><input type="radio" name="role" value="${x}" ${row.updated===x?'checked':''}>${x}</label>`).join('')}</fieldset>`:`<dl class="metadata-list"><div><dt>Owner</dt><dd>${h(row.owner)}</dd></div><div><dt>Status</dt><dd>${badge(row.status,row.status==='Active'?'green':'accent')}</dd></div></dl>`}<p class="form-error" role="alert" hidden></p><div class="drawer-note">${icon('info')} Edits are saved to this local preview.</div><div class="form-actions">${button('Cancel','data-close','secondary')}<button type="submit" class="button primary">Save changes</button></div></form>`})}
 function createRecord(member=false){openLayer({title:member?'Invite a teammate':'Create a project',body:`<form data-create-form data-kind="${member?'members':'projects'}">${field(member?'Full name':'Project name','<input name="name" required maxlength="80" placeholder="'+(member?'Jamie Chen':'A new idea')+'">')}${field(member?'Email address':'Description',member?'<input type="email" name="detail" required placeholder="jamie@studio.com">':'<input name="detail" placeholder="What are you working on?" maxlength="300">')}${member?'<p class="hint">A local preview invitation. No email is sent.</p>':''}<p class="form-error" role="alert" hidden></p><div class="form-actions">${button('Cancel','data-close','secondary')}<button class="button primary" type="submit">${member?'Add invitation':'Create project'}</button></div></form>`})}
 function openCommand(){openLayer({title:'Search workspace',kind:'command-layer',body:`<label class="command-search">${icon('search')}<input type="search" data-command-search placeholder="Search screens and components…" aria-label="Search commands" autocomplete="off" role="combobox" aria-expanded="true" aria-controls="command-results" aria-autocomplete="list"><kbd>esc</kbd></label><div id="command-results" role="listbox" aria-label="Commands"></div><p class="hint">↑ ↓ to move · Enter to open</p>`});renderCommands('');layer().querySelector('input').focus()}
 let commands=[],commandIndex=0;
 function renderCommands(term){const source=[...['settings','team','projects','onboarding'].map(name=>({name:{settings:'Account settings',team:'Team management',projects:'Project workspace',onboarding:'Sign-in & onboarding'}[name],screen:name})),...components.map(c=>({name:c.name,component:c.name}))];commands=source.filter(x=>x.name.toLowerCase().includes(term.toLowerCase())).slice(0,9);commandIndex=0;document.querySelector('#command-results').innerHTML=commands.length?commands.map((c,i)=>`<button type="button" role="option" aria-selected="${!i}" tabindex="-1" id="command-${i}" data-command-index="${i}">${icon(c.screen?'layout':'grid')}<span>${h(c.name)}<small>${c.screen?'Screen':'Component'}</small></span>${icon('arrow')}</button>`).join(''):'<div class="combo-no-results">No matches. Try “settings” or “table”.</div>';layer().querySelector('input').setAttribute('aria-activedescendant',commands.length?'command-0':'')}
 function runCommand(index){const command=commands[index];if(!command)return;SyntariMotion.closeDialog(layer());setTimeout(()=>{if(command.screen){if(!window.SyntariEmbed)setView('screens');showScreen(command.screen)}else{if(window.SyntariEmbed){window.dispatchEvent(new CustomEvent('syntari:navigate',{detail:{component:command.component}}));return;}setView('gallery');query=command.component;document.querySelector('#search').value=query;renderGallery();document.querySelector('#search').focus()}},160)}
 const dateFrom=s=>{const [y,m,d]=s.split('-').map(Number);return new Date(y,m-1,d,12)};
 const iso=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
 const shortDate=s=>dateFrom(s).toLocaleDateString('en-US',{month:'short',day:'numeric'});
 let rangeState=null;
 function openRange(trigger){rangeState={trigger,start:trigger.dataset.start,end:trigger.dataset.end,month:trigger.dataset.start,phase:'start'};openLayer({title:'Choose a date range',kind:'range-layer',body:'<div id="range-body"></div>',footer:button('Cancel','data-close','secondary')+button('Apply range','data-range-apply','primary')});renderRange()}
 function rangeMonth(date){const y=date.getFullYear(),m=date.getMonth(),offset=(new Date(y,m,1).getDay()+6)%7,count=new Date(y,m+1,0).getDate();return `<section class="range-month"><h3>${date.toLocaleDateString('en-US',{month:'long',year:'numeric'})}</h3><div class="calendar-week" aria-hidden="true">${['M','T','W','T','F','S','S'].map(x=>`<span>${x}</span>`).join('')}</div><div class="range-days" role="grid" aria-label="${date.toLocaleDateString('en-US',{month:'long',year:'numeric'})}">${Array.from({length:Math.ceil((offset+count)/7)},(_,week)=>`<div role="row">${Array.from({length:7},(_,day)=>{const n=week*7+day-offset+1;if(n<1||n>count)return '<span role="gridcell"></span>';const s=iso(new Date(y,m,n,12)),inRange=rangeState.start&&rangeState.end&&s>=rangeState.start&&s<=rangeState.end,edge=s===rangeState.start||s===rangeState.end;return `<span role="gridcell" aria-selected="${!!inRange}" class="${inRange?'in-range':''}"><button type="button" data-range-day="${s}" class="${edge?'range-edge':''}" tabindex="${s===rangeState.start?0:-1}" aria-label="${dateFrom(s).toLocaleDateString('en-US',{month:'long',day:'numeric',year:'numeric'})}">${n}</button></span>`}).join('')}</div>`).join('')}</div></section>`}
 function renderRange(focus){const current=dateFrom(rangeState.month);current.setDate(1);const next=new Date(current.getFullYear(),current.getMonth()+1,1,12);document.querySelector('#range-body').innerHTML=`<div class="range-presets"><div class="row">${button(icon('chevron'),'data-range-month="-1" aria-label="Previous range month"','small previous-results')}${button(icon('chevron'),'data-range-month="1" aria-label="Next range month"','small')}</div></div><p class="hint" role="status">${rangeState.phase==='end'?'Choose the end date.':'Choose a start date, then an end date.'}</p><div class="range-calendars">${rangeMonth(current)}</div><div class="range-summary">${rangeState.start?shortDate(rangeState.start):'Start date'} <span>–</span> ${rangeState.end?shortDate(rangeState.end):'End date'}</div>`;layer().querySelector('[data-range-apply]').disabled=!rangeState.end;if(!layer().querySelector('[data-range-day][tabindex="0"]'))layer().querySelector('[data-range-day]').tabIndex=0;if(focus)layer().querySelector(`[data-range-day="${focus}"]`)?.focus()}
 function selectTimeWheel(wheel,value,scroll=true){const options=[...wheel.querySelectorAll('[data-time-option]')],next=options[Math.max(0,Math.min(options.length-1,Number(value)))];if(!next)return;clearTimeout(wheel._timeSettle);options.forEach(option=>option.setAttribute('aria-selected',String(option===next)));wheel.setAttribute('aria-activedescendant',next.id);wheel.nextElementSibling.value=next.dataset.timeOption;if(scroll){wheel.dataset.timeSnapping='true';clearTimeout(wheel._timeSnap);const top=next.offsetTop-(wheel.clientHeight-next.offsetHeight)/2;wheel.scrollTo({top,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});wheel._timeSnap=setTimeout(()=>delete wheel.dataset.timeSnapping,360)}}
 function prepareTimeWheels(form){form.querySelectorAll('[data-time-wheel]').forEach(wheel=>{const selectNearest=()=>{const center=wheel.getBoundingClientRect().top+wheel.clientHeight/2,options=[...wheel.querySelectorAll('[data-time-option]')],nearest=options.reduce((best,option)=>Math.abs(option.getBoundingClientRect().top+option.offsetHeight/2-center)<Math.abs(best.getBoundingClientRect().top+best.offsetHeight/2-center)?option:best);selectTimeWheel(wheel,nearest.dataset.timeOption,false)};wheel.addEventListener('scroll',()=>{if(wheel.dataset.timeSnapping)return;clearTimeout(wheel._timeSettle);wheel._timeSettle=setTimeout(selectNearest,80)},{passive:true});requestAnimationFrame(()=>{const selected=wheel.querySelector('[aria-selected="true"]');wheel.dataset.timeSnapping='true';wheel.scrollTop=selected.offsetTop-(wheel.clientHeight-selected.offsetHeight)/2;requestAnimationFrame(()=>delete wheel.dataset.timeSnapping)})})}
 function openTime(trigger){const [hour,minute]=trigger.dataset.time.split(':').map(Number),dialog=openLayer({title:'Choose a time',kind:'time-layer',body:`<form data-time-form><div class="time-wheel-picker">${timeWheel('Hours','hours',hour,23)}<span class="time-wheel-separator" aria-hidden="true">:</span>${timeWheel('Minutes','minutes',minute,59)}</div><p class="hint time-zone-note">24-hour format · local time</p><div class="form-actions">${button('Cancel','data-close','secondary')}<button class="button primary" type="submit">Apply time</button></div></form>`});const form=dialog.querySelector('[data-time-form]');form._timeTrigger=trigger;prepareTimeWheels(form);requestAnimationFrame(()=>form.querySelector('[data-time-wheel]').focus())}

 const screenMeta={settings:['Account settings','A few details that make this space yours.'],team:['Good people. Shared ideas.','Manage your team and make room for someone new.'],projects:['A place for work in progress.','Every project, a little closer to the finish.'],onboarding:['Welcome to your next idea.','Sign in and make yourself at home.']};
 function shellScreen(content,name){return window.SyntariNavigation.render({content:content+`<div class="product-foot"><span class="status-dot"></span> All systems operational <span>Local interactive preview</span></div>`,items:navigationItems(),active:name,pinned:projects.slice(0,2),account:profile.name,...navigationPreference})}
 function settingsScreen(){return shellScreen(`<div class="product-heading"><div><h2>Your space, your way.</h2><p>Manage your profile and the details that matter.</p></div><span class="avatar blue"></span></div><form class="settings-form" data-settings-form novalidate><section class="settings-section"><div><h3>Profile</h3><p>How you appear to your teammates.</p></div><div class="settings-fields">${field('Full name',`<input name="name" value="${h(profile.name)}" required maxlength="80" autocomplete="name">`)}${field('Email address',`<input type="email" name="email" value="${h(profile.email)}" required autocomplete="email">`)}${field('About you',`<textarea name="bio" rows="3" maxlength="240">${h(profile.bio)}</textarea>`,'A line or two is plenty.')}</div></section><section class="settings-section"><div><h3>Notifications</h3><p>A little less noise.</p></div><div class="settings-fields"><div class="switch-row"><div>Weekly digest<p>A short recap of your workspace.</p></div><label class="switch"><input type="checkbox" name="digest" role="switch" aria-label="Weekly digest" ${profile.digest?'checked':''}><span></span></label></div><div class="switch-row"><div>Product updates<p>Useful things, as we build them.</p></div><label class="switch"><input type="checkbox" name="updates" role="switch" aria-label="Product updates" ${profile.updates?'checked':''}><span></span></label></div></div></section><p class="form-error" role="alert" hidden></p><div class="settings-savebar" hidden><span>You have unsaved changes</span><div class="row">${button('Discard','data-settings-discard','ghost small')}<button type="submit" class="button primary small">Save changes</button></div></div></form><section class="settings-section security-section"><div><h3>Security</h3><p>Keep your account yours.</p></div><div class="settings-fields"><div class="row spread"><div><h3>Password</h3><p class="hint">Update your sign-in password.</p></div>${button('Change password','data-change-password','small')}</div></div></section>`, 'settings')}
 function teamScreen(){return shellScreen(`<div class="product-heading"><div><h2>Your people.</h2><p>A little more company. A lot more possibility.</p></div>${button(icon('plus')+' Invite member','data-invite-member','primary')}</div><div class="team-summary"><div class="avatars"><span class="avatar"></span><span class="avatar blue"></span><span class="avatar mint"></span><span class="avatar-count">+${Math.max(0,members.length-3)}</span></div><span><strong>${members.length} teammates</strong><small>One shared workspace</small></span><span class="badge accent">Studio plan</span></div><div class="product-table-wrap">${table('members')}</div>`, 'team')}
 function projectsScreen(){return shellScreen(`<div class="product-heading"><div><h2>Work in good company.</h2><p>A home for everything you’re making.</p></div>${button(icon('plus')+' New project','data-create-record','primary')}</div><div class="project-overview"><div><span>In progress</span><strong>${projects.filter(x=>x.status==='Active').length}</strong></div><div><span>Ready for review</span><strong>${projects.filter(x=>x.status==='Review').length}</strong></div><div><span>Archived</span><strong>${projects.filter(x=>x.status==='Archived').length}</strong></div><div class="overview-note">${icon('circlecheck')}<span>A little progress,<br>every day.</span></div></div><div class="product-table-wrap">${table('projects')}</div>`, 'projects')}
 function authScreen(){let content='';if(onboardStep===0)content=`<span class="brand-mark"></span><h2>Good to see you.</h2><p>Sign in to your workspace.</p><form data-auth-form novalidate>${field('Email address','<input type="email" name="email" autocomplete="email" placeholder="you@studio.com" required>')}${password('Password','password')}<p class="form-error" role="alert" hidden></p><button class="button primary" type="submit">Continue ${icon('arrow')}</button></form><span class="auth-note">Demo sign-in · use any email and 8-character password.</span>`;
 else if(onboardStep===1)content=`<div class="onboard-progress"><span class="current"></span><span></span><span></span></div><h2>Make it your own.</h2><p>Start with a name for your workspace.</p><form data-onboard-workspace>${field('Workspace name',`<input name="workspace" required maxlength="60" value="${h(onboard.workspace)}" placeholder="Your studio">`)}${selectable('onboard-plan')}<div class="form-actions">${button('Back','data-onboard-back','ghost')}<button class="button primary" type="submit">Continue ${icon('arrow')}</button></div></form>`;
 else if(onboardStep===2)content=`<div class="onboard-progress"><span class="done"></span><span class="current"></span><span></span></div><h2>What brings you here?</h2><p>Give your workspace a starting point.</p><form data-onboard-purpose><fieldset class="purpose-options"><legend class="sr-only">Workspace purpose</legend>${['Product','Design','Research'].map((x,i)=>`<label class="choice"><input type="radio" name="purpose" value="${x}" ${onboard.purpose===x?'checked':''}>${icon(['layers','palette','search'][i])}${x}</label>`).join('')}</fieldset><div class="form-actions">${button('Back','data-onboard-back','ghost')}<button class="button primary" type="submit">Create workspace ${icon('arrow')}</button></div></form>`;
 else content=`<div class="onboard-progress"><span class="done"></span><span class="done"></span><span class="done"></span></div><div class="onboard-success">${icon('circlecheck')}</div><h2>You’re right at home.</h2><p><strong>${h(onboard.workspace)}</strong> is ready for its first idea.</p>${button('Open workspace '+icon('arrow'),'data-screen="projects"','primary')}${button('Start again','data-auth-reset','ghost small')}`;
 return `<div class="auth-stage"><div class="auth-art" aria-hidden="true"><div class="syntari-shape"><span></span><span></span><span></span></div><p>A little space.<br>A lot of possibility.</p></div><div class="auth-card">${content}</div></div>`}
 function showScreen(name){
  if(window.SyntariEmbed){window.dispatchEvent(new CustomEvent('syntari:navigate',{detail:{view:'screens',screen:name}}));return;}
  const url=new URL(location.href);url.searchParams.set('view','screens');url.searchParams.set('screen',name in screenMeta?name:'settings');url.searchParams.delete('category');history.replaceState(null,'',url);
  renderScreen(name,document.querySelector('#screens'));
 }
 function renderScreen(name,root){currentScreen=name in screenMeta?name:'settings';root.innerHTML=`<div class="screens-heading"><div><h2>Whole screens. Shared building blocks.</h2><p>Working patterns for your next product.</p></div><span class="badge accent">4 starter screens</span></div><nav class="screen-picker" aria-label="Starter screens">${[['settings','settings','Account settings'],['team','smile','Team management'],['projects','folder','Project workspace'],['onboarding','lock','Sign-in & onboarding']].map(([key,ic,label])=>`<button type="button" data-screen="${key}" class="${key===currentScreen?'active':''}" aria-current="${key===currentScreen?'page':'false'}">${icon(ic)}${label}</button>`).join('')}${window.SyntariEmbed&&!location.pathname.endsWith('preview.html')?`<a class="docs-screen-preview" href="preview.html?screen=${currentScreen}" target="_blank" rel="noopener">Open screen ${icon('external')}</a>`:''}</nav><div id="screen-stage">${{settings:settingsScreen,team:teamScreen,projects:projectsScreen,onboarding:authScreen}[currentScreen]()}</div>`;prepare(root);SyntariMotion.panel(root.querySelector('#screen-stage'));}
 function error(form,text,input){const target=form.querySelector('.form-error');if(target){target.hidden=false;target.textContent=text;if(!target.id)target.id=unique();if(input){input.setAttribute('aria-invalid','true');input.setAttribute('aria-describedby',target.id);input.focus()}}}
 function settingsValue(form){return {name:form.elements.name.value.trim(),email:form.elements.email.value.trim(),bio:form.elements.bio.value,digest:form.elements.digest.checked,updates:form.elements.updates.checked}}
 function settingsDirty(form){form.querySelector('.settings-savebar').hidden=JSON.stringify(settingsValue(form))===JSON.stringify(profile)}
 function refreshScreen(){const root=document.querySelector('#screens');if(window.SyntariEmbed&&root)renderScreen(currentScreen,root);else if(view==='screens')showScreen(currentScreen)}
 function prepare(root=document){window.SyntariNavigation.prepare(root);root.querySelectorAll('[data-starter-combo]').forEach(ensureCombo);root.querySelectorAll('[data-starter-table]').forEach(renderTable);root.querySelectorAll('.number-stepper').forEach(updateStepper);root.querySelectorAll('[data-unsaved-form]').forEach(form=>{if(!form.dataset.saved)form.dataset.saved=form.elements.workspace.value});root.querySelectorAll('[data-validation-form] input,[data-auth-form] input').forEach(input=>{if(!input.id)input.id=unique()});root.querySelectorAll('.selectable-cards').forEach(set=>{if(set.dataset.ready)return;set.dataset.ready='true';const inputs=set.querySelectorAll('input'),name=unique();inputs.forEach(input=>input.name=name)});}
 function updateStepper(root){const input=root.querySelector('input'),value=Number(input.value);root.querySelector('[data-number-step="-1"]').disabled=value<=Number(input.min);root.querySelector('[data-number-step="1"]').disabled=value>=Number(input.max)}
 document.addEventListener('input',e=>{
  const input=e.target,comboRoot=input.closest('[data-starter-combo]');if(comboRoot&&input.matches('input')){ensureCombo(comboRoot).active=-1;renderCombo(comboRoot)}
  if(input.matches('[data-command-search]'))renderCommands(input.value);
  if(input.closest('.table-search')){const root=input.closest('[data-starter-table]'),s=ensureTable(root);s.query=input.value;s.page=1;renderTable(root)}
  if(input.closest('.number-stepper'))updateStepper(input.closest('.number-stepper'));
  const draft=input.closest('[data-unsaved-form]');if(draft){const bar=draft.querySelector('.unsaved-bar'),dirty=input.value!==draft.dataset.saved;if(dirty?(bar.hidden||bar.inert):(!bar.hidden&&!bar.inert))SyntariMotion.visibility(bar,dirty);draft.querySelector('[data-saved-label]').textContent=input.value===draft.dataset.saved?'All changes saved.':'Your edits are ready to save.'}
  const settings=input.closest('[data-settings-form]');if(settings)settingsDirty(settings);
  if(input.hasAttribute('aria-invalid')){input.removeAttribute('aria-invalid');input.closest('form')?.querySelector('.form-error')?.setAttribute('hidden','')}
 });
 document.addEventListener('change',e=>{
  const input=e.target,root=input.closest('[data-starter-table]');if(root){const s=ensureTable(root);if(input.hasAttribute('data-table-select')){const id=Number(input.dataset.tableSelect);input.checked?s.selected.add(id):s.selected.delete(id)}if(input.hasAttribute('data-table-all'))s.visible.forEach(id=>input.checked?s.selected.add(id):s.selected.delete(id));if(input.hasAttribute('data-table-column'))s.columns[input.dataset.tableColumn]=input.checked;renderTable(root)}
  if(input.closest('[data-settings-form]'))settingsDirty(input.closest('[data-settings-form]'));
  if(input.closest('.number-stepper')){input.value=Math.min(Number(input.max),Math.max(Number(input.min),Number(input.value)||0));updateStepper(input.closest('.number-stepper'))}
 });
 document.addEventListener('focusin',e=>{const root=e.target.closest('[data-starter-combo]');if(root&&e.target.matches('input')){if(e.target.dataset.justSelected){delete e.target.dataset.justSelected;return}renderCombo(root)}});
 document.addEventListener('syntari:layout-change',e=>{if(e.target.classList.contains('mini-app-shell'))return;navigationPreference=e.detail;try{localStorage.setItem('syntari-navigation',JSON.stringify(navigationPreference))}catch{}});
 document.addEventListener('syntari:shell-action',e=>{
  const root=e.target,{action,key}=e.detail;if(!root.matches('[data-syntari-shell]'))return;e.preventDefault();window.SyntariNavigation.close();closeFloating();
  if(action==='navigate'||action==='settings'){
   const destination=action==='settings'?'settings':key;
   if(root.classList.contains('mini-app-shell')){window.SyntariNavigation.setActive(root,destination);root.querySelector('.syntari-mini-content').outerHTML=miniContent(destination);const heading=root.querySelector('[data-mini-heading]');heading.tabIndex=-1;heading.focus({preventScroll:true});SyntariMotion.panel(heading.parentElement)}else showScreen(destination);
  }
  if(action==='search')openCommand();
  if(action==='record')openRecord(projects.find(record=>record.id===Number(key)));
  if(action==='create')createRecord(false);
  if(action==='help')openLayer({title:'A little help, close by.',body:`<p class="layer-description">Move between projects, people, and settings from either navigation layout.</p><dl class="syntari-shortcuts"><div><dt>Search your workspace</dt><dd>⌘ / Ctrl K</dd></div><div><dt>Move through controls</dt><dd>Tab</dd></div><div><dt>Close a menu or drawer</dt><dd>Esc</dd></div></dl><p class="hint">Changes in this preview stay in your browser.</p>`});
 });
 document.addEventListener('click',e=>{
  const b=e.target.closest('button');if(!e.target.closest('[data-starter-combo],.starter-popover,.record-actions'))closeFloating();if(!b)return;const d=b.dataset;
  if(b.hasAttribute('data-simple-sort'))sortSimple(b.closest('[data-simple-table]'),d.simpleSort,b.parentElement.getAttribute('aria-sort')==='ascending');
  if(b.hasAttribute('data-simple-open'))openRecord(projects.find(r=>r.id===Number(d.simpleOpen)));
  if(b.hasAttribute('data-combo-option')){const root=b.closest('[data-starter-combo]');root.querySelector('input').dataset.justSelected='true';chooseCombo(root,d.comboOption)}
  if(b.hasAttribute('data-combo-remove')){const root=b.closest('[data-starter-combo]'),s=ensureCombo(root);s.selected=s.selected.filter(x=>x!==d.comboRemove);renderCombo(root,false);root.querySelector('input').focus()}
  if(b.hasAttribute('data-combo-clear')){const root=b.closest('[data-starter-combo]');root.querySelector('input').value='';if(root.dataset.mode!=='multiple')ensureCombo(root).selected=[];renderCombo(root);root.querySelector('input').focus()}
  if(b.hasAttribute('data-number-step')){const root=b.closest('.number-stepper'),input=root.querySelector('input');input.value=Math.min(Number(input.max),Math.max(Number(input.min),Number(input.value)+Number(d.numberStep)));input.dispatchEvent(new Event('input',{bubbles:true}));SyntariMotion.panel(input)}
  if(b.hasAttribute('data-password-toggle')){const input=b.parentElement.querySelector('input'),visible=input.type==='password';input.type=visible?'text':'password';b.setAttribute('aria-pressed',visible);b.setAttribute('aria-label',`${visible?'Hide':'Show'} password`);b.innerHTML=icon(visible?'eye-off':'eye')}
  if(b.hasAttribute('data-open-command'))openCommand();
  if(b.hasAttribute('data-command-index'))runCommand(Number(d.commandIndex));
  if(b.hasAttribute('data-screen'))showScreen(d.screen);
  if(b.hasAttribute('data-breadcrumb'))showToast('Workspace is the parent of Projects.');
  if(b.hasAttribute('data-open-drawer'))openRecord(projects[0]);
  if(b.hasAttribute('data-open-sheet'))openLayer({title:'Share workspace',kind:'bottom-sheet',body:`<p class="layer-description">Copy a link to this workspace or add a teammate.</p><div class="sheet-actions">${button(icon('link')+' Copy preview link','data-copy-preview-link')}${button(icon('plus')+' Invite a teammate','data-invite-member')}</div><p class="hint">Preview only. Invitations are not sent.</p>`});
  if(b.hasAttribute('data-copy-preview-link'))copy(location.href,'Preview link copied.');
  if(b.hasAttribute('data-popover-toggle')||b.hasAttribute('data-row-actions')){const panel=b.nextElementSibling,open=b.getAttribute('aria-expanded')==='true';closeFloating();if(!open){SyntariMotion.visibility(panel,true);b.setAttribute('aria-expanded','true');position(panel,b);panel.querySelector('button,input')?.focus()}}
  if(b.hasAttribute('data-demo-confirm'))confirmAction('Archive project?','The project will move to the archive in this preview.',()=>{showToast('Project archived in this preview.');b.textContent='Archived';b.disabled=true});
  if(b.hasAttribute('data-layer-confirm')){const action=layerAction;layerAction=null;SyntariMotion.closeDialog(layer());action?.()}
  if(b.hasAttribute('data-create-record'))createRecord(false);
  if(b.hasAttribute('data-invite-member'))createRecord(true);
  const tableRoot=b.closest('[data-starter-table]');
  if(tableRoot){const s=ensureTable(tableRoot);
   if(b.hasAttribute('data-table-sort')){s.direction=s.sort===d.tableSort?-s.direction:1;s.sort=d.tableSort;renderTable(tableRoot);tableRoot.querySelector(`[data-table-sort="${d.tableSort}"]`)?.focus()}
   if(b.hasAttribute('data-table-filter')){s.status=d.tableFilter;s.page=1;tableRoot.querySelector('[data-table-status]').innerHTML=h(s.status)+' '+icon('down');closeFloating(true);renderTable(tableRoot)}
   if(b.hasAttribute('data-table-page')){s.page+=Number(d.tablePage);renderTable(tableRoot)}
   if(b.hasAttribute('data-table-expand')){const id=Number(d.tableExpand);s.expanded.has(id)?s.expanded.delete(id):s.expanded.add(id);renderTable(tableRoot);tableRoot.querySelector(`[data-table-expand="${id}"]`)?.focus()}
   if(b.hasAttribute('data-table-reset')){s.query='';s.status='All statuses';s.page=1;tableRoot.querySelector('input[type=search]').value='';tableRoot.querySelector('[data-table-status]').innerHTML='All statuses '+icon('down');renderTable(tableRoot)}
   if(b.hasAttribute('data-record-edit'))openRecord(rowsFor(tableRoot).find(r=>r.id===Number(d.recordEdit)),tableRoot.dataset.kind);
   if(b.hasAttribute('data-record-archive')){const row=rowsFor(tableRoot).find(r=>r.id===Number(d.recordArchive)),restore=row.status==='Archived';closeFloating();confirmAction(restore?'Restore record?':'Archive record?',`${row.name} will ${restore?'return to active records':'move to the archive'}.`,()=>{row.status=restore?'Active':'Archived';refreshTables();showToast(restore?'Record restored.':'Record archived.');},restore?'Restore':'Archive')}
   if(b.hasAttribute('data-table-bulk')){const ids=[...s.selected];confirmAction(`Archive ${ids.length} records?`,'Selected records will remain available under Archived.',()=>{rowsFor(tableRoot).filter(r=>ids.includes(r.id)).forEach(r=>r.status='Archived');s.selected.clear();refreshTables();showToast(`${ids.length} records archived.`)})}
  }
  if(b.hasAttribute('data-date-range'))openRange(b);
  if(b.hasAttribute('data-range-day')){const chosen=d.rangeDay;if(rangeState.phase==='start'){rangeState.start=chosen;rangeState.end='';rangeState.phase='end'}else{rangeState.end=chosen;if(rangeState.end<rangeState.start)[rangeState.start,rangeState.end]=[rangeState.end,rangeState.start];rangeState.phase='start'}renderRange(chosen)}
  if(b.hasAttribute('data-range-month')){const date=dateFrom(rangeState.month);date.setDate(1);date.setMonth(date.getMonth()+Number(d.rangeMonth));rangeState.month=iso(date);renderRange();layer().querySelector(`[data-range-month="${d.rangeMonth}"]`)?.focus()}
  if(b.hasAttribute('data-range-preset')){const end=new Date(),start=new Date();start.setDate(end.getDate()-Number(d.rangePreset)+1);rangeState.start=iso(start);rangeState.end=iso(end);rangeState.month=iso(start);rangeState.phase='start';renderRange()}
  if(b.hasAttribute('data-range-apply')){const {trigger,start,end}=rangeState;trigger.dataset.start=start;trigger.dataset.end=end;trigger.querySelector('span').textContent=`${shortDate(start)} – ${shortDate(end)}, ${dateFrom(end).getFullYear()}`;SyntariMotion.closeDialog(layer())}
  if(b.hasAttribute('data-time-picker'))openTime(b);
  if(b.hasAttribute('data-time-option')){const wheel=b.closest('[data-time-wheel]');selectTimeWheel(wheel,b.dataset.timeOption);wheel.focus()}
  if(b.hasAttribute('data-retry')){b.disabled=true;b.innerHTML='<span class="spinner"></span> Loading…';const root=b.closest('.retry-demo');setTimeout(()=>{if(!root.isConnected)return;root.innerHTML=`<div class="empty-icon success-icon">${icon('circlecheck')}</div><h3>You’re up to date.</h3><p role="status">Your projects are ready.</p>${button('Simulate error','data-retry-reset','small ghost')}`;SyntariMotion.panel(root)},550)}
  if(b.hasAttribute('data-retry-reset')){const root=b.closest('.retry-demo');root.innerHTML=`<div class="empty-icon">${icon('info')}</div><h3>Couldn’t load your projects</h3><p>Try again to pick up where you left off.</p>${button('Try again','data-retry')}`}
  if(b.hasAttribute('data-upload-start')){const root=b.closest('.upload-demo');clearInterval(uploadJobs.get(root));root.classList.remove('is-complete');root.querySelector('.empty-icon').innerHTML=icon('upload');root.querySelector('[data-upload-cancel]').hidden=false;let progress=0;b.disabled=true;root.querySelector('[data-upload-cancel]').disabled=false;const meter=root.querySelector('[role=progressbar]');meter.setAttribute('aria-valuenow','0');meter.querySelector('span').style.width='0%';root.querySelector('[data-upload-label]').textContent='Uploading…';const job=setInterval(()=>{if(!root.isConnected){clearInterval(job);return}progress=Math.min(100,progress+10);meter.setAttribute('aria-valuenow',progress);meter.querySelector('span').style.width=progress+'%';if(progress%20===0)root.querySelector('[data-upload-label]').textContent=`Uploading ${progress}%`;if(progress===100){clearInterval(job);root.classList.add('is-complete');root.querySelector('.empty-icon').innerHTML=icon('circlecheck');SyntariMotion.panel(root.querySelector('.empty-icon'));SyntariMotion.feedback(root.querySelector('[data-upload-label]'),'Upload complete');root.querySelector('[data-upload-cancel]').hidden=true;b.textContent='Upload again';b.disabled=false;root.querySelector('[data-upload-cancel]').disabled=true}},120);uploadJobs.set(root,job)}
  if(b.hasAttribute('data-upload-cancel')){const root=b.closest('.upload-demo');clearInterval(uploadJobs.get(root));root.querySelector('[data-upload-label]').textContent='Upload cancelled';root.querySelector('[data-upload-start]').disabled=false;root.querySelector('[data-upload-start]').textContent='Try again';b.disabled=true;b.hidden=true;root.querySelector('[data-upload-start]').focus()}
  if(b.hasAttribute('data-discard-draft')){const form=b.closest('[data-unsaved-form]');form.elements.workspace.value=form.dataset.saved;SyntariMotion.visibility(form.querySelector('.unsaved-bar'),false);form.querySelector('[data-saved-label]').textContent='Changes discarded.';form.elements.workspace.focus()}
  if(b.hasAttribute('data-settings-discard'))showScreen('settings');
  if(b.hasAttribute('data-change-password'))openLayer({title:'Change password',body:`<form data-password-form novalidate>${password('New password')}${password('Confirm password','confirm')}<p class="form-error" role="alert" hidden></p><div class="form-actions">${button('Cancel','data-close','secondary')}<button type="submit" class="button primary">Update password</button></div><p class="hint">Preview only. Passwords are not stored.</p></form>`});
  if(b.hasAttribute('data-lightbox'))openLayer({title:d.lightbox,kind:'lightbox-layer',body:`<div class="large-art ${b.classList.contains('mint')?'mint':''}"><span class="asset-art" aria-hidden="true"><span></span><span></span><span></span></span></div><p class="hint">${h(d.lightbox)} · abstract asset preview</p>`});
  if(b.hasAttribute('data-onboard-back')){onboardStep=Math.max(0,onboardStep-1);showScreen('onboarding')}
  if(b.hasAttribute('data-auth-reset')){onboardStep=0;onboard={email:'',workspace:'',purpose:'Product'};showScreen('onboarding')}
 });
 document.addEventListener('submit',e=>{
  const form=e.target;if(!form.matches('[data-validation-form],[data-unsaved-form],[data-settings-form],[data-password-form],[data-record-form],[data-create-form],[data-time-form],[data-auth-form],[data-onboard-workspace],[data-onboard-purpose]'))return;e.preventDefault();
  if(form.hasAttribute('data-validation-form')){const input=form.elements.email;if(!input.validity.valid){error(form,'Enter a complete email address, such as you@studio.com.',input);return}form.querySelector('.form-error').hidden=true;input.removeAttribute('aria-invalid');showToast('Email looks good.');SyntariMotion.feedback(form.querySelector('.hint'),'Ready for the next step.');form.querySelector('[type=submit]').innerHTML=icon('check')+' Continue'}
  if(form.hasAttribute('data-unsaved-form')){if(!form.elements.workspace.value.trim()){form.elements.workspace.setCustomValidity('Enter a workspace name.');form.elements.workspace.reportValidity();form.elements.workspace.addEventListener('input',()=>form.elements.workspace.setCustomValidity(''),{once:true});return}form.dataset.saved=form.elements.workspace.value.trim();form.elements.workspace.value=form.dataset.saved;form.elements.workspace.focus();SyntariMotion.visibility(form.querySelector('.unsaved-bar'),false);form.querySelector('[data-saved-label]').textContent='All changes saved.';showToast('Workspace name saved.')}
  if(form.hasAttribute('data-settings-form')){if(!form.elements.name.value.trim()){error(form,'Enter your name.',form.elements.name);return}if(!form.elements.email.validity.valid){error(form,'Enter a complete email address.',form.elements.email);return}profile=settingsValue(form);let persisted=true;try{localStorage.setItem('syntari-profile',JSON.stringify(profile))}catch{persisted=false}form.querySelector('.settings-savebar').hidden=true;showToast(persisted?'Profile saved in this browser.':'Profile saved for this session.');refreshScreen()}
  if(form.hasAttribute('data-password-form')){if(form.elements.password.value.length<8){error(form,'Use at least 8 characters.',form.elements.password);return}if(form.elements.password.value!==form.elements.confirm.value){error(form,'The passwords need to match.',form.elements.confirm);return}form.reset();SyntariMotion.closeDialog(layer());showToast('Password update preview complete.')}
  if(form.hasAttribute('data-record-form')){const data=rowsFor({dataset:{kind:form.dataset.kind}}),row=data.find(r=>r.id===Number(form.dataset.id));if(!form.elements.name.value.trim()){error(form,'Enter a name.',form.elements.name);return}row.name=form.elements.name.value.trim();row.detail=form.elements.detail.value.trim();if(form.dataset.kind==='members')row.updated=form.elements.role.value;SyntariMotion.closeDialog(layer());refreshTables();showToast('Changes saved.')}
  if(form.hasAttribute('data-create-form')){const name=form.elements.name.value.trim(),detail=form.elements.detail.value.trim();if(!name){error(form,'Enter a name.',form.elements.name);return}const member=form.dataset.kind==='members';if(member&&members.some(x=>x.detail.toLowerCase()===detail.toLowerCase())){error(form,'This email already belongs to a teammate.',form.elements.detail);return}const id=Date.now();(member?members:projects).unshift({id,name,detail,status:member?'Invited':'Active',updated:member?'Member':iso(new Date()),owner:member?'Unassigned':profile.name});SyntariMotion.closeDialog(layer());refreshTables();refreshScreen();showToast(member?'Invitation added to this preview.':'Project created.')}
  if(form.hasAttribute('data-time-form')){const inputs=form.querySelectorAll('input'),trigger=form._timeTrigger,value=`${String(Number(inputs[0].value)).padStart(2,'0')}:${String(Number(inputs[1].value)).padStart(2,'0')}`;trigger.dataset.time=value;trigger.querySelector('span').textContent=value;SyntariMotion.closeDialog(layer())}
  if(form.hasAttribute('data-auth-form')){if(!form.elements.email.validity.valid){error(form,'Enter a valid email address.',form.elements.email);return}if(form.elements.password.value.length<8){error(form,'Use at least 8 characters for this demo.',form.elements.password);return}onboard.email=form.elements.email.value;form.elements.password.value='';onboardStep=1;showScreen('onboarding')}
  if(form.hasAttribute('data-onboard-workspace')){const name=form.elements.workspace.value.trim();if(!name){form.elements.workspace.setCustomValidity('Enter a workspace name.');form.elements.workspace.reportValidity();form.elements.workspace.addEventListener('input',()=>form.elements.workspace.setCustomValidity(''),{once:true});return}onboard.workspace=name;onboardStep=2;showScreen('onboarding')}
  if(form.hasAttribute('data-onboard-purpose')){onboard.purpose=form.elements.purpose.value;onboardStep=3;showScreen('onboarding')}
 });
 document.addEventListener('keydown',e=>{
  if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();e.stopImmediatePropagation();openCommand();return}
  const comboRoot=e.target.closest('[data-starter-combo]');if(comboRoot&&e.target.matches('input')){const s=ensureCombo(comboRoot),input=e.target,list=comboRoot.querySelector('[role=listbox]');if(['ArrowDown','ArrowUp','Home','End'].includes(e.key)){e.preventDefault();e.stopImmediatePropagation();if(list.hidden)renderCombo(comboRoot);s.active=e.key==='Home'?0:e.key==='End'?s.filtered.length-1:(s.active+(e.key==='ArrowDown'?1:-1)+s.filtered.length)%s.filtered.length;renderCombo(comboRoot);list.querySelector('.active')?.scrollIntoView({block:'nearest'})}if(e.key==='Enter'&&!list.hidden&&s.active>=0){e.preventDefault();e.stopImmediatePropagation();input.dataset.justSelected='true';chooseCombo(comboRoot,s.filtered[s.active])}if(e.key==='Escape'){e.preventDefault();e.stopImmediatePropagation();closeFloating()}if(e.key==='Tab')closeFloating();}
  if(e.target.matches('[data-command-search]')){if(['ArrowDown','ArrowUp'].includes(e.key)){e.preventDefault();commandIndex=(commandIndex+(e.key==='ArrowDown'?1:-1)+commands.length)%commands.length;document.querySelectorAll('#command-results [role=option]').forEach((x,i)=>x.setAttribute('aria-selected',i===commandIndex));e.target.setAttribute('aria-activedescendant',`command-${commandIndex}`)}if(e.key==='Enter'){e.preventDefault();runCommand(commandIndex)}}
  const panel=e.target.closest('.starter-popover-panel,.row-action-menu');if(panel&&e.key==='Escape'){e.preventDefault();e.stopImmediatePropagation();closeFloating(true)}
  const timeWheelRoot=e.target.closest('[data-time-wheel]');if(timeWheelRoot&&['ArrowDown','ArrowUp','PageDown','PageUp','Home','End'].includes(e.key)){e.preventDefault();const current=Number(timeWheelRoot.nextElementSibling.value),last=timeWheelRoot.querySelectorAll('[data-time-option]').length-1,value=e.key==='Home'?0:e.key==='End'?last:current+({ArrowDown:1,ArrowUp:-1,PageDown:5,PageUp:-5}[e.key]||0);selectTimeWheel(timeWheelRoot,value)}
  const day=e.target.closest('[data-range-day]');if(day&&['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();e.stopImmediatePropagation();const date=dateFrom(day.dataset.rangeDay);date.setDate(date.getDate()+({ArrowLeft:-1,ArrowRight:1,ArrowUp:-7,ArrowDown:7}[e.key]));const value=iso(date);if(!layer().querySelector(`[data-range-day="${value}"]`))rangeState.month=value;renderRange(value)}
 },true);
 function reposition(){document.querySelectorAll('.starter-options:not([hidden]),.starter-popover-panel:not([hidden]),.row-action-menu:not([hidden])').forEach(p=>{const t=p.parentElement.querySelector('.combo-input,[data-popover-toggle],[data-row-actions]');if(t)position(p,t)})}
 addEventListener('resize',reposition);addEventListener('scroll',reposition,true);
 function init(){categoryIcons.Layout='layout';register();const dialog=document.createElement('dialog');dialog.id='starter-dialog';dialog.setAttribute('aria-labelledby','starter-layer-title');document.body.append(dialog);dialog.addEventListener('close',()=>{layerAction=null;const cb=layerAfterClose;layerAfterClose=null;cb?.()});window.SyntariStarter={prepare,showScreen,renderScreen,openCommand,openProject:()=>openRecord(projects[0]),components:{combo,stepper,password,selectable,table,simpleTable,dateRange,timePicker,metadata,thumb,pageHeader,shell}};renderGallery();prepare(document);}
 init();
})();
