const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n);
const invoiceData=[
 {client:'Acme Studio',initials:'AC',invoice:'#INV-2048',status:'7 days overdue',kind:'overdue',due:'Sep 12',amount:3200},
 {client:'Northstar',initials:'NO',invoice:'#INV-2051',status:'Review draft',kind:'review',due:'Sep 16',amount:1850},
 {client:'Onda Agency',initials:'OA',invoice:'#INV-2054',status:'Scheduled',kind:'scheduled',due:'Sep 23',amount:4400},
 {client:'Koto Office',initials:'KO',invoice:'#INV-2056',status:'Verify payment',kind:'review',due:'Sep 17',amount:980},
 {client:'Luma Works',initials:'LW',invoice:'#INV-2059',status:'Current',kind:'scheduled',due:'Sep 28',amount:2450},
 {client:'Field Notes',initials:'FN',invoice:'#INV-2061',status:'Current',kind:'scheduled',due:'Oct 02',amount:1540}
];
const workflow={
 owed:{k:'STEP 01',title:'One clear view of your receivables.',copy:'Import invoices and instantly see what is outstanding, overdue, scheduled, or waiting for your review.',list:['Age every open invoice automatically','Surface only items that need attention','Keep client context beside the balance'],visual:`<div class="ledger-head"><span>Open balance</span><b>$18,420</b><small>Across 8 invoices</small></div><div class="aging"><span class="aging-current" style="width:46%"></span><span class="aging-mid" style="width:31%"></span><span class="aging-late" style="width:23%"></span></div><div class="aging-labels"><span><i class="current"></i> Current $8.4k</span><span><i class="mid"></i> 1–14d $5.7k</span><span><i class="late"></i> 15d+ $4.2k</span></div><div class="mini-ledger"><div><b>Acme Studio</b><span class="status overdue">7 days overdue</span><strong>$3,200</strong></div><div><b>Northstar</b><span class="status review">Review draft</span><strong>$1,850</strong></div><div><b>Onda Agency</b><span class="status scheduled">Scheduled</span><strong>$4,400</strong></div></div>`},
 move:{k:'STEP 02',title:'Make the next move obvious.',copy:'Morrow prepares the right follow-up using the invoice state, client history, and the tone you choose.',list:['Review before anything is sent','Friendly, neutral, and firm tone profiles','Automatically pause whenever a client replies'],visual:`<div class="card-title"><div><span class="spark">✦</span><div><h2>Draft ready</h2><p>Acme Studio · #INV-2048</p></div></div><span class="badge purple">Friendly</span></div><div class="email-preview" style="margin-top:22px"><span>Subject</span><b>Quick follow-up on invoice #INV-2048</b><hr><p>Hi Maya,</p><p>Just a quick follow-up on invoice #INV-2048 for $3,200, which was due last week.</p><p>Could you let me know when I should expect payment?</p></div><div class="compose-actions"><button class="button">Edit draft</button><a class="button dark" href="app.html#review">Review & schedule</a></div>`},
 close:{k:'STEP 03',title:'Stop the second the job is done.',copy:'Once payment is confirmed, Morrow closes the loop and cancels every future reminder in that sequence.',list:['Stop automatically on verified payments','Pause immediately on client reply','Keep a full activity trail for every action'],visual:`<div style="display:grid;place-items:center;min-height:340px;text-align:center;padding:30px"><div><div class="paid-check" style="width:52px;height:52px;margin:0 auto 18px;font-size:20px">✓</div><span class="step-kicker">PAYMENT CONFIRMED</span><h3 style="font-size:30px;margin:9px 0 8px">$3,200 received.</h3><p style="max-width:360px;color:var(--fg-3);font-size:11px">Acme Studio is marked paid. Two scheduled follow-ups were cancelled automatically.</p><div class="badge" style="margin-top:18px">Sequence closed · Sep 19, 11:42</div></div></div>`}
};
$$('.workflow-tab').forEach(btn=>btn.addEventListener('click',()=>{ $$('.workflow-tab').forEach(x=>x.classList.remove('active'));btn.classList.add('active'); const d=workflow[btn.dataset.workflow]; $('.step-kicker').textContent=d.k;$('#workflow-title').textContent=d.title;$('#workflow-copy').textContent=d.copy;$('#workflow-list').innerHTML=d.list.map(x=>`<li>${x}</li>`).join('');$('#workflow-visual').innerHTML=d.visual;}));
function toast(msg){const el=$('#toast');if(!el)return;el.textContent=msg;el.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>el.classList.remove('show'),2600)}
$$('[data-toast]').forEach(b=>b.addEventListener('click',()=>toast(b.dataset.toast)));
const isApp=document.body.classList.contains('product-app');
if(isApp){
 const panels=$$('[data-view-panel]'), nav=$$('.nav-item');
 function showView(view){panels.forEach(p=>p.classList.toggle('hidden',p.dataset.viewPanel!==view));nav.forEach(n=>n.classList.toggle('active',n.dataset.view===view));$('#crumb').textContent=view[0].toUpperCase()+view.slice(1);$('#sidebar').classList.remove('open')}
 nav.forEach(b=>b.addEventListener('click',()=>showView(b.dataset.view)));$$('[data-view-jump]').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.viewJump)));
 $('#menu-button')?.addEventListener('click',()=>$('#sidebar').classList.toggle('open'));
 $('#theme-toggle')?.addEventListener('click',()=>{const root=document.documentElement;root.dataset.theme=root.dataset.theme==='dark'?'light':'dark'});
 const ledger=$('#large-ledger');if(ledger) ledger.innerHTML=invoiceData.map(i=>`<div><span><i class="client-avatar ${i.kind==='overdue'?'ink':''}">${i.initials}</i><b>${i.client}</b></span><span>${i.invoice}</span><span><em class="status ${i.kind}">${i.status}</em></span><span>${i.due}</span><strong>${money(i.amount)}</strong></div>`).join('');
 $('#invoice-search')?.addEventListener('input',e=>{const q=e.target.value.toLowerCase();$$('#large-ledger>div').forEach((row,idx)=>row.hidden=!`${invoiceData[idx].client} ${invoiceData[idx].invoice}`.toLowerCase().includes(q))});
 $$('.filter').forEach(f=>f.addEventListener('click',()=>{$$('.filter').forEach(x=>x.classList.remove('active'));f.classList.add('active');toast(`${f.textContent} filter applied`)}));
 const clients=[['Acme Studio','AC','$3,200 open','Usually pays 4–8 days late'],['Northstar','NO','$1,850 open','Reply received today'],['Onda Agency','OA','$4,400 open','Pays on schedule'],['Koto Office','KO','$980 pending','Payment needs verification'],['Luma Works','LW','$2,450 open','New client'],['Field Notes','FN','$1,540 open','No follow-up needed']];
 $('#client-grid').innerHTML=clients.map(c=>`<article class="workspace-card client-card"><div class="client-card-head"><span class="client-avatar">${c[1]}</span><div><h3>${c[0]}</h3><p>${c[3]}</p></div></div><div class="client-balance"><span>Balance</span><b>${c[2]}</b></div></article>`).join('');
 const activity=[['✓','Payment confirmed','Koto Office · $980','11:42'],['↗','Reminder scheduled','Onda Agency · friendly','10:16'],['Ⅱ','Sequence paused','Northstar replied','09:54'],['✦','Draft created','Acme Studio · #INV-2048','09:31'],['+','Invoices imported','6 records from CSV','Yesterday']];
 $('#activity-list').innerHTML=activity.map(a=>`<div class="activity-item"><span>${a[0]}</span><div><b>${a[1]}</b><small>${a[2]}</small></div><time>${a[3]}</time></div>`).join('');
 const dialog=$('#review-dialog'); function openReview(client='Acme Studio'){ $('#dialog-client').textContent=client;dialog.showModal() }
 $$('[data-review]').forEach(b=>b.addEventListener('click',()=>openReview(b.dataset.review)));
 $$('.tone-picker button').forEach(b=>b.addEventListener('click',()=>{const parent=b.parentElement;$$('button',parent).forEach(x=>x.classList.remove('active'));b.classList.add('active')}));
 const confirm=$('#balance-confirm'),approve=$('#approve-button');confirm?.addEventListener('change',()=>approve.disabled=!confirm.checked);approve?.addEventListener('click',()=>{dialog.close();toast('Reminder approved · scheduled for tomorrow at 09:30');confirm.checked=false;approve.disabled=true});
 if(location.hash==='#review') setTimeout(()=>openReview(),100);
}
