import {test,expect} from '@playwright/test';
test('homepage previews components and leaves rendering to the Renderer',async({page})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:4398/');
 await expect(page.getByRole('heading',{name:'From intent to interface.'})).toBeVisible();
 await expect.poll(()=>page.evaluate(()=>document.fonts.check('16px Geist'))).toBe(true);
 await expect(page.locator('[data-home-count]')).toHaveText('131 components');
 await expect(page.locator('[data-intent-form]')).toHaveCount(0);
 await expect(page.locator('.home-faq')).toHaveCount(0);
 await expect(page.locator('.home-footer')).toBeVisible();
 await expect(page.locator('.home-wordmark')).toHaveCount(0);
 await page.locator('[data-home-gallery]').scrollIntoViewIfNeeded();
 await expect(page.locator('[data-home-preview="button"] [data-syntari-component]')).toBeVisible();
 await expect(page.locator('[data-home-preview="otp-input"] .home-otp-note')).toHaveText('Use 123456');
 await expect(page.locator('[data-home-preview="otp-input"] .otp-group')).toBeVisible();
 const otp=page.locator('[data-home-preview="otp-input"]');
 await expect(otp.locator('.otp-submit')).toHaveCount(0);
 await expect(page.locator('[data-home-preview="otp-input"]')).not.toContainText('Enter the six-digit code');
 for(const [index,digit] of ['1','2','3','4','5','6'].entries())await otp.locator('.otp-digit').nth(index).fill(digit);
 await expect(otp.locator('[data-otp-form]')).toHaveAttribute('data-otp-state','success');
 await expect(otp.locator('[data-otp-status]')).toHaveClass(/sr-only/);
 const approval=page.locator('[data-home-preview="tool-approval"]');
 await expect(approval).not.toContainText('Local demonstration');
 await approval.getByRole('button',{name:'Approve',exact:true}).click();
 await expect(approval.locator('.agent-footer')).toBeHidden();
 await expect(approval).not.toContainText('Reset preview');
 const chart=page.locator('[data-home-preview="chart-bars"]');
 await expect(chart.locator('.column-label')).toHaveText(['Jan','Feb','Mar','Apr','May','Jun']);
 await expect(chart).not.toContainText('Relative return');
 await expect(chart).not.toContainText('1995');
 const tabs=page.locator('[data-home-preview="tabs"]');
 await expect(tabs.getByRole('tab',{name:'Activity'})).toHaveAttribute('aria-selected','true');
 await expect(tabs.getByRole('tabpanel')).toContainText('Jamie published');
 await expect(page.locator('.home-card')).toHaveCount(6);
 await expect(page.locator('[data-home-command]')).toContainText('syntari-ui-0.2.2.tgz');
 await page.getByRole('link',{name:'Open Renderer',exact:true}).click();
 await expect(page).toHaveURL('http://127.0.0.1:4398/renderer/');
 await expect(page.locator('[data-intent-form]')).toBeVisible();
 expect(errors).toEqual([]);
});
test('homepage fits a phone and preserves theme through Renderer navigation',async({page})=>{
 await page.setViewportSize({width:390,height:844});await page.goto('http://127.0.0.1:4398/');
 await page.getByRole('button',{name:'Switch to light theme'}).click();
 await expect(page.locator('html')).toHaveAttribute('data-theme','light');
 await expect(page.locator('[data-intent-form]')).toHaveCount(0);
 await expect(page.locator('.home-faq')).toHaveCount(0);
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await page.getByRole('link',{name:'Open Renderer',exact:true}).click();
 await expect(page).toHaveURL(/\/renderer\//);await expect(page.locator('html')).toHaveAttribute('data-theme','light');
 await expect(page.locator('[data-intent-form]')).toBeVisible();
});
