import { setTheme } from './theme.mjs';
import {test,expect} from '@playwright/test';

const expectFullCatalog=async page=>{const expected=await page.evaluate(async()=>(await import('/syntari.js')).getComponents().then(list=>list.length));await expect(page.locator('.specimen')).toHaveCount(expected);};
test('starter controls and screens',async({page})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:4398/gallery.html');
 const c=name=>page.locator(`[data-component="${name}"]`);
 await c('Searchable select').getByRole('combobox').fill('Jamie');await page.keyboard.press('ArrowDown');await page.keyboard.press('Enter');await expect(c('Searchable select').getByRole('combobox')).toHaveValue('Jamie Chen');
 await c('Multiselect').getByRole('combobox').fill('Design');await c('Multiselect').getByRole('option',{name:'Design',exact:true}).click();await expect(c('Multiselect').getByRole('button',{name:'Remove Design'})).toBeVisible();await c('Multiselect').getByRole('button',{name:'Remove Design'}).click();await expect(c('Multiselect').getByRole('button',{name:'Remove Design'})).toHaveCount(0);
 await c('Number stepper').getByRole('button',{name:'Increase Seats'}).click();await expect(c('Number stepper').getByRole('spinbutton')).toHaveValue('4');
 await c('Password field').getByLabel('Password',{exact:true}).fill('syntari1234');await c('Password field').getByRole('button',{name:'Show password'}).click();await expect(c('Password field').getByLabel('Password',{exact:true})).toHaveAttribute('type','text');
 await c('Date range picker').locator('[data-date-range]').click();await page.getByRole('button',{name:'September 5, 2026',exact:true}).click();await page.getByRole('button',{name:'September 12, 2026',exact:true}).click();await page.locator('[data-range-apply]').click();await expect(page.locator('#starter-dialog')).not.toBeVisible();await expect(c('Date range picker').locator('[data-date-range]')).toHaveAttribute('data-end','2026-09-12');
 await c('Time picker').locator('[data-time-picker]').click();const hours=page.getByRole('listbox',{name:'Hours'});await expect(hours.getByRole('option',{selected:true})).toHaveText('09');await hours.press('ArrowDown');await expect(hours.getByRole('option',{selected:true})).toHaveText('10');await page.getByRole('button',{name:'Apply time'}).click();await expect(c('Time picker').locator('[data-time-picker]')).toHaveAttribute('data-time','10:30');await expect(page.locator('#starter-dialog')).not.toBeVisible();
 await c('Data table').getByRole('searchbox').fill('Brand');await expect(c('Data table').locator('tbody tr')).toHaveCount(1);await c('Data table').getByRole('checkbox',{name:'Select Brand refresh'}).check();await expect(c('Data table').locator('[data-table-selection]')).toBeVisible();await c('Data table').getByRole('button',{name:'Brand refresh Jamie Chen',exact:true}).click();await expect(c('Data table').locator('.expanded-record')).toBeVisible();
 await page.locator('.docs-sidebar [data-view="screens"]').click();await page.locator('[data-settings-form] input[name=name]').fill('Robin');await expect(page.locator('.settings-savebar')).toBeVisible();await page.getByRole('button',{name:'Save changes',exact:true}).click();await expect(page.locator('.settings-savebar')).not.toBeVisible();
 await page.locator('.screen-picker [data-screen="projects"]').click();await page.locator('#screens [data-create-record]').click();await page.locator('#starter-dialog input[name=name]').fill('New test project');await page.locator('#starter-dialog input[name=detail]').fill('Test description');await page.locator('#starter-dialog [type=submit]').click();await expect(page.locator('#starter-dialog')).not.toBeVisible();await page.locator('#screens .table-search input').fill('New test');await expect(page.locator('#screens .record-name')).toContainText('New test project');
 await page.locator('.screen-picker [data-screen="onboarding"]').click();await page.locator('[data-auth-form] input[type=email]').fill('robin@example.com');await page.locator('[data-auth-form] input[type=password]').fill('syntari1234');await page.locator('[data-auth-form] [type=submit]').click();await page.locator('[data-onboard-workspace] input[name=workspace]').fill('Test Studio');await page.locator('[data-onboard-workspace] [type=submit]').click();await page.locator('[data-onboard-purpose] [type=submit]').click();await expect(page.locator('.auth-card')).toContainText('Test Studio');
 await page.keyboard.press('Control+k');await page.getByRole('combobox',{name:'Search commands'}).fill('Account settings');await page.keyboard.press('Enter');await expect(page.locator('[data-settings-form]')).toBeVisible();
 for(const theme of ['Light theme','Dark theme']){await setTheme(page,theme);await page.setViewportSize({width:390,height:844});await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();await page.setViewportSize({width:1440,height:1000})}
 expect(errors).toEqual([]);
});
test('agent workflows',async({page})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:4398/gallery.html');await page.locator('[data-category="Agents"]').click();const c=name=>page.locator(`[data-component="${name}"]`);
 await c('Agent todo list').getByRole('button',{name:'Run plan'}).click();await expect(c('Agent todo list').locator('[data-todo-count]')).toHaveText('4 of 4 completed',{timeout:6000});await c('Agent todo list').getByRole('button',{name:'Replay'}).click();await c('Agent todo list').getByRole('button',{name:'Stop plan'}).click();await expect(c('Agent todo list').locator('[data-run-status]')).toContainText('stopped');
 await c('Approval card').getByRole('button',{name:'Approve',exact:true}).click();await expect(c('Approval card').locator('.agent-decision')).toContainText('Approved');await c('Approval card').getByRole('button',{name:'Reset preview'}).click();await c('Approval card').getByRole('button',{name:'Decline'}).click();await expect(c('Approval card').locator('.agent-decision')).toContainText('Declined');
 await c('Streaming response').getByRole('button',{name:'Generate response'}).click();await expect(c('Streaming response').locator('[data-stream-status]')).toHaveText('Response complete.');await c('Streaming response').getByRole('button',{name:'Regenerate'}).click();await c('Streaming response').getByRole('button',{name:'Stop'}).click();await expect(c('Streaming response').locator('[data-stream-status]')).toHaveText('Response stopped.');
 await c('Chat workspace').getByRole('textbox').fill('<script>local text</script>');await c('Chat workspace').getByRole('button',{name:'Send message'}).click();await expect(c('Chat workspace').locator('.user-message')).toHaveText('<script>local text</script>');await c('Chat workspace').getByRole('button',{name:'New chat'}).click();await expect(c('Chat workspace').locator('.user-message')).toHaveCount(0);
 await setTheme(page,'dark');await page.screenshot({path:'test-results/agents-dark.png'});await page.setViewportSize({width:390,height:844});await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();await page.screenshot({path:'test-results/agents-mobile.png'});await page.emulateMedia({reducedMotion:'reduce'});await c('Streaming response').getByRole('button',{name:'Regenerate'}).click();await expect(c('Streaming response').locator('[data-stream-status]')).toHaveText('Response complete.');expect(errors).toEqual([]);
});
test('remaining catalog patterns and responsive coverage',async({page})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:4398/gallery.html');const c=name=>page.locator(`[data-component="${name}"]`);
 await expectFullCatalog(page);
 await c('Data table').getByRole('button',{name:'All statuses',exact:true}).click();await c('Data table').getByRole('button',{name:'Review',exact:true}).click();await expect(c('Data table').locator('tbody tr')).toHaveCount(2);
 const fillOtp=async value=>{const digits=c('OTP input').locator('.otp-digit');for(let i=0;i<value.length;i++)await digits.nth(i).fill(value[i]);};await fillOtp('111111');await c('OTP input').getByRole('button',{name:'Verify code'}).click();await expect(c('OTP input').getByRole('status')).toContainText('did not match');await fillOtp('123456');await c('OTP input').getByRole('button',{name:'Verify code'}).click();await expect(c('OTP input').getByRole('status')).toContainText('verified');
 await c('Range slider').getByRole('slider',{name:'Minimum budget'}).fill('900');await expect(c('Range slider').getByRole('slider',{name:'Maximum budget'})).toHaveValue('900');
 await c('Availability scheduler').getByRole('button',{name:'Tue',exact:true}).click();await c('Availability scheduler').getByRole('button',{name:'14:00'}).click();await c('Availability scheduler').getByRole('button',{name:'Confirm time'}).click();await expect(c('Availability scheduler').getByRole('status')).toContainText('Tuesday at 14:00');
 await c('Context menu').getByRole('button',{name:'Actions',exact:true}).click();await page.keyboard.press('ArrowDown');await page.keyboard.press('Enter');await expect(c('Context menu').getByRole('status')).toContainText('Rename');
 await c('Swipeable list').getByRole('button',{name:'Archive',exact:true}).first().click();await expect(c('Swipeable list').locator('.swipe-item')).toHaveCount(2);await c('Swipeable list').getByRole('button',{name:'Undo'}).click();await expect(c('Swipeable list').locator('.swipe-item')).toHaveCount(3);
 await c('Masonry grid').getByRole('button',{name:'Load more'}).click();await expect(c('Masonry grid').locator('.masonry-grid>div')).toHaveCount(7);
 await c('Wallet card').getByRole('button',{name:'Hide balance'}).click();await expect(c('Wallet card').locator('[data-wallet-balance]')).toHaveText('••••••');await c('Wallet card').getByRole('button',{name:'Show balance'}).click();await expect(c('Wallet card').locator('[data-wallet-balance]')).toHaveText('$1,250.00');
 await c('Agent questions').getByRole('radio',{name:'Accessibility',exact:true}).check();await c('Agent questions').getByRole('button',{name:'Review response'}).click();await expect(c('Agent questions').getByRole('status')).toContainText('accessibility');await c('Agent questions').getByRole('button',{name:'Confirm response'}).click();await expect(c('Agent questions').getByRole('status')).toContainText('saved');
 await c('Prompt input').getByLabel('Attach a file').setInputFiles({name:'sample.txt',mimeType:'text/plain',buffer:Buffer.from('local preview')});await expect(c('Prompt input').locator('[data-attachment-name]')).toHaveText('sample.txt');
 for(const width of [390,768,1440]){await page.setViewportSize({width,height:900});for(const theme of ['Light theme','Dark theme']){await setTheme(page,theme);await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy()}}
 await page.goto('http://127.0.0.1:4398/gallery.html?view=screens&screen=projects');await expect(page.locator('#screens')).toBeVisible();await expect(page.locator('#screens .product-heading')).toContainText('Work in good company');expect(errors).toEqual([]);
});
