import {test,expect} from '@playwright/test';
const origin='http://127.0.0.1:4398';
test('System preserves the live component while inspecting contracts, code and installation',async({page,context})=>{
 const errors=[];page.on('pageerror',error=>errors.push(error.message));
 await context.grantPermissions(['clipboard-read','clipboard-write']);
 await page.route('**/registry/index.json',async route=>{await new Promise(resolve=>setTimeout(resolve,1500));await route.continue();});
 await page.goto(origin+'/system/#button');
 await expect(page.locator('[data-preview-loader]')).toBeVisible();
 await expect(page.locator('[data-preview-loader] .brand-mark')).toBeVisible();
 await expect(page.locator('[data-preview-skeleton]')).toHaveCount(0);
 const preview=page.locator('[data-component-mount] > [data-syntari-component]');
 await expect(preview).toHaveAttribute('data-syntari-component','button');
 await expect(page.locator('[data-component-count]')).toHaveText('131');
 expect(await page.locator('.sys-workspace').evaluate(el=>el.getBoundingClientRect().width/innerWidth)).toBeGreaterThan(.75);
 const initial=await preview.elementHandle();
 await page.getByRole('button',{name:'Inspect component'}).click();
 await expect(page.locator('[data-contract-status]')).toHaveText('Authored contract');
 await expect(page.locator('[data-rules]')).not.toBeEmpty();
 await expect(page.locator('[data-info-panel]')).toBeVisible();
 await expect(page.locator('[data-inspector] .sys-reference-tabs')).toHaveCount(0);
 expect(await page.evaluate(el=>el===document.querySelector('[data-syntari-component]'),initial)).toBe(true);
 await page.getByRole('button',{name:'View code'}).click();
 await expect(page.locator('[data-workspace]')).toHaveAttribute('data-panel','code');
 await expect(page.locator('[data-code-panel]')).toBeVisible();
 await page.getByRole('button',{name:'Manifest',exact:true}).click();
 await expect(page.locator('[data-source]')).toContainText('"id": "button"');
 await page.getByRole('button',{name:'Install',exact:true}).click();
 await expect(page.locator('[data-install-command]')).toContainText('syntari-ui-0.2.2.tgz -- syntari add button');
 await expect(page.locator('[data-workspace]')).toHaveAttribute('data-panel','install');
 const drawer=await page.locator('[data-inspector]').boundingBox(),stage=await page.locator('[data-stage]').boundingBox(),workspace=await page.locator('.sys-workspace').boundingBox();
 expect(Math.abs(stage.x+stage.width-drawer.x)).toBeLessThan(3);
 expect(Math.abs(drawer.x+drawer.width-(workspace.x+workspace.width))).toBeLessThan(3);
 expect(Math.abs(stage.y+stage.height-(workspace.y+workspace.height))).toBeLessThan(3);
 await expect(page.locator('[data-inspector] .sys-reference-tabs')).toHaveCount(0);
 await page.getByRole('button',{name:'Copy command'}).click();
 expect(await page.evaluate(()=>navigator.clipboard.readText())).toContain('syntari add button');
 await expect(page.locator('[data-copy-status]')).toContainText('Copied');
 await page.getByRole('button',{name:'Close panel'}).click();
 await page.getByRole('searchbox',{name:'Find a component'}).fill('app shell');
 await page.locator('[data-slug="app-shell"]').click();
 await expect(preview).toHaveAttribute('data-syntari-component','app-shell');
 await expect(page).toHaveURL(/system\/#app-shell$/);
 await page.goBack();
 await expect(preview).toHaveAttribute('data-syntari-component','button');
 expect(errors).toEqual([]);
});
test('System component routes, mobile navigation, states and inspector focus work',async({page})=>{
 await page.setViewportSize({width:390,height:844});
 await page.goto(origin+'/components/slider/');
 await expect(page.locator('[data-syntari-component="slider"]')).toBeVisible();
 await page.getByRole('button',{name:'Open System navigation'}).click();
 await page.getByRole('searchbox',{name:'Find a component'}).fill('tool approval');
 await page.locator('[data-slug="tool-approval"]').click();
 await expect(page.locator('[data-syntari-component="tool-approval"]')).toBeVisible();
 await page.getByRole('button',{name:'Inspect component'}).click();
 await expect(page.locator('[data-inspector]')).toBeVisible();
 await expect(page.locator('[data-ir-support]')).toContainText('Screen IR supported');
 await page.keyboard.press('Escape');
 await expect(page.getByRole('button',{name:'Inspect component'})).toBeFocused();
 await page.getByRole('button',{name:'Install',exact:true}).click();
 await expect(page.locator('[data-workspace]')).toHaveAttribute('data-panel','install');
 await expect(page.getByRole('button',{name:'View code'})).toBeVisible();
 await expect.poll(()=>page.evaluate(()=>{const workspace=document.querySelector('.sys-workspace').getBoundingClientRect(),drawer=document.querySelector('[data-inspector]').getBoundingClientRect();return Math.abs(workspace.left-drawer.left)<3&&Math.abs(workspace.right-drawer.right)<3})).toBe(true);
 await page.getByRole('button',{name:'View code'}).click();
 await expect(page.locator('[data-workspace]')).toHaveAttribute('data-panel','code');
 await expect(page.locator('[data-code-panel]')).toBeVisible();
 await page.keyboard.press('Escape');
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await page.getByRole('button',{name:'Open System navigation'}).click();
 await page.getByRole('searchbox',{name:'Find a component'}).fill('slider');
 await page.locator('[data-slug="slider"]').click();
 await page.locator('[data-states]').getByRole('button',{name:'Disabled'}).click();
 await expect(page.getByRole('slider',{name:'Monthly events'})).toBeDisabled();
});
