import { test, expect } from '@playwright/test';
import { setTheme } from './theme.mjs';
const origin = 'http://127.0.0.1:4318';

test('gallery and documentation share one document, filters, theme and browser history', async ({page}) => {
  const errors = []; page.on('pageerror', error => errors.push(error.message));
  await page.goto(origin + '/library.html');
  await page.getByRole('link', {name: 'Explore components', exact: true}).waitFor();
  await page.evaluate(() => { window.shellHeader = document.querySelector('.docs-header'); });
  await page.getByRole('link', {name: 'Explore components', exact: true}).click();
  await expect(page.locator('.specimen')).toHaveCount(107);
  await expect(page.locator('#view-gallery')).toHaveAttribute('aria-current', 'page');
  await page.locator('[data-category="Action"]').click();
  await page.locator('[data-category="Form controls"]').click();
  await page.goBack();
  await expect(page.locator('#section-name')).toContainText('Action');
  await page.goForward();
  await expect(page.locator('#section-name')).toContainText('Form controls');
  await page.locator('#search').fill('slider');
  await expect(page.locator('.specimen')).toHaveCount(2);
  await setTheme(page, 'dark');
  await page.getByRole('link', {name: 'View Slider documentation', exact: true}).click();
  await expect(page.locator('h1')).toHaveText('Slider');
  await expect(page.locator('#view-documentation')).toHaveAttribute('aria-current', 'page');
  await page.getByRole('button', {name: 'Maximum', exact: true}).click();
  await expect(page.locator('#live-example input')).toHaveValue('50000');
  await page.locator('#view-documentation').click();
  await expect(page.locator('#live-example input')).toHaveValue('50000');
  await page.locator('#view-gallery').click();
  await expect(page.locator('#search')).toHaveValue('slider');
  await expect(page.locator('#section-name')).toContainText('Form controls');
  await expect(page.locator('.specimen')).toHaveCount(2);
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark');
  expect(await page.evaluate(() => window.shellHeader === document.querySelector('.docs-header'))).toBe(true);
  await expect(page.locator('script[src$="/app.js"]')).toHaveCount(1);
  await page.locator('#view-documentation').click();
  await page.locator('.docs-sidebar .brand').click();
  await expect(page).toHaveURL(origin + '/library.html');
  await page.locator('#view-gallery').click();
  await page.reload();
  await expect(page.locator('#search')).toHaveValue('slider');
  await expect(page.locator('.specimen')).toHaveCount(2);
  expect(errors).toEqual([]);
});

test('returning from component documentation restores the gallery position', async ({page}) => {
  await page.emulateMedia({reducedMotion: 'reduce'});
  await page.goto(origin + '/gallery.html?category=Form+controls');
  const link = page.getByRole('link', {name: 'View Slider documentation', exact: true});
  await link.scrollIntoViewIfNeeded();
  const position = await page.evaluate(() => scrollY);
  expect(position).toBeGreaterThan(500);
  await link.click();
  await expect(page.locator('h1')).toHaveText('Slider');
  await page.goBack();
  await expect(page.locator('#search')).toBeVisible();
  await expect.poll(async () => Math.abs(await page.evaluate(() => scrollY) - position)).toBeLessThan(8);
  await link.click();
  await expect(page.locator('h1')).toHaveText('Slider');
  await page.locator('#view-gallery').click();
  await expect.poll(async () => Math.abs(await page.evaluate(() => scrollY) - position)).toBeLessThan(8);
  await page.locator('.docs-sidebar [data-view="gallery"]').click();
  await expect.poll(() => page.evaluate(() => scrollY)).toBe(0);
});

test('mobile navigation, keyboard search and starter links stay inside Syntari', async ({page}) => {
  const errors = []; page.on('pageerror', error => errors.push(error.message));
  await page.setViewportSize({width: 390, height: 844});
  await page.emulateMedia({reducedMotion: 'reduce'});
  await page.goto(origin + '/components/button/');
  await page.locator('.syntari-component').waitFor();
  await page.evaluate(() => { window.shellHeader = document.querySelector('.docs-header'); });
  await page.locator('#view-gallery').click();
  await page.keyboard.press('/');
  await expect(page.locator('#search')).toBeFocused();
  await page.locator('#search').fill('nonexistent');
  await expect(page.locator('#empty')).toBeVisible();
  await page.getByRole('button', {name: 'Clear search', exact: true}).click();
  await expect(page.locator('.specimen')).toHaveCount(107);
  await page.locator('#docs-menu').click();
  await expect(page.locator('.docs-sidebar [data-view="gallery"]')).toBeFocused();
  await page.locator('[data-category="Form controls"]').click();
  await expect(page.locator('body')).not.toHaveClass(/nav-open/);
  await expect(page.locator('.docs-sidebar')).toHaveJSProperty('inert', true);
  await page.locator('#docs-menu').click();
  await page.locator('.docs-sidebar [data-view="screens"]').click();
  await page.locator('.screen-picker [data-screen="projects"]').click();
  await expect(page.locator('#screens .product-heading')).toContainText('Work in good company');
  await page.locator('#docs-menu').click();
  await page.locator('.docs-sidebar [data-view="foundations"]').click();
  await expect(page.locator('.swatch')).toHaveCount(12);
  await setTheme(page, 'dark');
  const download = page.waitForEvent('download');
  await page.getByRole('button', {name: 'Export tokens', exact: true}).click();
  expect((await download).suggestedFilename()).toBe('syntari-tokens.css');
  await page.keyboard.press('/');
  await expect(page.locator('#search')).toBeFocused();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  expect(await page.evaluate(() => window.shellHeader === document.querySelector('.docs-header'))).toBe(true);
  expect(errors).toEqual([]);
});
